; Generated by gen.sh from Inputs/bad_peer_per_team.cpp -- do not edit.
;
; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-chunk-analysis -disable-output %s 2>&1 | %FileCheck %s
;
; // The peer is read from memory, so it may differ between teams.
; #include <cstddef>
; typedef long long llint;
; #pragma omp declare target
; extern "C" void ompx_pipelined_put(int peer, void* dst, const void* src, size_t bytes);
; #pragma omp end declare target
;
; void step(float* a, const int* peers, llint nx, llint ny, float s) {
;     #pragma omp target teams is_device_ptr(a, peers) firstprivate(nx, ny, s)
;     {
;         #pragma omp distribute parallel for collapse(2)
;         for (llint i = 0; i < nx; ++i)
;             for (llint j = 0; j < ny; ++j)
;                 a[i * ny + j] = s;
;         ompx_pipelined_put(peers[0], a, a, nx * ny * sizeof(float));
;     }
; }
;
; // CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfPKixxf_l{{[0-9]+}}
; // CHECK-NEXT: ompx_pipelined_put: ILLEGAL: peer or dst differs between teams

source_filename = "Inputs/bad_peer_per_team.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_plugin_enable_fast_reduction = weak addrspace(1) constant i8 0
@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 0, i8 1, i32 1, i32 257, i32 0, i32 0, i32 0, i32 0 }, ptr addrspacecast (ptr addrspace(1) @1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_dynamic_environment to ptr) }
@2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_wg_size = weak addrspace(1) constant i16 257
@__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_exec_mode = weak addrspace(1) constant i8 1
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600
@_shared = internal addrspace(3) global [4 x i8] poison, align 16
@_shared.1 = internal addrspace(3) global [8 x i8] poison, align 16
@_shared.2 = internal addrspace(3) global [8 x i8] poison, align 16
@_shared.3 = internal addrspace(3) global [8 x i8] poison, align 16
@llvm.compiler.used = appending addrspace(1) global [3 x ptr] [ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_exec_mode to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_wg_size to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_plugin_enable_fast_reduction to ptr)], section "llvm.metadata"

; Function Attrs: alwaysinline convergent norecurse nounwind
define weak_odr protected amdgpu_kernel void @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3, i64 noundef %4, ptr noundef %5) local_unnamed_addr #0 {
  %7 = alloca i64, align 8, addrspace(5)
  %8 = alloca i64, align 8, addrspace(5)
  %9 = alloca i64, align 8, addrspace(5)
  %10 = alloca i32, align 4, addrspace(5)
  %11 = alloca [6 x ptr], align 8, addrspace(5)
  %12 = addrspacecast ptr %5 to ptr addrspace(1)
  %13 = tail call i32 @__kmpc_target_init(ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_kernel_environment to ptr), ptr %0) #2
  %14 = icmp eq i32 %13, -1
  br i1 %14, label %16, label %15

15:                                               ; preds = %6, %54
  ret void

16:                                               ; preds = %6
  %17 = tail call i32 @__kmpc_global_thread_num(ptr addrspacecast (ptr addrspace(1) @1 to ptr)) #2
  call void @llvm.lifetime.start.p5(i64 48, ptr addrspace(5) %11)
  %18 = addrspacecast ptr addrspace(5) %11 to ptr
  %19 = trunc i64 %4 to i32
  store i64 %1, ptr addrspace(3) @_shared.3, align 16, !tbaa !9, !noalias !13
  store i64 %2, ptr addrspace(3) @_shared.2, align 16, !tbaa !9, !noalias !13
  store ptr %3, ptr addrspace(3) @_shared.1, align 16, !tbaa !16, !noalias !13
  store i32 %19, ptr addrspace(3) @_shared, align 16, !tbaa !18, !noalias !13
  %20 = icmp sgt i64 %1, 0
  %21 = icmp sgt i64 %2, 0
  %22 = and i1 %20, %21
  br i1 %22, label %23, label %54

23:                                               ; preds = %16
  %24 = addrspacecast ptr addrspace(5) %9 to ptr
  %25 = addrspacecast ptr addrspace(5) %8 to ptr
  %26 = addrspacecast ptr addrspace(5) %7 to ptr
  %27 = mul nuw nsw i64 %2, %1
  %28 = add nsw i64 %27, -1
  %29 = addrspacecast ptr addrspace(5) %10 to ptr
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %7) #2, !noalias !13
  store i64 0, ptr addrspace(5) %7, align 8, !tbaa !9, !noalias !13
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %8) #2, !noalias !13
  store i64 %28, ptr addrspace(5) %8, align 8, !tbaa !9, !noalias !13
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %9) #2, !noalias !13
  store i64 1, ptr addrspace(5) %9, align 8, !tbaa !9, !noalias !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %10) #2, !noalias !13
  store i32 0, ptr addrspace(5) %10, align 4, !tbaa !20, !noalias !13
  call void @__kmpc_distribute_static_init_8(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %17, i32 92, ptr nonnull %29, ptr nonnull %26, ptr nonnull %25, ptr nonnull %24, i64 1, i64 1) #2, !noalias !13
  %30 = load i64, ptr addrspace(5) %8, align 8, !noalias !13
  %31 = call i64 @llvm.smin.i64(i64 %30, i64 %28)
  store i64 %31, ptr addrspace(5) %8, align 8, !tbaa !9, !noalias !13
  %32 = load i64, ptr addrspace(5) %7, align 8, !tbaa !9, !noalias !13
  %33 = icmp sgt i64 %32, %31
  br i1 %33, label %50, label %34

34:                                               ; preds = %23
  %35 = getelementptr inbounds i8, ptr addrspace(5) %11, i32 8
  %36 = getelementptr inbounds i8, ptr addrspace(5) %11, i32 16
  %37 = getelementptr inbounds i8, ptr addrspace(5) %11, i32 24
  %38 = getelementptr inbounds i8, ptr addrspace(5) %11, i32 32
  %39 = getelementptr inbounds i8, ptr addrspace(5) %11, i32 40
  br label %40

40:                                               ; preds = %40, %34
  %41 = phi i64 [ %31, %34 ], [ %48, %40 ]
  %42 = phi i64 [ %32, %34 ], [ %47, %40 ]
  %43 = load i64, ptr addrspace(5) %7, align 8, !noalias !13
  %44 = inttoptr i64 %43 to ptr
  store ptr %44, ptr addrspace(5) %11, align 8, !tbaa !16, !noalias !13
  %45 = inttoptr i64 %41 to ptr
  store ptr %45, ptr addrspace(5) %35, align 8, !tbaa !16, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared.3 to ptr), ptr addrspace(5) %36, align 8, !tbaa !16, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared.2 to ptr), ptr addrspace(5) %37, align 8, !tbaa !16, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared.1 to ptr), ptr addrspace(5) %38, align 8, !tbaa !16, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared to ptr), ptr addrspace(5) %39, align 8, !tbaa !16, !noalias !13
  call void @__kmpc_parallel_51(ptr addrspacecast (ptr addrspace(1) @1 to ptr), i32 %17, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined, ptr nonnull @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined_wrapper, ptr nonnull %18, i64 6) #2, !noalias !13
  %46 = load i64, ptr addrspace(5) %9, align 8, !tbaa !9, !noalias !13
  %47 = add nsw i64 %46, %42
  %48 = load i64, ptr addrspace(5) %8, align 8, !noalias !13
  %49 = icmp sgt i64 %47, %48
  br i1 %49, label %50, label %40

50:                                               ; preds = %40, %23
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %17) #2, !noalias !13
  %51 = load ptr, ptr addrspace(3) @_shared.1, align 16, !tbaa !16, !noalias !13
  %52 = load i64, ptr addrspace(3) @_shared.3, align 16, !tbaa !9, !noalias !13
  %53 = load i64, ptr addrspace(3) @_shared.2, align 16, !tbaa !9, !noalias !13
  br label %54

54:                                               ; preds = %16, %50
  %55 = phi i64 [ %53, %50 ], [ %2, %16 ]
  %56 = phi i64 [ %52, %50 ], [ %1, %16 ]
  %57 = phi ptr [ %51, %50 ], [ %3, %16 ]
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %10) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %9) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %8) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %7) #2, !noalias !13
  %58 = load i32, ptr addrspace(1) %12, align 4, !tbaa !20, !noalias !13
  %59 = shl i64 %55, 2
  %60 = mul i64 %59, %56
  call void @ompx_pipelined_put(i32 noundef %58, ptr noundef %57, ptr noundef %57, i64 noundef %60) #8, !noalias !13
  call void @llvm.lifetime.end.p5(i64 48, ptr addrspace(5) %11)
  call void @__kmpc_target_deinit() #2
  br label %15
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined(ptr noalias nocapture noundef readonly %0, ptr noalias nocapture readnone %1, i64 noundef %2, i64 noundef %3, ptr nocapture noundef nonnull readonly align 8 dereferenceable(8) %4, ptr nocapture noundef nonnull readonly align 8 dereferenceable(8) %5, ptr nocapture noundef nonnull readonly align 8 dereferenceable(8) %6, ptr nocapture noundef nonnull readonly align 4 dereferenceable(4) %7) #3 {
  %9 = alloca i64, align 8, addrspace(5)
  %10 = alloca i64, align 8, addrspace(5)
  %11 = alloca i64, align 8, addrspace(5)
  %12 = alloca i32, align 4, addrspace(5)
  %13 = load i64, ptr %4, align 8, !tbaa !9
  %14 = load i64, ptr %5, align 8, !tbaa !9
  %15 = icmp sgt i64 %13, 0
  %16 = icmp sgt i64 %14, 0
  %17 = select i1 %15, i1 %16, i1 false
  br i1 %17, label %18, label %42

18:                                               ; preds = %8
  %19 = addrspacecast ptr addrspace(5) %11 to ptr
  %20 = addrspacecast ptr addrspace(5) %12 to ptr
  %21 = addrspacecast ptr addrspace(5) %10 to ptr
  %22 = addrspacecast ptr addrspace(5) %9 to ptr
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %9) #9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %10) #9
  store i64 %2, ptr addrspace(5) %9, align 8, !tbaa !9
  store i64 %3, ptr addrspace(5) %10, align 8, !tbaa !9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %11) #9
  store i64 1, ptr addrspace(5) %11, align 8, !tbaa !9
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %12) #9
  store i32 0, ptr addrspace(5) %12, align 4, !tbaa !20
  %23 = load i32, ptr %0, align 4, !tbaa !20
  call void @__kmpc_for_static_init_8(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %23, i32 33, ptr nonnull %20, ptr nonnull %22, ptr nonnull %21, ptr nonnull %19, i64 1, i64 1) #2
  %24 = load i64, ptr addrspace(5) %9, align 8, !tbaa !9
  %25 = icmp ugt i64 %24, %3
  br i1 %25, label %41, label %26

26:                                               ; preds = %18
  %27 = load ptr, ptr %6, align 8, !tbaa !16
  %28 = load i64, ptr %5, align 8, !tbaa !9
  %29 = load i64, ptr addrspace(5) %11, align 8, !tbaa !9
  %30 = load float, ptr %7, align 4, !tbaa !18
  br label %31

31:                                               ; preds = %26, %31
  %32 = phi i64 [ %24, %26 ], [ %39, %31 ]
  %33 = sdiv i64 %32, %14
  %34 = mul nsw i64 %33, %14
  %35 = sub nsw i64 %32, %34
  %36 = mul nsw i64 %28, %33
  %37 = getelementptr float, ptr %27, i64 %36
  %38 = getelementptr float, ptr %37, i64 %35
  store float %30, ptr %38, align 4, !tbaa !18
  %39 = add nsw i64 %29, %32
  %40 = icmp ugt i64 %39, %3
  br i1 %40, label %41, label %31

41:                                               ; preds = %31, %18
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %23) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %12) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %11) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %10) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %9) #2
  br label %42

42:                                               ; preds = %41, %8
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined_wrapper(i16 zeroext %0, i32 noundef %1) #4 {
  %3 = alloca i64, align 8, addrspace(5)
  %4 = alloca i64, align 8, addrspace(5)
  %5 = alloca i64, align 8, addrspace(5)
  %6 = alloca i32, align 4, addrspace(5)
  %7 = alloca ptr, align 8, addrspace(5)
  %8 = addrspacecast ptr addrspace(5) %7 to ptr
  call void @__kmpc_get_shared_variables(ptr %8) #2
  %9 = load ptr, ptr addrspace(5) %7, align 8
  %10 = getelementptr inbounds i8, ptr %9, i64 8
  %11 = load i64, ptr %10, align 8, !tbaa !16
  %12 = getelementptr inbounds i8, ptr %9, i64 16
  %13 = load ptr, ptr %12, align 8, !tbaa !16
  %14 = getelementptr inbounds i8, ptr %9, i64 24
  %15 = load ptr, ptr %14, align 8, !tbaa !16
  %16 = getelementptr inbounds i8, ptr %9, i64 32
  %17 = load ptr, ptr %16, align 8, !tbaa !16
  %18 = getelementptr inbounds i8, ptr %9, i64 40
  %19 = load ptr, ptr %18, align 8, !tbaa !16
  %20 = load i64, ptr %13, align 8, !tbaa !9, !noalias !22
  %21 = load i64, ptr %15, align 8, !tbaa !9, !noalias !22
  %22 = icmp sgt i64 %20, 0
  %23 = icmp sgt i64 %21, 0
  %24 = select i1 %22, i1 %23, i1 false
  br i1 %24, label %25, label %49

25:                                               ; preds = %2
  %26 = load i64, ptr %9, align 8, !tbaa !16
  %27 = addrspacecast ptr addrspace(5) %5 to ptr
  %28 = addrspacecast ptr addrspace(5) %6 to ptr
  %29 = addrspacecast ptr addrspace(5) %4 to ptr
  %30 = addrspacecast ptr addrspace(5) %3 to ptr
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %3) #9, !noalias !22
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %4) #9, !noalias !22
  store i64 %26, ptr addrspace(5) %3, align 8, !tbaa !9, !noalias !22
  store i64 %11, ptr addrspace(5) %4, align 8, !tbaa !9, !noalias !22
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %5) #9, !noalias !22
  store i64 1, ptr addrspace(5) %5, align 8, !tbaa !9, !noalias !22
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %6) #9, !noalias !22
  store i32 0, ptr addrspace(5) %6, align 4, !tbaa !20, !noalias !22
  call void @__kmpc_for_static_init_8(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %1, i32 33, ptr nonnull %28, ptr nonnull %30, ptr nonnull %29, ptr nonnull %27, i64 1, i64 1) #2, !noalias !22
  %31 = load i64, ptr addrspace(5) %3, align 8, !tbaa !9, !noalias !22
  %32 = icmp ugt i64 %31, %11
  br i1 %32, label %48, label %33

33:                                               ; preds = %25
  %34 = load ptr, ptr %17, align 8, !tbaa !16, !noalias !22
  %35 = load i64, ptr %15, align 8, !tbaa !9, !noalias !22
  %36 = load i64, ptr addrspace(5) %5, align 8, !tbaa !9, !noalias !22
  %37 = load float, ptr %19, align 4, !tbaa !18, !noalias !22
  br label %38

38:                                               ; preds = %38, %33
  %39 = phi i64 [ %31, %33 ], [ %46, %38 ]
  %40 = sdiv i64 %39, %21
  %41 = mul nsw i64 %40, %21
  %42 = sub nsw i64 %39, %41
  %43 = mul nsw i64 %40, %35
  %44 = getelementptr float, ptr %34, i64 %43
  %45 = getelementptr float, ptr %44, i64 %42
  store float %37, ptr %45, align 4, !tbaa !18, !noalias !22
  %46 = add nsw i64 %39, %36
  %47 = icmp ugt i64 %46, %11
  br i1 %47, label %48, label %38

48:                                               ; preds = %38, %25
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %1) #2, !noalias !22
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %6) #2, !noalias !22
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %5) #2, !noalias !22
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %4) #2, !noalias !22
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %3) #2, !noalias !22
  br label %49

49:                                               ; preds = %2, %48
  ret void
}

declare void @__kmpc_get_shared_variables(ptr) local_unnamed_addr

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #5

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) local_unnamed_addr #6

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #7

attributes #0 = { alwaysinline convergent norecurse nounwind "amdgpu-flat-work-group-size"="1,257" "kernel" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #4 = { norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #5 = { alwaysinline }
attributes #6 = { convergent "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #7 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #8 = { convergent nounwind }
attributes #9 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!nvvm.annotations = !{!1}
!llvm.module.flags = !{!2, !3, !4, !5, !6}
!opencl.ocl.version = !{!7}
!llvm.ident = !{!8}

!0 = !{i32 0, i32 1549388176, i32 1459617801, !"_Z4stepPfPKixxf", i32 9, i32 0, i32 0}
!1 = !{ptr @__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9, !"kernel", i32 1}
!2 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{i32 2, i32 0}
!8 = !{!"AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)"}
!9 = !{!10, !10, i64 0}
!10 = !{!"long long", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14}
!14 = distinct !{!14, !15, !"__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined: argument 0"}
!15 = distinct !{!15, !"__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined"}
!16 = !{!17, !17, i64 0}
!17 = !{!"any pointer", !11, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"float", !11, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"int", !11, i64 0}
!22 = !{!23}
!23 = distinct !{!23, !24, !"__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined: argument 0"}
!24 = distinct !{!24, !"__omp_offloading_5c59c990_57000009__Z4stepPfPKixxf_l9_omp_outlined_omp_outlined"}
