; Generated by gen.sh from InputsO3/bad_inloop_conditional.cpp -- do not edit.
;
; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes='default<O3>' -disable-output %s 2>&1 | %FileCheck %s
;
; // A put in the loop's body that does not run on every iteration.
; #include <cstddef>
; typedef long long llint;
; #pragma omp declare target
; extern "C" void ompx_pipelined_put(int peer, void* dst, const void* src, size_t bytes);
; #pragma omp end declare target
;
; void step(float* a, llint n, int peer, float s) {
;     #pragma omp target teams distribute parallel for is_device_ptr(a)
;     for (llint i = 0; i < n; ++i) {
;         a[i] = s;
;         if (i == 0) ompx_pipelined_put(peer, a, a, n * sizeof(float));
;     }
; }
;
; // CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfxif_l{{[0-9]+}}
; // CHECK-NEXT: ompx_pipelined_put: ILLEGAL: the put does not run on every iteration (it is conditional)

source_filename = "InputsO3/bad_inloop_conditional.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_plugin_enable_fast_reduction = weak addrspace(1) constant i8 0
@__omp_rtl_debug_kind = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden addrspace(1) constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 1, i8 2, i32 1, i32 -1, i32 0, i32 0, i32 0, i32 0 }, ptr addrspacecast (ptr addrspace(1) @1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_dynamic_environment to ptr) }
@2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_wg_size = weak addrspace(1) constant i16 256
@__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_exec_mode = weak addrspace(1) constant i8 2
@llvm.compiler.used = appending addrspace(1) global [3 x ptr] [ptr addrspacecast (ptr addrspace(1) @__omp_plugin_enable_fast_reduction to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_wg_size to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_exec_mode to ptr)], section "llvm.metadata"
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600

; Function Attrs: alwaysinline convergent mustprogress norecurse nounwind
define weak_odr protected amdgpu_kernel void @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9(ptr noalias noundef %0, i64 noundef %1, ptr noundef %2, i64 noundef %3, i64 noundef %4) #0 {
  %6 = alloca ptr, align 8, addrspace(5)
  %7 = alloca i64, align 8, addrspace(5)
  %8 = alloca ptr, align 8, addrspace(5)
  %9 = alloca i64, align 8, addrspace(5)
  %10 = alloca i64, align 8, addrspace(5)
  %11 = alloca i64, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca i32, align 4, addrspace(5)
  %15 = alloca i32, align 4, addrspace(5)
  %16 = addrspacecast ptr addrspace(5) %6 to ptr
  %17 = addrspacecast ptr addrspace(5) %7 to ptr
  %18 = addrspacecast ptr addrspace(5) %8 to ptr
  %19 = addrspacecast ptr addrspace(5) %9 to ptr
  %20 = addrspacecast ptr addrspace(5) %10 to ptr
  %21 = addrspacecast ptr addrspace(5) %11 to ptr
  %22 = addrspacecast ptr addrspace(5) %12 to ptr
  %23 = addrspacecast ptr addrspace(5) %13 to ptr
  %24 = addrspacecast ptr addrspace(5) %14 to ptr
  %25 = addrspacecast ptr addrspace(5) %15 to ptr
  store ptr %0, ptr %16, align 8, !tbaa !9
  store i64 %1, ptr %17, align 8, !tbaa !13
  store ptr %2, ptr %18, align 8, !tbaa !9
  store i64 %3, ptr %19, align 8, !tbaa !13
  store i64 %4, ptr %20, align 8, !tbaa !13
  %26 = call i32 @__kmpc_target_init(ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_kernel_environment to ptr), ptr %0)
  %27 = icmp eq i32 %26, -1
  br i1 %27, label %28, label %37

28:                                               ; preds = %5
  %29 = call i32 @__kmpc_global_thread_num(ptr addrspacecast (ptr addrspace(1) @1 to ptr))
  %30 = load i64, ptr %17, align 8, !tbaa !15
  store i64 %30, ptr %21, align 8, !tbaa !15
  %31 = load i64, ptr %21, align 8, !tbaa !13
  %32 = load ptr, ptr %18, align 8, !tbaa !9
  %33 = load float, ptr %19, align 4, !tbaa !17
  store float %33, ptr %22, align 4, !tbaa !17
  %34 = load i64, ptr %22, align 8, !tbaa !13
  %35 = load i32, ptr %20, align 4, !tbaa !19
  store i32 %35, ptr %23, align 4, !tbaa !19
  %36 = load i64, ptr %23, align 8, !tbaa !13
  store i32 0, ptr %24, align 4
  store i32 %29, ptr %25, align 4, !tbaa !19
  call void @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_omp_outlined(ptr %25, ptr %24, i64 %31, ptr %32, i64 %34, i64 %36) #3
  call void @__kmpc_target_deinit()
  ret void

37:                                               ; preds = %5
  ret void
}

declare i32 @__kmpc_target_init(ptr, ptr)

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, ptr noundef %3, i64 noundef %4, i64 noundef %5) #1 {
  %7 = alloca ptr, align 8, addrspace(5)
  %8 = alloca ptr, align 8, addrspace(5)
  %9 = alloca i64, align 8, addrspace(5)
  %10 = alloca ptr, align 8, addrspace(5)
  %11 = alloca i64, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca i64, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca i64, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i32, align 4, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i64, align 8, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca [6 x ptr], align 8, addrspace(5)
  %27 = addrspacecast ptr addrspace(5) %7 to ptr
  %28 = addrspacecast ptr addrspace(5) %8 to ptr
  %29 = addrspacecast ptr addrspace(5) %9 to ptr
  %30 = addrspacecast ptr addrspace(5) %10 to ptr
  %31 = addrspacecast ptr addrspace(5) %11 to ptr
  %32 = addrspacecast ptr addrspace(5) %12 to ptr
  %33 = addrspacecast ptr addrspace(5) %13 to ptr
  %34 = addrspacecast ptr addrspace(5) %14 to ptr
  %35 = addrspacecast ptr addrspace(5) %15 to ptr
  %36 = addrspacecast ptr addrspace(5) %16 to ptr
  %37 = addrspacecast ptr addrspace(5) %17 to ptr
  %38 = addrspacecast ptr addrspace(5) %18 to ptr
  %39 = addrspacecast ptr addrspace(5) %19 to ptr
  %40 = addrspacecast ptr addrspace(5) %20 to ptr
  %41 = addrspacecast ptr addrspace(5) %21 to ptr
  %42 = addrspacecast ptr addrspace(5) %22 to ptr
  %43 = addrspacecast ptr addrspace(5) %23 to ptr
  %44 = addrspacecast ptr addrspace(5) %24 to ptr
  %45 = addrspacecast ptr addrspace(5) %25 to ptr
  %46 = addrspacecast ptr addrspace(5) %26 to ptr
  store ptr %0, ptr %27, align 8, !tbaa !9
  store ptr %1, ptr %28, align 8, !tbaa !9
  store i64 %2, ptr %29, align 8, !tbaa !13
  store ptr %3, ptr %30, align 8, !tbaa !9
  store i64 %4, ptr %31, align 8, !tbaa !13
  store i64 %5, ptr %32, align 8, !tbaa !13
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %13) #3
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %15) #3
  %47 = load i64, ptr %29, align 8, !tbaa !15
  store i64 %47, ptr %35, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %16) #3
  %48 = load i64, ptr %35, align 8, !tbaa !15
  %49 = sub nsw i64 %48, 0
  %50 = sdiv i64 %49, 1
  %51 = sub nsw i64 %50, 1
  store i64 %51, ptr %36, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %17) #3
  store i64 0, ptr %37, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %17) #3
  %52 = load i64, ptr %35, align 8, !tbaa !15
  %53 = icmp slt i64 0, %52
  br i1 %53, label %54, label %123

54:                                               ; preds = %6
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %18) #3
  store i64 0, ptr %38, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %19) #3
  %55 = load i64, ptr %36, align 8, !tbaa !15
  store i64 %55, ptr %39, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %20) #3
  store i64 1, ptr %40, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %21) #3
  store i32 0, ptr %41, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %22) #3
  %56 = call i32 @__kmpc_get_hardware_num_threads_in_block()
  %57 = zext i32 %56 to i64
  %58 = load ptr, ptr %27, align 8
  %59 = load i32, ptr %58, align 4, !tbaa !19
  call void @__kmpc_distribute_static_init_8(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %59, i32 91, ptr %41, ptr %38, ptr %39, ptr %40, i64 1, i64 %57)
  %60 = load i64, ptr %39, align 8, !tbaa !15
  %61 = load i64, ptr %36, align 8, !tbaa !15
  %62 = icmp sgt i64 %60, %61
  br i1 %62, label %63, label %65

63:                                               ; preds = %54
  %64 = load i64, ptr %36, align 8, !tbaa !15
  br label %67

65:                                               ; preds = %54
  %66 = load i64, ptr %39, align 8, !tbaa !15
  br label %67

67:                                               ; preds = %65, %63
  %68 = phi i64 [ %64, %63 ], [ %66, %65 ]
  store i64 %68, ptr %39, align 8, !tbaa !15
  %69 = load i64, ptr %38, align 8, !tbaa !15
  store i64 %69, ptr %33, align 8, !tbaa !15
  br label %70

70:                                               ; preds = %116, %67
  %71 = load i64, ptr %33, align 8, !tbaa !15
  %72 = load i64, ptr %36, align 8, !tbaa !15
  %73 = add nsw i64 %72, 1
  %74 = icmp slt i64 %71, %73
  br i1 %74, label %76, label %75

75:                                               ; preds = %70
  br label %119

76:                                               ; preds = %70
  %77 = load i64, ptr %38, align 8
  %78 = load i64, ptr %39, align 8
  %79 = load i64, ptr %29, align 8, !tbaa !15
  store i64 %79, ptr %43, align 8, !tbaa !15
  %80 = load i64, ptr %43, align 8, !tbaa !13
  %81 = load ptr, ptr %30, align 8, !tbaa !9
  %82 = load float, ptr %31, align 4, !tbaa !17
  store float %82, ptr %44, align 4, !tbaa !17
  %83 = load i64, ptr %44, align 8, !tbaa !13
  %84 = load i32, ptr %32, align 4, !tbaa !19
  store i32 %84, ptr %45, align 4, !tbaa !19
  %85 = load i64, ptr %45, align 8, !tbaa !13
  %86 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 0
  %87 = inttoptr i64 %77 to ptr
  store ptr %87, ptr %86, align 8, !tbaa !9
  %88 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 1
  %89 = inttoptr i64 %78 to ptr
  store ptr %89, ptr %88, align 8, !tbaa !9
  %90 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 2
  %91 = inttoptr i64 %80 to ptr
  store ptr %91, ptr %90, align 8, !tbaa !9
  %92 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 3
  store ptr %81, ptr %92, align 8, !tbaa !9
  %93 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 4
  %94 = inttoptr i64 %83 to ptr
  store ptr %94, ptr %93, align 8, !tbaa !9
  %95 = getelementptr inbounds [6 x ptr], ptr %46, i64 0, i64 5
  %96 = inttoptr i64 %85 to ptr
  store ptr %96, ptr %95, align 8, !tbaa !9
  %97 = load ptr, ptr %27, align 8
  %98 = load i32, ptr %97, align 4, !tbaa !19
  call void @__kmpc_parallel_51(ptr addrspacecast (ptr addrspace(1) @1 to ptr), i32 %98, i32 1, i32 -1, i32 -1, ptr @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_omp_outlined_omp_outlined, ptr null, ptr %46, i64 6)
  br label %99

99:                                               ; preds = %76
  %100 = load i64, ptr %33, align 8, !tbaa !15
  %101 = load i64, ptr %40, align 8, !tbaa !15
  %102 = add nsw i64 %100, %101
  store i64 %102, ptr %33, align 8, !tbaa !15
  %103 = load i64, ptr %38, align 8, !tbaa !15
  %104 = load i64, ptr %40, align 8, !tbaa !15
  %105 = add nsw i64 %103, %104
  store i64 %105, ptr %38, align 8, !tbaa !15
  %106 = load i64, ptr %39, align 8, !tbaa !15
  %107 = load i64, ptr %40, align 8, !tbaa !15
  %108 = add nsw i64 %106, %107
  store i64 %108, ptr %39, align 8, !tbaa !15
  %109 = load i64, ptr %39, align 8, !tbaa !15
  %110 = load i64, ptr %36, align 8, !tbaa !15
  %111 = icmp sgt i64 %109, %110
  br i1 %111, label %112, label %114

112:                                              ; preds = %99
  %113 = load i64, ptr %36, align 8, !tbaa !15
  br label %116

114:                                              ; preds = %99
  %115 = load i64, ptr %39, align 8, !tbaa !15
  br label %116

116:                                              ; preds = %114, %112
  %117 = phi i64 [ %113, %112 ], [ %115, %114 ]
  store i64 %117, ptr %39, align 8, !tbaa !15
  %118 = load i64, ptr %38, align 8, !tbaa !15
  store i64 %118, ptr %33, align 8, !tbaa !15
  br label %70

119:                                              ; preds = %75
  br label %120

120:                                              ; preds = %119
  %121 = load ptr, ptr %27, align 8
  %122 = load i32, ptr %121, align 4, !tbaa !19
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %122)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %22) #3
  br label %123

123:                                              ; preds = %120, %6
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %21) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %20) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %19) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %18) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %16) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %15) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %13) #3
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #2

declare i32 @__kmpc_get_hardware_num_threads_in_block()

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #3

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9_omp_outlined_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef %5, i64 noundef %6, i64 noundef %7) #1 {
  %9 = alloca ptr, align 8, addrspace(5)
  %10 = alloca ptr, align 8, addrspace(5)
  %11 = alloca i64, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca ptr, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca i64, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i64, align 8, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i64, align 8, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i32, align 4, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = addrspacecast ptr addrspace(5) %9 to ptr
  %28 = addrspacecast ptr addrspace(5) %10 to ptr
  %29 = addrspacecast ptr addrspace(5) %11 to ptr
  %30 = addrspacecast ptr addrspace(5) %12 to ptr
  %31 = addrspacecast ptr addrspace(5) %13 to ptr
  %32 = addrspacecast ptr addrspace(5) %14 to ptr
  %33 = addrspacecast ptr addrspace(5) %15 to ptr
  %34 = addrspacecast ptr addrspace(5) %16 to ptr
  %35 = addrspacecast ptr addrspace(5) %17 to ptr
  %36 = addrspacecast ptr addrspace(5) %18 to ptr
  %37 = addrspacecast ptr addrspace(5) %19 to ptr
  %38 = addrspacecast ptr addrspace(5) %20 to ptr
  %39 = addrspacecast ptr addrspace(5) %21 to ptr
  %40 = addrspacecast ptr addrspace(5) %22 to ptr
  %41 = addrspacecast ptr addrspace(5) %23 to ptr
  %42 = addrspacecast ptr addrspace(5) %24 to ptr
  %43 = addrspacecast ptr addrspace(5) %25 to ptr
  %44 = addrspacecast ptr addrspace(5) %26 to ptr
  store ptr %0, ptr %27, align 8, !tbaa !9
  store ptr %1, ptr %28, align 8, !tbaa !9
  store i64 %2, ptr %29, align 8, !tbaa !13
  store i64 %3, ptr %30, align 8, !tbaa !13
  store i64 %4, ptr %31, align 8, !tbaa !13
  store ptr %5, ptr %32, align 8, !tbaa !9
  store i64 %6, ptr %33, align 8, !tbaa !13
  store i64 %7, ptr %34, align 8, !tbaa !13
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %17) #3
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %19) #3
  %45 = load i64, ptr %31, align 8, !tbaa !15
  store i64 %45, ptr %37, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %20) #3
  %46 = load i64, ptr %37, align 8, !tbaa !15
  %47 = sub nsw i64 %46, 0
  %48 = sdiv i64 %47, 1
  %49 = sub nsw i64 %48, 1
  store i64 %49, ptr %38, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %21) #3
  store i64 0, ptr %39, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %21) #3
  %50 = load i64, ptr %37, align 8, !tbaa !15
  %51 = icmp slt i64 0, %50
  br i1 %51, label %52, label %90

52:                                               ; preds = %8
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %22) #3
  store i64 0, ptr %40, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %23) #3
  %53 = load i64, ptr %38, align 8, !tbaa !15
  store i64 %53, ptr %41, align 8, !tbaa !15
  %54 = load i64, ptr %29, align 8, !tbaa !13
  %55 = load i64, ptr %30, align 8, !tbaa !13
  store i64 %54, ptr %40, align 8, !tbaa !15
  store i64 %55, ptr %41, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %24) #3
  store i64 1, ptr %42, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %25) #3
  store i32 0, ptr %43, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %26) #3
  %56 = load ptr, ptr %27, align 8
  %57 = load i32, ptr %56, align 4, !tbaa !19
  call void @__kmpc_for_static_init_8(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %57, i32 33, ptr %43, ptr %40, ptr %41, ptr %42, i64 1, i64 1)
  %58 = load i64, ptr %40, align 8, !tbaa !15
  store i64 %58, ptr %35, align 8, !tbaa !15
  br label %59

59:                                               ; preds = %82, %52
  %60 = load i64, ptr %35, align 8, !tbaa !15
  %61 = load i64, ptr %30, align 8, !tbaa !13
  %62 = icmp ule i64 %60, %61
  br i1 %62, label %64, label %63

63:                                               ; preds = %59
  br label %86

64:                                               ; preds = %59
  %65 = load i64, ptr %35, align 8, !tbaa !15
  %66 = mul nsw i64 %65, 1
  %67 = add nsw i64 0, %66
  store i64 %67, ptr %44, align 8, !tbaa !15
  %68 = load float, ptr %33, align 4, !tbaa !17
  %69 = load ptr, ptr %32, align 8, !tbaa !9
  %70 = load i64, ptr %44, align 8, !tbaa !15
  %71 = getelementptr inbounds float, ptr %69, i64 %70
  store float %68, ptr %71, align 4, !tbaa !17
  %72 = load i64, ptr %44, align 8, !tbaa !15
  %73 = icmp eq i64 %72, 0
  br i1 %73, label %74, label %80

74:                                               ; preds = %64
  %75 = load i32, ptr %34, align 4, !tbaa !19
  %76 = load ptr, ptr %32, align 8, !tbaa !9
  %77 = load ptr, ptr %32, align 8, !tbaa !9
  %78 = load i64, ptr %31, align 8, !tbaa !15
  %79 = mul i64 %78, 4
  call void @ompx_pipelined_put(i32 noundef %75, ptr noundef %76, ptr noundef %77, i64 noundef %79) #6
  br label %80

80:                                               ; preds = %74, %64
  br label %81

81:                                               ; preds = %80
  br label %82

82:                                               ; preds = %81
  %83 = load i64, ptr %35, align 8, !tbaa !15
  %84 = load i64, ptr %42, align 8, !tbaa !15
  %85 = add nsw i64 %83, %84
  store i64 %85, ptr %35, align 8, !tbaa !15
  br label %59

86:                                               ; preds = %63
  br label %87

87:                                               ; preds = %86
  %88 = load ptr, ptr %27, align 8
  %89 = load i32, ptr %88, align 4, !tbaa !19
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %89)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %26) #3
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %25) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %24) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %23) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %22) #3
  br label %90

90:                                               ; preds = %87, %8
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %20) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %19) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %17) #3
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #3

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) #4

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) #3

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) #5

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) #3

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) #3

declare void @__kmpc_target_deinit()

attributes #0 = { alwaysinline convergent mustprogress norecurse nounwind "amdgpu-flat-work-group-size"="1,256" "kernel" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { alwaysinline convergent norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nounwind }
attributes #4 = { convergent "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #5 = { alwaysinline }
attributes #6 = { convergent }

!omp_offload.info = !{!0}
!nvvm.annotations = !{!1}
!llvm.module.flags = !{!2, !3, !4, !5, !6}
!llvm.ident = !{!7, !7, !7, !7, !7, !7, !7, !7, !7}
!opencl.ocl.version = !{!8, !8, !8, !8, !8, !8, !8, !8}

!0 = !{i32 0, i32 1549388176, i32 1459618484, !"_Z4stepPfxif", i32 9, i32 0, i32 0}
!1 = !{ptr @__omp_offloading_5c59c990_570002b4__Z4stepPfxif_l9, !"kernel", i32 1}
!2 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{!"AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)"}
!8 = !{i32 2, i32 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14, !14, i64 0}
!14 = !{!"long", !11, i64 0}
!15 = !{!16, !16, i64 0}
!16 = !{!"long long", !11, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"float", !11, i64 0}
!19 = !{!20, !20, i64 0}
!20 = !{!"int", !11, i64 0}
