#!/usr/bin/env bash
# Regenerate the box-form pipelined-put lit tests from Inputs/*.cpp.
#
# Each Inputs/<case>.cpp is compiled to AMDGPU OpenMP device IR and carries
# its own CHECK lines; <case>.ll is the RUN lines, the source as comments
# and the IR. The IR comes from LLVM 19 (ROCm 6.4 on Tioga), which LLVM 21
# also reads, so the tests run against a plugin built for either.
#
# Usage: LLVM=<llvm prefix with AMDGPU offload> ./gen.sh
set -euo pipefail
cd "$(dirname "$0")"
LLVM=${LLVM:-/opt/rocm-6.4.0/lib/llvm}

RUN='; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-chunk-analysis -disable-output %s 2>&1 | %FileCheck %s'

device_ir() {   # source, extra clang flags
    "$LLVM/bin/clang++" -fopenmp --offload-arch=gfx90a --offload-device-only \
        -S -emit-llvm $2 "$1" -o - | grep -v '^; ModuleID'
}

for src in Inputs/*.cpp; do
    name=$(basename "$src" .cpp)
    {
        echo "; Generated by gen.sh from Inputs/$name.cpp -- do not edit."
        echo ";"
        echo "$RUN"
        echo ";"
        sed 's/^/; /; s/ *$//' "$src"
        echo
        device_ir "$src" -O2
    } > "$name.ll"
done

# The whole -O3 pipeline from unoptimized IR: the prep pass keeps the
# region outlined, the put is lowered to the box element grain, and the
# put_no_db mirror leaves the repeated store alone.
{
    echo "; Generated by gen.sh: Inputs/legal_face3d.cpp before any optimization,"
    echo "; lowered through default<O3> -- do not edit."
    echo ";"
    echo "; RUN: env GICC_MODE=chunk-lower %opt -load-pass-plugin=%gicc_passes_so \\"
    echo "; RUN:   -passes='default<O3>' -S %s 2>&1 | %FileCheck %s"
    echo ";"
    cat <<'CHECKS'
; CHECK: lowered: element grain over the box
; The kernel resolves the peer, sends the unwritten part of the range, and
; hands the range and the peer offset to the region.
; CHECK-LABEL: define {{.*}} @__omp_offloading_
; CHECK: [[PD:%.*]] = call ptr @ompx__peer_addr_mapped(i32 {{%.*}}, ptr {{%.*}})
; CHECK: call void @ompx__box_residual(ptr [[PD]], ptr {{%.*}}, i64 {{%.*}}, ptr {{%.*}}, i32 3, ptr {{%.*}}, ptr {{%.*}}, i64 4, i32 {{%.*}})
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.delta
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.start
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.len
; CHECK: call void @__kmpc_distribute_static_init
; CHECK-NOT: ompx_pipelined_put
; A store in the range is repeated at the peer offset.
; CHECK-LABEL: define internal void @__omp_offloading_{{.*}}_omp_outlined_omp_outlined(
; CHECK: [[DELTA:%.*]] = load i64, ptr addrspace(3) @gicc.box.delta
; The put_no_db mirror checks the original store first; then the box check.
; CHECK: store float [[V:%[0-9]+]], ptr [[P:%[0-9]+]], align 4, !tbaa
; CHECK: %gicc.box.in = and i1
; CHECK-NEXT: br i1 %gicc.box.in
; CHECK: [[R:%.*]] = getelementptr i8, ptr [[P]], i64 [[DELTA]]
; CHECK-NEXT: store float [[V]], ptr [[R]], align 4, !gicc.repeat
; CHECK-NOT: gicc-chunk-noinline
CHECKS
    echo
    device_ir Inputs/legal_face3d.cpp "-O3 -Xclang -disable-llvm-passes"
} > lower_face3d.ll
