; Generated by gen.sh from InputsO3/legal_inloop_1d.cpp -- do not edit.
;
; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes='default<O3>' -disable-output %s 2>&1 | %FileCheck %s
;
; // A 1-D loop with the put in its body takes the box form too.
; #include <cstddef>
; typedef long long llint;
; #pragma omp declare target
; extern "C" void ompx_pipelined_put(int peer, void* dst, const void* src, size_t bytes);
; #pragma omp end declare target
;
; void step(float* src, float* dst, llint n, int peer, float s) {
;     #pragma omp target teams distribute parallel for is_device_ptr(src, dst)
;     for (llint i = 0; i < n; ++i) {
;         src[i] = s * (float)i;
;         ompx_pipelined_put(peer, dst, src, n * sizeof(float));
;     }
; }
;
; // CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfS_xif_l{{[0-9]+}}
; // CHECK-NEXT: ompx_pipelined_put: LEGAL
; // CHECK-NEXT: box: 1-D extent=[%1] stride=[4] offset=0
; // CHECK-NEXT: range: [arg#2 + 0, + (4 * %1)): stores inside it are mirrored, the rest is sent at kernel start

source_filename = "InputsO3/legal_inloop_1d.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_plugin_enable_fast_reduction = weak addrspace(1) constant i8 0
@__omp_rtl_debug_kind = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden addrspace(1) constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 1, i8 2, i32 1, i32 -1, i32 0, i32 0, i32 0, i32 0 }, ptr addrspacecast (ptr addrspace(1) @1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_dynamic_environment to ptr) }
@2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_wg_size = weak addrspace(1) constant i16 256
@__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_exec_mode = weak addrspace(1) constant i8 2
@llvm.compiler.used = appending addrspace(1) global [3 x ptr] [ptr addrspacecast (ptr addrspace(1) @__omp_plugin_enable_fast_reduction to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_wg_size to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_exec_mode to ptr)], section "llvm.metadata"
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600

; Function Attrs: alwaysinline convergent mustprogress norecurse nounwind
define weak_odr protected amdgpu_kernel void @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9(ptr noalias noundef %0, i64 noundef %1, ptr noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef %5) #0 {
  %7 = alloca ptr, align 8, addrspace(5)
  %8 = alloca i64, align 8, addrspace(5)
  %9 = alloca ptr, align 8, addrspace(5)
  %10 = alloca i64, align 8, addrspace(5)
  %11 = alloca i64, align 8, addrspace(5)
  %12 = alloca ptr, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca i64, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i32, align 4, addrspace(5)
  %17 = alloca i32, align 4, addrspace(5)
  %18 = addrspacecast ptr addrspace(5) %7 to ptr
  %19 = addrspacecast ptr addrspace(5) %8 to ptr
  %20 = addrspacecast ptr addrspace(5) %9 to ptr
  %21 = addrspacecast ptr addrspace(5) %10 to ptr
  %22 = addrspacecast ptr addrspace(5) %11 to ptr
  %23 = addrspacecast ptr addrspace(5) %12 to ptr
  %24 = addrspacecast ptr addrspace(5) %13 to ptr
  %25 = addrspacecast ptr addrspace(5) %14 to ptr
  %26 = addrspacecast ptr addrspace(5) %15 to ptr
  %27 = addrspacecast ptr addrspace(5) %16 to ptr
  %28 = addrspacecast ptr addrspace(5) %17 to ptr
  store ptr %0, ptr %18, align 8, !tbaa !9
  store i64 %1, ptr %19, align 8, !tbaa !13
  store ptr %2, ptr %20, align 8, !tbaa !9
  store i64 %3, ptr %21, align 8, !tbaa !13
  store i64 %4, ptr %22, align 8, !tbaa !13
  store ptr %5, ptr %23, align 8, !tbaa !9
  %29 = call i32 @__kmpc_target_init(ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_kernel_environment to ptr), ptr %0)
  %30 = icmp eq i32 %29, -1
  br i1 %30, label %31, label %41

31:                                               ; preds = %6
  %32 = call i32 @__kmpc_global_thread_num(ptr addrspacecast (ptr addrspace(1) @1 to ptr))
  %33 = load i64, ptr %19, align 8, !tbaa !15
  store i64 %33, ptr %24, align 8, !tbaa !15
  %34 = load i64, ptr %24, align 8, !tbaa !13
  %35 = load ptr, ptr %20, align 8, !tbaa !9
  %36 = load float, ptr %21, align 4, !tbaa !17
  store float %36, ptr %25, align 4, !tbaa !17
  %37 = load i64, ptr %25, align 8, !tbaa !13
  %38 = load i32, ptr %22, align 4, !tbaa !19
  store i32 %38, ptr %26, align 4, !tbaa !19
  %39 = load i64, ptr %26, align 8, !tbaa !13
  %40 = load ptr, ptr %23, align 8, !tbaa !9
  store i32 0, ptr %27, align 4
  store i32 %32, ptr %28, align 4, !tbaa !19
  call void @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_omp_outlined(ptr %28, ptr %27, i64 %34, ptr %35, i64 %37, i64 %39, ptr %40) #3
  call void @__kmpc_target_deinit()
  ret void

41:                                               ; preds = %6
  ret void
}

declare i32 @__kmpc_target_init(ptr, ptr)

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, ptr noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef %6) #1 {
  %8 = alloca ptr, align 8, addrspace(5)
  %9 = alloca ptr, align 8, addrspace(5)
  %10 = alloca i64, align 8, addrspace(5)
  %11 = alloca ptr, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca ptr, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca i64, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i64, align 8, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i32, align 4, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = alloca i64, align 8, addrspace(5)
  %28 = alloca [7 x ptr], align 8, addrspace(5)
  %29 = addrspacecast ptr addrspace(5) %8 to ptr
  %30 = addrspacecast ptr addrspace(5) %9 to ptr
  %31 = addrspacecast ptr addrspace(5) %10 to ptr
  %32 = addrspacecast ptr addrspace(5) %11 to ptr
  %33 = addrspacecast ptr addrspace(5) %12 to ptr
  %34 = addrspacecast ptr addrspace(5) %13 to ptr
  %35 = addrspacecast ptr addrspace(5) %14 to ptr
  %36 = addrspacecast ptr addrspace(5) %15 to ptr
  %37 = addrspacecast ptr addrspace(5) %16 to ptr
  %38 = addrspacecast ptr addrspace(5) %17 to ptr
  %39 = addrspacecast ptr addrspace(5) %18 to ptr
  %40 = addrspacecast ptr addrspace(5) %19 to ptr
  %41 = addrspacecast ptr addrspace(5) %20 to ptr
  %42 = addrspacecast ptr addrspace(5) %21 to ptr
  %43 = addrspacecast ptr addrspace(5) %22 to ptr
  %44 = addrspacecast ptr addrspace(5) %23 to ptr
  %45 = addrspacecast ptr addrspace(5) %24 to ptr
  %46 = addrspacecast ptr addrspace(5) %25 to ptr
  %47 = addrspacecast ptr addrspace(5) %26 to ptr
  %48 = addrspacecast ptr addrspace(5) %27 to ptr
  %49 = addrspacecast ptr addrspace(5) %28 to ptr
  store ptr %0, ptr %29, align 8, !tbaa !9
  store ptr %1, ptr %30, align 8, !tbaa !9
  store i64 %2, ptr %31, align 8, !tbaa !13
  store ptr %3, ptr %32, align 8, !tbaa !9
  store i64 %4, ptr %33, align 8, !tbaa !13
  store i64 %5, ptr %34, align 8, !tbaa !13
  store ptr %6, ptr %35, align 8, !tbaa !9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %15) #3
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %17) #3
  %50 = load i64, ptr %31, align 8, !tbaa !15
  store i64 %50, ptr %38, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %18) #3
  %51 = load i64, ptr %38, align 8, !tbaa !15
  %52 = sub nsw i64 %51, 0
  %53 = sdiv i64 %52, 1
  %54 = sub nsw i64 %53, 1
  store i64 %54, ptr %39, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %19) #3
  store i64 0, ptr %40, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %19) #3
  %55 = load i64, ptr %38, align 8, !tbaa !15
  %56 = icmp slt i64 0, %55
  br i1 %56, label %57, label %128

57:                                               ; preds = %7
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %20) #3
  store i64 0, ptr %41, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %21) #3
  %58 = load i64, ptr %39, align 8, !tbaa !15
  store i64 %58, ptr %42, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %22) #3
  store i64 1, ptr %43, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %23) #3
  store i32 0, ptr %44, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %24) #3
  %59 = call i32 @__kmpc_get_hardware_num_threads_in_block()
  %60 = zext i32 %59 to i64
  %61 = load ptr, ptr %29, align 8
  %62 = load i32, ptr %61, align 4, !tbaa !19
  call void @__kmpc_distribute_static_init_8(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %62, i32 91, ptr %44, ptr %41, ptr %42, ptr %43, i64 1, i64 %60)
  %63 = load i64, ptr %42, align 8, !tbaa !15
  %64 = load i64, ptr %39, align 8, !tbaa !15
  %65 = icmp sgt i64 %63, %64
  br i1 %65, label %66, label %68

66:                                               ; preds = %57
  %67 = load i64, ptr %39, align 8, !tbaa !15
  br label %70

68:                                               ; preds = %57
  %69 = load i64, ptr %42, align 8, !tbaa !15
  br label %70

70:                                               ; preds = %68, %66
  %71 = phi i64 [ %67, %66 ], [ %69, %68 ]
  store i64 %71, ptr %42, align 8, !tbaa !15
  %72 = load i64, ptr %41, align 8, !tbaa !15
  store i64 %72, ptr %36, align 8, !tbaa !15
  br label %73

73:                                               ; preds = %121, %70
  %74 = load i64, ptr %36, align 8, !tbaa !15
  %75 = load i64, ptr %39, align 8, !tbaa !15
  %76 = add nsw i64 %75, 1
  %77 = icmp slt i64 %74, %76
  br i1 %77, label %79, label %78

78:                                               ; preds = %73
  br label %124

79:                                               ; preds = %73
  %80 = load i64, ptr %41, align 8
  %81 = load i64, ptr %42, align 8
  %82 = load i64, ptr %31, align 8, !tbaa !15
  store i64 %82, ptr %46, align 8, !tbaa !15
  %83 = load i64, ptr %46, align 8, !tbaa !13
  %84 = load ptr, ptr %32, align 8, !tbaa !9
  %85 = load float, ptr %33, align 4, !tbaa !17
  store float %85, ptr %47, align 4, !tbaa !17
  %86 = load i64, ptr %47, align 8, !tbaa !13
  %87 = load i32, ptr %34, align 4, !tbaa !19
  store i32 %87, ptr %48, align 4, !tbaa !19
  %88 = load i64, ptr %48, align 8, !tbaa !13
  %89 = load ptr, ptr %35, align 8, !tbaa !9
  %90 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 0
  %91 = inttoptr i64 %80 to ptr
  store ptr %91, ptr %90, align 8, !tbaa !9
  %92 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 1
  %93 = inttoptr i64 %81 to ptr
  store ptr %93, ptr %92, align 8, !tbaa !9
  %94 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 2
  %95 = inttoptr i64 %83 to ptr
  store ptr %95, ptr %94, align 8, !tbaa !9
  %96 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 3
  store ptr %84, ptr %96, align 8, !tbaa !9
  %97 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 4
  %98 = inttoptr i64 %86 to ptr
  store ptr %98, ptr %97, align 8, !tbaa !9
  %99 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 5
  %100 = inttoptr i64 %88 to ptr
  store ptr %100, ptr %99, align 8, !tbaa !9
  %101 = getelementptr inbounds [7 x ptr], ptr %49, i64 0, i64 6
  store ptr %89, ptr %101, align 8, !tbaa !9
  %102 = load ptr, ptr %29, align 8
  %103 = load i32, ptr %102, align 4, !tbaa !19
  call void @__kmpc_parallel_51(ptr addrspacecast (ptr addrspace(1) @1 to ptr), i32 %103, i32 1, i32 -1, i32 -1, ptr @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_omp_outlined_omp_outlined, ptr null, ptr %49, i64 7)
  br label %104

104:                                              ; preds = %79
  %105 = load i64, ptr %36, align 8, !tbaa !15
  %106 = load i64, ptr %43, align 8, !tbaa !15
  %107 = add nsw i64 %105, %106
  store i64 %107, ptr %36, align 8, !tbaa !15
  %108 = load i64, ptr %41, align 8, !tbaa !15
  %109 = load i64, ptr %43, align 8, !tbaa !15
  %110 = add nsw i64 %108, %109
  store i64 %110, ptr %41, align 8, !tbaa !15
  %111 = load i64, ptr %42, align 8, !tbaa !15
  %112 = load i64, ptr %43, align 8, !tbaa !15
  %113 = add nsw i64 %111, %112
  store i64 %113, ptr %42, align 8, !tbaa !15
  %114 = load i64, ptr %42, align 8, !tbaa !15
  %115 = load i64, ptr %39, align 8, !tbaa !15
  %116 = icmp sgt i64 %114, %115
  br i1 %116, label %117, label %119

117:                                              ; preds = %104
  %118 = load i64, ptr %39, align 8, !tbaa !15
  br label %121

119:                                              ; preds = %104
  %120 = load i64, ptr %42, align 8, !tbaa !15
  br label %121

121:                                              ; preds = %119, %117
  %122 = phi i64 [ %118, %117 ], [ %120, %119 ]
  store i64 %122, ptr %42, align 8, !tbaa !15
  %123 = load i64, ptr %41, align 8, !tbaa !15
  store i64 %123, ptr %36, align 8, !tbaa !15
  br label %73

124:                                              ; preds = %78
  br label %125

125:                                              ; preds = %124
  %126 = load ptr, ptr %29, align 8
  %127 = load i32, ptr %126, align 4, !tbaa !19
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %127)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %24) #3
  br label %128

128:                                              ; preds = %125, %7
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %23) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %22) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %21) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %20) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %18) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %17) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %15) #3
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #2

declare i32 @__kmpc_get_hardware_num_threads_in_block()

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #3

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9_omp_outlined_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef %5, i64 noundef %6, i64 noundef %7, ptr noundef %8) #1 {
  %10 = alloca ptr, align 8, addrspace(5)
  %11 = alloca ptr, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca i64, align 8, addrspace(5)
  %15 = alloca ptr, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca ptr, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i64, align 8, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i64, align 8, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = alloca i32, align 4, addrspace(5)
  %28 = alloca i64, align 8, addrspace(5)
  %29 = addrspacecast ptr addrspace(5) %10 to ptr
  %30 = addrspacecast ptr addrspace(5) %11 to ptr
  %31 = addrspacecast ptr addrspace(5) %12 to ptr
  %32 = addrspacecast ptr addrspace(5) %13 to ptr
  %33 = addrspacecast ptr addrspace(5) %14 to ptr
  %34 = addrspacecast ptr addrspace(5) %15 to ptr
  %35 = addrspacecast ptr addrspace(5) %16 to ptr
  %36 = addrspacecast ptr addrspace(5) %17 to ptr
  %37 = addrspacecast ptr addrspace(5) %18 to ptr
  %38 = addrspacecast ptr addrspace(5) %19 to ptr
  %39 = addrspacecast ptr addrspace(5) %20 to ptr
  %40 = addrspacecast ptr addrspace(5) %21 to ptr
  %41 = addrspacecast ptr addrspace(5) %22 to ptr
  %42 = addrspacecast ptr addrspace(5) %23 to ptr
  %43 = addrspacecast ptr addrspace(5) %24 to ptr
  %44 = addrspacecast ptr addrspace(5) %25 to ptr
  %45 = addrspacecast ptr addrspace(5) %26 to ptr
  %46 = addrspacecast ptr addrspace(5) %27 to ptr
  %47 = addrspacecast ptr addrspace(5) %28 to ptr
  store ptr %0, ptr %29, align 8, !tbaa !9
  store ptr %1, ptr %30, align 8, !tbaa !9
  store i64 %2, ptr %31, align 8, !tbaa !13
  store i64 %3, ptr %32, align 8, !tbaa !13
  store i64 %4, ptr %33, align 8, !tbaa !13
  store ptr %5, ptr %34, align 8, !tbaa !9
  store i64 %6, ptr %35, align 8, !tbaa !13
  store i64 %7, ptr %36, align 8, !tbaa !13
  store ptr %8, ptr %37, align 8, !tbaa !9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %19) #3
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %21) #3
  %48 = load i64, ptr %33, align 8, !tbaa !15
  store i64 %48, ptr %40, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %22) #3
  %49 = load i64, ptr %40, align 8, !tbaa !15
  %50 = sub nsw i64 %49, 0
  %51 = sdiv i64 %50, 1
  %52 = sub nsw i64 %51, 1
  store i64 %52, ptr %41, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %23) #3
  store i64 0, ptr %42, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %23) #3
  %53 = load i64, ptr %40, align 8, !tbaa !15
  %54 = icmp slt i64 0, %53
  br i1 %54, label %55, label %92

55:                                               ; preds = %9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %24) #3
  store i64 0, ptr %43, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %25) #3
  %56 = load i64, ptr %41, align 8, !tbaa !15
  store i64 %56, ptr %44, align 8, !tbaa !15
  %57 = load i64, ptr %31, align 8, !tbaa !13
  %58 = load i64, ptr %32, align 8, !tbaa !13
  store i64 %57, ptr %43, align 8, !tbaa !15
  store i64 %58, ptr %44, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %26) #3
  store i64 1, ptr %45, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %27) #3
  store i32 0, ptr %46, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %28) #3
  %59 = load ptr, ptr %29, align 8
  %60 = load i32, ptr %59, align 4, !tbaa !19
  call void @__kmpc_for_static_init_8(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %60, i32 33, ptr %46, ptr %43, ptr %44, ptr %45, i64 1, i64 1)
  %61 = load i64, ptr %43, align 8, !tbaa !15
  store i64 %61, ptr %38, align 8, !tbaa !15
  br label %62

62:                                               ; preds = %84, %55
  %63 = load i64, ptr %38, align 8, !tbaa !15
  %64 = load i64, ptr %32, align 8, !tbaa !13
  %65 = icmp ule i64 %63, %64
  br i1 %65, label %67, label %66

66:                                               ; preds = %62
  br label %88

67:                                               ; preds = %62
  %68 = load i64, ptr %38, align 8, !tbaa !15
  %69 = mul nsw i64 %68, 1
  %70 = add nsw i64 0, %69
  store i64 %70, ptr %47, align 8, !tbaa !15
  %71 = load float, ptr %35, align 4, !tbaa !17
  %72 = load i64, ptr %47, align 8, !tbaa !15
  %73 = sitofp i64 %72 to float
  %74 = fmul float %71, %73
  %75 = load ptr, ptr %34, align 8, !tbaa !9
  %76 = load i64, ptr %47, align 8, !tbaa !15
  %77 = getelementptr inbounds float, ptr %75, i64 %76
  store float %74, ptr %77, align 4, !tbaa !17
  %78 = load i32, ptr %36, align 4, !tbaa !19
  %79 = load ptr, ptr %37, align 8, !tbaa !9
  %80 = load ptr, ptr %34, align 8, !tbaa !9
  %81 = load i64, ptr %33, align 8, !tbaa !15
  %82 = mul i64 %81, 4
  call void @ompx_pipelined_put(i32 noundef %78, ptr noundef %79, ptr noundef %80, i64 noundef %82) #6
  br label %83

83:                                               ; preds = %67
  br label %84

84:                                               ; preds = %83
  %85 = load i64, ptr %38, align 8, !tbaa !15
  %86 = load i64, ptr %45, align 8, !tbaa !15
  %87 = add nsw i64 %85, %86
  store i64 %87, ptr %38, align 8, !tbaa !15
  br label %62

88:                                               ; preds = %66
  br label %89

89:                                               ; preds = %88
  %90 = load ptr, ptr %29, align 8
  %91 = load i32, ptr %90, align 4, !tbaa !19
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %91)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %28) #3
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %27) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %26) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %25) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %24) #3
  br label %92

92:                                               ; preds = %89, %9
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %22) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %21) #3
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %19) #3
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #3

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) #4

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) #3

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) #5

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) #3

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) #3

declare void @__kmpc_target_deinit()

attributes #0 = { alwaysinline convergent mustprogress norecurse nounwind "amdgpu-flat-work-group-size"="1,256" "kernel" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { alwaysinline convergent norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nounwind }
attributes #4 = { convergent "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #5 = { alwaysinline }
attributes #6 = { convergent }

!omp_offload.info = !{!0}
!nvvm.annotations = !{!1}
!llvm.module.flags = !{!2, !3, !4, !5, !6}
!llvm.ident = !{!7, !7, !7, !7, !7, !7, !7, !7, !7}
!opencl.ocl.version = !{!8, !8, !8, !8, !8, !8, !8, !8}

!0 = !{i32 0, i32 1549388176, i32 1459618483, !"_Z4stepPfS_xif", i32 9, i32 0, i32 0}
!1 = !{ptr @__omp_offloading_5c59c990_570002b3__Z4stepPfS_xif_l9, !"kernel", i32 1}
!2 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{!"AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)"}
!8 = !{i32 2, i32 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14, !14, i64 0}
!14 = !{!"long", !11, i64 0}
!15 = !{!16, !16, i64 0}
!16 = !{!"long long", !11, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"float", !11, i64 0}
!19 = !{!20, !20, i64 0}
!20 = !{!"int", !11, i64 0}
