; Generated by gen.sh from Inputs/legal_const_trip_1d.cpp -- do not edit.
;
; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-chunk-analysis -disable-output %s 2>&1 | %FileCheck %s
;
; // A 1-D loop with a constant trip count: the distribute fini and the put
; // share a block, which the put is still after.
; #include <cstddef>
; typedef long long llint;
; #pragma omp declare target
; extern "C" void ompx_pipelined_put(int peer, void* dst, const void* src, size_t bytes);
; extern "C" int omp_get_team_num();
; #pragma omp end declare target
;
; void step(float* src, float* dst, int peer, float s) {
;     #pragma omp target teams is_device_ptr(src, dst) firstprivate(peer, s)
;     {
;         #pragma omp distribute parallel for
;         for (int i = 0; i < 4096; ++i) src[i] = s * (float)i;
;         ompx_pipelined_put(peer, dst, src, 4096 * sizeof(float));
;     }
; }
;
; // CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfS_if_l{{[0-9]+}}
; // CHECK-NEXT: ompx_pipelined_put: LEGAL
; // CHECK-NEXT: blocks: distribute sched=92 over [0, 4095]

source_filename = "Inputs/legal_const_trip_1d.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_plugin_enable_fast_reduction = weak addrspace(1) constant i8 0
@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 0, i8 1, i32 1, i32 257, i32 0, i32 0, i32 0, i32 0 }, ptr addrspacecast (ptr addrspace(1) @1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_dynamic_environment to ptr) }
@2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_wg_size = weak addrspace(1) constant i16 257
@__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_exec_mode = weak addrspace(1) constant i8 1
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600
@_shared = internal addrspace(3) global [4 x i8] poison, align 16
@_shared.1 = internal addrspace(3) global [8 x i8] poison, align 16
@llvm.compiler.used = appending addrspace(1) global [3 x ptr] [ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_exec_mode to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_wg_size to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_plugin_enable_fast_reduction to ptr)], section "llvm.metadata"

; Function Attrs: alwaysinline convergent norecurse nounwind
define weak_odr protected amdgpu_kernel void @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11(ptr noalias noundef %0, ptr noundef %1, i64 noundef %2, i64 noundef %3, ptr noundef %4) local_unnamed_addr #0 {
  %6 = alloca i32, align 4, addrspace(5)
  %7 = alloca i32, align 4, addrspace(5)
  %8 = alloca i32, align 4, addrspace(5)
  %9 = alloca i32, align 4, addrspace(5)
  %10 = alloca [4 x ptr], align 8, addrspace(5)
  %11 = tail call i32 @__kmpc_target_init(ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_kernel_environment to ptr), ptr %0) #2
  %12 = icmp eq i32 %11, -1
  br i1 %12, label %14, label %13

13:                                               ; preds = %5, %42
  ret void

14:                                               ; preds = %5
  %15 = tail call i32 @__kmpc_global_thread_num(ptr addrspacecast (ptr addrspace(1) @1 to ptr)) #2
  call void @llvm.lifetime.start.p5(i64 32, ptr addrspace(5) %10)
  %16 = addrspacecast ptr addrspace(5) %6 to ptr
  %17 = addrspacecast ptr addrspace(5) %7 to ptr
  %18 = addrspacecast ptr addrspace(5) %8 to ptr
  %19 = addrspacecast ptr addrspace(5) %9 to ptr
  %20 = addrspacecast ptr addrspace(5) %10 to ptr
  %21 = trunc i64 %2 to i32
  store ptr %1, ptr addrspace(3) @_shared.1, align 16, !tbaa !9, !noalias !13
  store i32 %21, ptr addrspace(3) @_shared, align 16, !tbaa !16, !noalias !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %6) #2, !noalias !13
  store i32 0, ptr addrspace(5) %6, align 4, !tbaa !18, !noalias !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %7) #2, !noalias !13
  store i32 4095, ptr addrspace(5) %7, align 4, !tbaa !18, !noalias !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %8) #2, !noalias !13
  store i32 1, ptr addrspace(5) %8, align 4, !tbaa !18, !noalias !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %9) #2, !noalias !13
  store i32 0, ptr addrspace(5) %9, align 4, !tbaa !18, !noalias !13
  call void @__kmpc_distribute_static_init_4(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %15, i32 92, ptr nonnull %19, ptr nonnull %16, ptr nonnull %17, ptr nonnull %18, i32 1, i32 1) #2, !noalias !13
  %22 = load i32, ptr addrspace(5) %7, align 4, !noalias !13
  %23 = call i32 @llvm.smin.i32(i32 %22, i32 4095)
  store i32 %23, ptr addrspace(5) %7, align 4, !tbaa !18, !noalias !13
  %24 = load i32, ptr addrspace(5) %6, align 4, !tbaa !18, !noalias !13
  %25 = icmp sgt i32 %24, %23
  br i1 %25, label %42, label %26

26:                                               ; preds = %14
  %27 = getelementptr inbounds i8, ptr addrspace(5) %10, i32 8
  %28 = getelementptr inbounds i8, ptr addrspace(5) %10, i32 16
  %29 = getelementptr inbounds i8, ptr addrspace(5) %10, i32 24
  br label %30

30:                                               ; preds = %30, %26
  %31 = phi i32 [ %23, %26 ], [ %40, %30 ]
  %32 = phi i32 [ %24, %26 ], [ %39, %30 ]
  %33 = load i32, ptr addrspace(5) %6, align 4, !noalias !13
  %34 = zext i32 %33 to i64
  %35 = zext i32 %31 to i64
  %36 = inttoptr i64 %34 to ptr
  store ptr %36, ptr addrspace(5) %10, align 8, !tbaa !9, !noalias !13
  %37 = inttoptr i64 %35 to ptr
  store ptr %37, ptr addrspace(5) %27, align 8, !tbaa !9, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared.1 to ptr), ptr addrspace(5) %28, align 8, !tbaa !9, !noalias !13
  store ptr addrspacecast (ptr addrspace(3) @_shared to ptr), ptr addrspace(5) %29, align 8, !tbaa !9, !noalias !13
  call void @__kmpc_parallel_51(ptr addrspacecast (ptr addrspace(1) @1 to ptr), i32 %15, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined, ptr nonnull @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined_wrapper, ptr nonnull %20, i64 4) #2, !noalias !13
  %38 = load i32, ptr addrspace(5) %8, align 4, !tbaa !18, !noalias !13
  %39 = add nsw i32 %38, %32
  %40 = load i32, ptr addrspace(5) %7, align 4, !noalias !13
  %41 = icmp sgt i32 %39, %40
  br i1 %41, label %42, label %30

42:                                               ; preds = %30, %14
  %43 = trunc i64 %3 to i32
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %15) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %9) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %8) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %7) #2, !noalias !13
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %6) #2, !noalias !13
  %44 = load ptr, ptr addrspace(3) @_shared.1, align 16, !tbaa !9, !noalias !13
  call void @ompx_pipelined_put(i32 noundef %43, ptr noundef %4, ptr noundef %44, i64 noundef 16384) #8, !noalias !13
  call void @llvm.lifetime.end.p5(i64 32, ptr addrspace(5) %10)
  call void @__kmpc_target_deinit() #2
  br label %13
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined(ptr noalias nocapture noundef readonly %0, ptr noalias nocapture readnone %1, i64 noundef %2, i64 noundef %3, ptr nocapture noundef nonnull readonly align 8 dereferenceable(8) %4, ptr nocapture noundef nonnull readonly align 4 dereferenceable(4) %5) #3 {
  %7 = alloca i32, align 4, addrspace(5)
  %8 = alloca i32, align 4, addrspace(5)
  %9 = alloca i32, align 4, addrspace(5)
  %10 = alloca i32, align 4, addrspace(5)
  %11 = addrspacecast ptr addrspace(5) %7 to ptr
  %12 = addrspacecast ptr addrspace(5) %8 to ptr
  %13 = addrspacecast ptr addrspace(5) %9 to ptr
  %14 = addrspacecast ptr addrspace(5) %10 to ptr
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %7) #9
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %8) #9
  %15 = trunc i64 %2 to i32
  %16 = trunc i64 %3 to i32
  store i32 %15, ptr addrspace(5) %7, align 4, !tbaa !18
  store i32 %16, ptr addrspace(5) %8, align 4, !tbaa !18
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %9) #9
  store i32 1, ptr addrspace(5) %9, align 4, !tbaa !18
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %10) #9
  store i32 0, ptr addrspace(5) %10, align 4, !tbaa !18
  %17 = load i32, ptr %0, align 4, !tbaa !18
  call void @__kmpc_for_static_init_4(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %17, i32 33, ptr nonnull %14, ptr nonnull %11, ptr nonnull %12, ptr nonnull %13, i32 1, i32 1) #2
  %18 = load i32, ptr addrspace(5) %7, align 4, !tbaa !18
  %19 = sext i32 %18 to i64
  %20 = icmp ugt i64 %19, %3
  br i1 %20, label %34, label %21

21:                                               ; preds = %6
  %22 = load ptr, ptr %4, align 8, !tbaa !9
  %23 = load i32, ptr addrspace(5) %9, align 4, !tbaa !18
  br label %24

24:                                               ; preds = %21, %24
  %25 = phi i64 [ %19, %21 ], [ %32, %24 ]
  %26 = trunc nsw i64 %25 to i32
  %27 = load float, ptr %5, align 4, !tbaa !16
  %28 = sitofp i32 %26 to float
  %29 = fmul float %27, %28
  %30 = getelementptr inbounds float, ptr %22, i64 %25
  store float %29, ptr %30, align 4, !tbaa !16
  %31 = add nsw i32 %23, %26
  %32 = sext i32 %31 to i64
  %33 = icmp ugt i64 %32, %3
  br i1 %33, label %34, label %24

34:                                               ; preds = %24, %6
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %17) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %10) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %9) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %8) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %7) #2
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined_wrapper(i16 zeroext %0, i32 noundef %1) #4 {
  %3 = alloca i32, align 4, addrspace(5)
  %4 = alloca i32, align 4, addrspace(5)
  %5 = alloca i32, align 4, addrspace(5)
  %6 = alloca i32, align 4, addrspace(5)
  %7 = alloca ptr, align 8, addrspace(5)
  %8 = addrspacecast ptr addrspace(5) %7 to ptr
  call void @__kmpc_get_shared_variables(ptr %8) #2
  %9 = load ptr, ptr addrspace(5) %7, align 8
  %10 = load i64, ptr %9, align 8, !tbaa !9
  %11 = getelementptr inbounds i8, ptr %9, i64 8
  %12 = load i64, ptr %11, align 8, !tbaa !9
  %13 = getelementptr inbounds i8, ptr %9, i64 16
  %14 = load ptr, ptr %13, align 8, !tbaa !9
  %15 = getelementptr inbounds i8, ptr %9, i64 24
  %16 = load ptr, ptr %15, align 8, !tbaa !9
  %17 = addrspacecast ptr addrspace(5) %3 to ptr
  %18 = addrspacecast ptr addrspace(5) %4 to ptr
  %19 = addrspacecast ptr addrspace(5) %5 to ptr
  %20 = addrspacecast ptr addrspace(5) %6 to ptr
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %3) #9, !noalias !20
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %4) #9, !noalias !20
  %21 = trunc i64 %10 to i32
  %22 = trunc i64 %12 to i32
  store i32 %21, ptr addrspace(5) %3, align 4, !tbaa !18, !noalias !20
  store i32 %22, ptr addrspace(5) %4, align 4, !tbaa !18, !noalias !20
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %5) #9, !noalias !20
  store i32 1, ptr addrspace(5) %5, align 4, !tbaa !18, !noalias !20
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %6) #9, !noalias !20
  store i32 0, ptr addrspace(5) %6, align 4, !tbaa !18, !noalias !20
  call void @__kmpc_for_static_init_4(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %1, i32 33, ptr nonnull %20, ptr nonnull %17, ptr nonnull %18, ptr nonnull %19, i32 1, i32 1) #2, !noalias !20
  %23 = load i32, ptr addrspace(5) %3, align 4, !tbaa !18, !noalias !20
  %24 = sext i32 %23 to i64
  %25 = icmp ult i64 %12, %24
  br i1 %25, label %39, label %26

26:                                               ; preds = %2
  %27 = load ptr, ptr %14, align 8, !tbaa !9, !noalias !20
  %28 = load i32, ptr addrspace(5) %5, align 4, !tbaa !18, !noalias !20
  br label %29

29:                                               ; preds = %29, %26
  %30 = phi i64 [ %24, %26 ], [ %37, %29 ]
  %31 = trunc nsw i64 %30 to i32
  %32 = load float, ptr %16, align 4, !tbaa !16, !noalias !20
  %33 = sitofp i32 %31 to float
  %34 = fmul float %32, %33
  %35 = getelementptr inbounds float, ptr %27, i64 %30
  store float %34, ptr %35, align 4, !tbaa !16, !noalias !20
  %36 = add nsw i32 %28, %31
  %37 = sext i32 %36 to i64
  %38 = icmp ult i64 %12, %37
  br i1 %38, label %39, label %29

39:                                               ; preds = %29, %2
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %1) #2, !noalias !20
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %6) #2, !noalias !20
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %5) #2, !noalias !20
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %4) #2, !noalias !20
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %3) #2, !noalias !20
  ret void
}

declare void @__kmpc_get_shared_variables(ptr) local_unnamed_addr

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #5

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) local_unnamed_addr #6

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #7

attributes #0 = { alwaysinline convergent norecurse nounwind "amdgpu-flat-work-group-size"="1,257" "kernel" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #4 = { norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #5 = { alwaysinline }
attributes #6 = { convergent "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #7 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #8 = { convergent nounwind }
attributes #9 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!nvvm.annotations = !{!1}
!llvm.module.flags = !{!2, !3, !4, !5, !6}
!opencl.ocl.version = !{!7}
!llvm.ident = !{!8}

!0 = !{i32 0, i32 1549388176, i32 1459617797, !"_Z4stepPfS_if", i32 11, i32 0, i32 0}
!1 = !{ptr @__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11, !"kernel", i32 1}
!2 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{i32 2, i32 0}
!8 = !{!"AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)"}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14}
!14 = distinct !{!14, !15, !"__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined: argument 0"}
!15 = distinct !{!15, !"__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined"}
!16 = !{!17, !17, i64 0}
!17 = !{!"float", !11, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"int", !11, i64 0}
!20 = !{!21}
!21 = distinct !{!21, !22, !"__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined: argument 0"}
!22 = distinct !{!22, !"__omp_offloading_5c59c990_57000005__Z4stepPfS_if_l11_omp_outlined_omp_outlined"}
