; Generated by gen.sh: Inputs/legal_face3d.cpp before any optimization,
; lowered through default<O3> -- do not edit.
;
; RUN: env GICC_MODE=chunk-lower %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes='default<O3>' -S %s 2>&1 | %FileCheck %s
;
; CHECK: lowered: element grain over the box
; The kernel resolves the peer, sends the unwritten part of the range, and
; hands the range and the peer offset to the region.
; CHECK-LABEL: define {{.*}} @__omp_offloading_
; A generic kernel cannot count the teams past the range: a peer that is
; not IPC-mapped is left to the next quiet.
; CHECK: [[PD:%.*]] = call ptr @ompx__box_peer(i32 {{%.*}}, ptr {{%.*}}, ptr {{%.*}}, i64 {{%.*}}, i32 0, ptr {{%.*}})
; The kernel is still generic when the pass runs, so one thread per team
; sends the residual.
; CHECK: call void @ompx__box_residual(ptr [[PD]], ptr {{%.*}}, i64 {{%.*}}, ptr {{%.*}}, i32 3, ptr {{%.*}}, ptr {{%.*}}, i64 4, i32 {{%.*}}, i32 0)
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.delta
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.start
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.box.len
; CHECK: call void @__kmpc_distribute_static_init
; CHECK-NOT: ompx_pipelined_put
; A store in the range is repeated at the peer offset.
; CHECK-LABEL: define internal void @__omp_offloading_{{.*}}_omp_outlined_omp_outlined(
; CHECK: [[DELTA:%.*]] = load i64, ptr addrspace(3) @gicc.box.delta
; The put_no_db mirror checks the original store first; then the box check.
; CHECK: store float [[V:%[0-9]+]], ptr [[P:%[0-9]+]], align 4, !tbaa
; CHECK: %gicc.box.in = and i1
; CHECK-NEXT: br i1 %gicc.box.in
; CHECK: [[R:%.*]] = getelementptr i8, ptr [[P]], i64 [[DELTA]]
; CHECK-NEXT: store float [[V]], ptr [[R]], align 4, !gicc.repeat
; CHECK-NOT: gicc-chunk-noinline
; CHECK-NOT: ompx__box_due(

source_filename = "Inputs/legal_face3d.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_plugin_enable_fast_reduction = weak addrspace(1) constant i8 0
@__omp_rtl_debug_kind = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden addrspace(1) constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 1, i8 1, i32 1, i32 -1, i32 0, i32 0, i32 0, i32 0 }, ptr addrspacecast (ptr addrspace(1) @1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_dynamic_environment to ptr) }
@2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_wg_size = weak addrspace(1) constant i16 257
@__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_exec_mode = weak addrspace(1) constant i8 1
@llvm.compiler.used = appending addrspace(1) global [3 x ptr] [ptr addrspacecast (ptr addrspace(1) @__omp_plugin_enable_fast_reduction to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_wg_size to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_exec_mode to ptr)], section "llvm.metadata"
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600

; Function Attrs: alwaysinline convergent mustprogress norecurse nounwind
define weak_odr protected amdgpu_kernel void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef %5, i64 noundef %6, i64 noundef %7, i64 noundef %8, i64 noundef %9) #0 {
  %11 = alloca ptr, align 8, addrspace(5)
  %12 = alloca i64, align 8, addrspace(5)
  %13 = alloca i64, align 8, addrspace(5)
  %14 = alloca i64, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca ptr, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca i64, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i64, align 8, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i64, align 8, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = alloca i64, align 8, addrspace(5)
  %28 = alloca i64, align 8, addrspace(5)
  %29 = alloca i32, align 4, addrspace(5)
  %30 = alloca i32, align 4, addrspace(5)
  %31 = addrspacecast ptr addrspace(5) %11 to ptr
  %32 = addrspacecast ptr addrspace(5) %12 to ptr
  %33 = addrspacecast ptr addrspace(5) %13 to ptr
  %34 = addrspacecast ptr addrspace(5) %14 to ptr
  %35 = addrspacecast ptr addrspace(5) %15 to ptr
  %36 = addrspacecast ptr addrspace(5) %16 to ptr
  %37 = addrspacecast ptr addrspace(5) %17 to ptr
  %38 = addrspacecast ptr addrspace(5) %18 to ptr
  %39 = addrspacecast ptr addrspace(5) %19 to ptr
  %40 = addrspacecast ptr addrspace(5) %20 to ptr
  %41 = addrspacecast ptr addrspace(5) %21 to ptr
  %42 = addrspacecast ptr addrspace(5) %22 to ptr
  %43 = addrspacecast ptr addrspace(5) %23 to ptr
  %44 = addrspacecast ptr addrspace(5) %24 to ptr
  %45 = addrspacecast ptr addrspace(5) %25 to ptr
  %46 = addrspacecast ptr addrspace(5) %26 to ptr
  %47 = addrspacecast ptr addrspace(5) %27 to ptr
  %48 = addrspacecast ptr addrspace(5) %28 to ptr
  %49 = addrspacecast ptr addrspace(5) %29 to ptr
  %50 = addrspacecast ptr addrspace(5) %30 to ptr
  store ptr %0, ptr %31, align 8, !tbaa !9
  store i64 %1, ptr %32, align 8, !tbaa !13
  store i64 %2, ptr %33, align 8, !tbaa !13
  store i64 %3, ptr %34, align 8, !tbaa !13
  store i64 %4, ptr %35, align 8, !tbaa !13
  store ptr %5, ptr %36, align 8, !tbaa !9
  store i64 %6, ptr %37, align 8, !tbaa !13
  store i64 %7, ptr %38, align 8, !tbaa !13
  store i64 %8, ptr %39, align 8, !tbaa !13
  store i64 %9, ptr %40, align 8, !tbaa !13
  %51 = call i32 @__kmpc_target_init(ptr addrspacecast (ptr addrspace(1) @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_kernel_environment to ptr), ptr %0)
  %52 = icmp eq i32 %51, -1
  br i1 %52, label %53, label %72

53:                                               ; preds = %10
  %54 = call i32 @__kmpc_global_thread_num(ptr addrspacecast (ptr addrspace(1) @1 to ptr))
  %55 = load i64, ptr %32, align 8, !tbaa !15
  store i64 %55, ptr %41, align 8, !tbaa !15
  %56 = load i64, ptr %41, align 8, !tbaa !13
  %57 = load i64, ptr %33, align 8, !tbaa !15
  store i64 %57, ptr %42, align 8, !tbaa !15
  %58 = load i64, ptr %42, align 8, !tbaa !13
  %59 = load i64, ptr %34, align 8, !tbaa !15
  store i64 %59, ptr %43, align 8, !tbaa !15
  %60 = load i64, ptr %43, align 8, !tbaa !13
  %61 = load i64, ptr %35, align 8, !tbaa !15
  store i64 %61, ptr %44, align 8, !tbaa !15
  %62 = load i64, ptr %44, align 8, !tbaa !13
  %63 = load ptr, ptr %36, align 8, !tbaa !9
  %64 = load i64, ptr %37, align 8, !tbaa !15
  store i64 %64, ptr %45, align 8, !tbaa !15
  %65 = load i64, ptr %45, align 8, !tbaa !13
  %66 = load i64, ptr %38, align 8, !tbaa !15
  store i64 %66, ptr %46, align 8, !tbaa !15
  %67 = load i64, ptr %46, align 8, !tbaa !13
  %68 = load float, ptr %39, align 4, !tbaa !17
  store float %68, ptr %47, align 4, !tbaa !17
  %69 = load i64, ptr %47, align 8, !tbaa !13
  %70 = load i32, ptr %40, align 4, !tbaa !19
  store i32 %70, ptr %48, align 4, !tbaa !19
  %71 = load i64, ptr %48, align 8, !tbaa !13
  store i32 0, ptr %49, align 4
  store i32 %54, ptr %50, align 4, !tbaa !19
  call void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined(ptr %50, ptr %49, i64 %56, i64 %58, i64 %60, i64 %62, ptr %63, i64 %65, i64 %67, i64 %69, i64 %71) #4
  call void @__kmpc_target_deinit()
  ret void

72:                                               ; preds = %10
  ret void
}

declare i32 @__kmpc_target_init(ptr, ptr)

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef %6, i64 noundef %7, i64 noundef %8, i64 noundef %9, i64 noundef %10) #1 {
  %12 = alloca ptr, align 8, addrspace(5)
  %13 = alloca ptr, align 8, addrspace(5)
  %14 = alloca i64, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca i64, align 8, addrspace(5)
  %18 = alloca ptr, align 8, addrspace(5)
  %19 = alloca i64, align 8, addrspace(5)
  %20 = alloca i64, align 8, addrspace(5)
  %21 = alloca i64, align 8, addrspace(5)
  %22 = alloca i64, align 8, addrspace(5)
  %23 = alloca i64, align 8, addrspace(5)
  %24 = alloca i64, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = alloca i64, align 8, addrspace(5)
  %28 = alloca i64, align 8, addrspace(5)
  %29 = alloca i64, align 8, addrspace(5)
  %30 = alloca i64, align 8, addrspace(5)
  %31 = alloca i64, align 8, addrspace(5)
  %32 = alloca i64, align 8, addrspace(5)
  %33 = alloca i64, align 8, addrspace(5)
  %34 = alloca i64, align 8, addrspace(5)
  %35 = alloca i64, align 8, addrspace(5)
  %36 = alloca i64, align 8, addrspace(5)
  %37 = alloca i64, align 8, addrspace(5)
  %38 = alloca i64, align 8, addrspace(5)
  %39 = alloca i32, align 4, addrspace(5)
  %40 = alloca i64, align 8, addrspace(5)
  %41 = alloca i64, align 8, addrspace(5)
  %42 = alloca i64, align 8, addrspace(5)
  %43 = alloca [10 x ptr], align 8, addrspace(5)
  %44 = addrspacecast ptr addrspace(5) %12 to ptr
  %45 = addrspacecast ptr addrspace(5) %13 to ptr
  %46 = addrspacecast ptr addrspace(5) %14 to ptr
  %47 = addrspacecast ptr addrspace(5) %15 to ptr
  %48 = addrspacecast ptr addrspace(5) %16 to ptr
  %49 = addrspacecast ptr addrspace(5) %17 to ptr
  %50 = addrspacecast ptr addrspace(5) %18 to ptr
  %51 = addrspacecast ptr addrspace(5) %19 to ptr
  %52 = addrspacecast ptr addrspace(5) %20 to ptr
  %53 = addrspacecast ptr addrspace(5) %21 to ptr
  %54 = addrspacecast ptr addrspace(5) %22 to ptr
  %55 = addrspacecast ptr addrspace(5) %23 to ptr
  %56 = addrspacecast ptr addrspace(5) %24 to ptr
  %57 = addrspacecast ptr addrspace(5) %25 to ptr
  %58 = addrspacecast ptr addrspace(5) %26 to ptr
  %59 = addrspacecast ptr addrspace(5) %27 to ptr
  %60 = addrspacecast ptr addrspace(5) %28 to ptr
  %61 = addrspacecast ptr addrspace(5) %29 to ptr
  %62 = addrspacecast ptr addrspace(5) %30 to ptr
  %63 = addrspacecast ptr addrspace(5) %31 to ptr
  %64 = addrspacecast ptr addrspace(5) %32 to ptr
  %65 = addrspacecast ptr addrspace(5) %33 to ptr
  %66 = addrspacecast ptr addrspace(5) %34 to ptr
  %67 = addrspacecast ptr addrspace(5) %35 to ptr
  %68 = addrspacecast ptr addrspace(5) %36 to ptr
  %69 = addrspacecast ptr addrspace(5) %37 to ptr
  %70 = addrspacecast ptr addrspace(5) %38 to ptr
  %71 = addrspacecast ptr addrspace(5) %39 to ptr
  %72 = addrspacecast ptr addrspace(5) %40 to ptr
  %73 = addrspacecast ptr addrspace(5) %41 to ptr
  %74 = addrspacecast ptr addrspace(5) %42 to ptr
  %75 = addrspacecast ptr addrspace(5) %43 to ptr
  store ptr %0, ptr %44, align 8, !tbaa !9
  store ptr %1, ptr %45, align 8, !tbaa !9
  store i64 %2, ptr %46, align 8, !tbaa !13
  store i64 %3, ptr %47, align 8, !tbaa !13
  store i64 %4, ptr %48, align 8, !tbaa !13
  store i64 %5, ptr %49, align 8, !tbaa !13
  store ptr %6, ptr %50, align 8, !tbaa !9
  store i64 %7, ptr %51, align 8, !tbaa !13
  store i64 %8, ptr %52, align 8, !tbaa !13
  store i64 %9, ptr %53, align 8, !tbaa !13
  store i64 %10, ptr %54, align 8, !tbaa !13
  %76 = load i64, ptr %46, align 8, !tbaa !15
  %77 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %76, ptr %77, align 8, !tbaa !15
  %78 = load i64, ptr %47, align 8, !tbaa !15
  %79 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %78, ptr %79, align 8, !tbaa !15
  %80 = load i64, ptr %48, align 8, !tbaa !15
  %81 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %80, ptr %81, align 8, !tbaa !15
  %82 = load i64, ptr %49, align 8, !tbaa !15
  %83 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %82, ptr %83, align 8, !tbaa !15
  %84 = load ptr, ptr %50, align 8, !tbaa !9
  %85 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store ptr %84, ptr %85, align 8, !tbaa !9
  %86 = load i64, ptr %51, align 8, !tbaa !15
  %87 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %86, ptr %87, align 8, !tbaa !15
  %88 = load i64, ptr %52, align 8, !tbaa !15
  %89 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %88, ptr %89, align 8, !tbaa !15
  %90 = load float, ptr %53, align 4, !tbaa !17
  %91 = call align 16 ptr @__kmpc_alloc_shared(i64 4)
  store float %90, ptr %91, align 4, !tbaa !17
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %23) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %27) #4
  %92 = load i64, ptr %77, align 8, !tbaa !15
  store i64 %92, ptr %59, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %28) #4
  %93 = load i64, ptr %81, align 8, !tbaa !15
  store i64 %93, ptr %60, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %29) #4
  %94 = load i64, ptr %81, align 8, !tbaa !15
  %95 = load i64, ptr %79, align 8, !tbaa !15
  %96 = add nsw i64 %94, %95
  store i64 %96, ptr %61, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %30) #4
  %97 = load i64, ptr %81, align 8, !tbaa !15
  store i64 %97, ptr %62, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %31) #4
  %98 = load i64, ptr %81, align 8, !tbaa !15
  %99 = load i64, ptr %83, align 8, !tbaa !15
  %100 = add nsw i64 %98, %99
  store i64 %100, ptr %63, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %32) #4
  %101 = load i64, ptr %59, align 8, !tbaa !15
  %102 = sub nsw i64 %101, 0
  %103 = sdiv i64 %102, 1
  %104 = load i64, ptr %61, align 8, !tbaa !15
  %105 = load i64, ptr %60, align 8, !tbaa !15
  %106 = sub i64 %104, %105
  %107 = sub i64 %106, 1
  %108 = add i64 %107, 1
  %109 = udiv i64 %108, 1
  %110 = mul i64 %103, %109
  %111 = load i64, ptr %63, align 8, !tbaa !15
  %112 = load i64, ptr %62, align 8, !tbaa !15
  %113 = sub i64 %111, %112
  %114 = sub i64 %113, 1
  %115 = add i64 %114, 1
  %116 = udiv i64 %115, 1
  %117 = mul i64 %110, %116
  %118 = sub i64 %117, 1
  store i64 %118, ptr %64, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %33) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %34) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %35) #4
  store i64 0, ptr %65, align 8, !tbaa !15
  %119 = load i64, ptr %60, align 8, !tbaa !15
  store i64 %119, ptr %66, align 8, !tbaa !15
  %120 = load i64, ptr %62, align 8, !tbaa !15
  store i64 %120, ptr %67, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %35) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %34) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %33) #4
  %121 = load i64, ptr %59, align 8, !tbaa !15
  %122 = icmp slt i64 0, %121
  br i1 %122, label %123, label %176

123:                                              ; preds = %11
  %124 = load i64, ptr %60, align 8, !tbaa !15
  %125 = load i64, ptr %61, align 8, !tbaa !15
  %126 = icmp slt i64 %124, %125
  br i1 %126, label %127, label %176

127:                                              ; preds = %123
  %128 = load i64, ptr %62, align 8, !tbaa !15
  %129 = load i64, ptr %63, align 8, !tbaa !15
  %130 = icmp slt i64 %128, %129
  br i1 %130, label %131, label %176

131:                                              ; preds = %127
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %36) #4
  store i64 0, ptr %68, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %37) #4
  %132 = load i64, ptr %64, align 8, !tbaa !15
  store i64 %132, ptr %69, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %38) #4
  store i64 1, ptr %70, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %39) #4
  store i32 0, ptr %71, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %40) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %41) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %42) #4
  %133 = load ptr, ptr %44, align 8
  %134 = load i32, ptr %133, align 4, !tbaa !19
  call void @__kmpc_distribute_static_init_8u(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %134, i32 92, ptr %71, ptr %68, ptr %69, ptr %70, i64 1, i64 1)
  %135 = load i64, ptr %69, align 8, !tbaa !15
  %136 = load i64, ptr %64, align 8, !tbaa !15
  %137 = icmp ugt i64 %135, %136
  br i1 %137, label %138, label %140

138:                                              ; preds = %131
  %139 = load i64, ptr %64, align 8, !tbaa !15
  br label %142

140:                                              ; preds = %131
  %141 = load i64, ptr %69, align 8, !tbaa !15
  br label %142

142:                                              ; preds = %140, %138
  %143 = phi i64 [ %139, %138 ], [ %141, %140 ]
  store i64 %143, ptr %69, align 8, !tbaa !15
  %144 = load i64, ptr %68, align 8, !tbaa !15
  store i64 %144, ptr %55, align 8, !tbaa !15
  br label %145

145:                                              ; preds = %168, %142
  %146 = load i64, ptr %55, align 8, !tbaa !15
  %147 = load i64, ptr %69, align 8, !tbaa !15
  %148 = add i64 %147, 1
  %149 = icmp ult i64 %146, %148
  br i1 %149, label %151, label %150

150:                                              ; preds = %145
  br label %172

151:                                              ; preds = %145
  %152 = load i64, ptr %68, align 8
  %153 = load i64, ptr %69, align 8
  %154 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 0
  %155 = inttoptr i64 %152 to ptr
  store ptr %155, ptr %154, align 8, !tbaa !9
  %156 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 1
  %157 = inttoptr i64 %153 to ptr
  store ptr %157, ptr %156, align 8, !tbaa !9
  %158 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 2
  store ptr %77, ptr %158, align 8, !tbaa !9
  %159 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 3
  store ptr %79, ptr %159, align 8, !tbaa !9
  %160 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 4
  store ptr %81, ptr %160, align 8, !tbaa !9
  %161 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 5
  store ptr %83, ptr %161, align 8, !tbaa !9
  %162 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 6
  store ptr %85, ptr %162, align 8, !tbaa !9
  %163 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 7
  store ptr %87, ptr %163, align 8, !tbaa !9
  %164 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 8
  store ptr %89, ptr %164, align 8, !tbaa !9
  %165 = getelementptr inbounds [10 x ptr], ptr %75, i64 0, i64 9
  store ptr %91, ptr %165, align 8, !tbaa !9
  %166 = load ptr, ptr %44, align 8
  %167 = load i32, ptr %166, align 4, !tbaa !19
  call void @__kmpc_parallel_51(ptr addrspacecast (ptr addrspace(1) @1 to ptr), i32 %167, i32 1, i32 -1, i32 -1, ptr @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined_omp_outlined, ptr @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined_omp_outlined_wrapper, ptr %75, i64 10)
  br label %168

168:                                              ; preds = %151
  %169 = load i64, ptr %55, align 8, !tbaa !15
  %170 = load i64, ptr %70, align 8, !tbaa !15
  %171 = add i64 %169, %170
  store i64 %171, ptr %55, align 8, !tbaa !15
  br label %145

172:                                              ; preds = %150
  br label %173

173:                                              ; preds = %172
  %174 = load ptr, ptr %44, align 8
  %175 = load i32, ptr %174, align 4, !tbaa !19
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @2 to ptr), i32 %175)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %42) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %41) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %40) #4
  br label %176

176:                                              ; preds = %173, %127, %123, %11
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %39) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %38) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %37) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %36) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %32) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %31) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %30) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %29) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %28) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %27) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %23) #4
  %177 = load i32, ptr %54, align 4, !tbaa !19
  %178 = load ptr, ptr %85, align 8, !tbaa !9
  %179 = load ptr, ptr %85, align 8, !tbaa !9
  %180 = load i64, ptr %87, align 8, !tbaa !15
  %181 = load i64, ptr %89, align 8, !tbaa !15
  %182 = mul nsw i64 %180, %181
  %183 = mul i64 %182, 4
  call void @ompx_pipelined_put(i32 noundef %177, ptr noundef %178, ptr noundef %179, i64 noundef %183) #9
  call void @__kmpc_free_shared(ptr %91, i64 4)
  call void @__kmpc_free_shared(ptr %89, i64 8)
  call void @__kmpc_free_shared(ptr %87, i64 8)
  call void @__kmpc_free_shared(ptr %85, i64 8)
  call void @__kmpc_free_shared(ptr %83, i64 8)
  call void @__kmpc_free_shared(ptr %81, i64 8)
  call void @__kmpc_free_shared(ptr %79, i64 8)
  call void @__kmpc_free_shared(ptr %77, i64 8)
  ret void
}

; Function Attrs: nosync nounwind allocsize(0)
declare noalias ptr @__kmpc_alloc_shared(i64) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #3

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #4

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, ptr noundef nonnull align 8 dereferenceable(8) %4, ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 8 dereferenceable(8) %6, ptr noundef nonnull align 8 dereferenceable(8) %7, ptr noundef nonnull align 8 dereferenceable(8) %8, ptr noundef nonnull align 8 dereferenceable(8) %9, ptr noundef nonnull align 8 dereferenceable(8) %10, ptr noundef nonnull align 4 dereferenceable(4) %11) #1 {
  %13 = alloca ptr, align 8, addrspace(5)
  %14 = alloca ptr, align 8, addrspace(5)
  %15 = alloca i64, align 8, addrspace(5)
  %16 = alloca i64, align 8, addrspace(5)
  %17 = alloca ptr, align 8, addrspace(5)
  %18 = alloca ptr, align 8, addrspace(5)
  %19 = alloca ptr, align 8, addrspace(5)
  %20 = alloca ptr, align 8, addrspace(5)
  %21 = alloca ptr, align 8, addrspace(5)
  %22 = alloca ptr, align 8, addrspace(5)
  %23 = alloca ptr, align 8, addrspace(5)
  %24 = alloca ptr, align 8, addrspace(5)
  %25 = alloca i64, align 8, addrspace(5)
  %26 = alloca i64, align 8, addrspace(5)
  %27 = alloca i64, align 8, addrspace(5)
  %28 = alloca i64, align 8, addrspace(5)
  %29 = alloca i64, align 8, addrspace(5)
  %30 = alloca i64, align 8, addrspace(5)
  %31 = alloca i64, align 8, addrspace(5)
  %32 = alloca i64, align 8, addrspace(5)
  %33 = alloca i64, align 8, addrspace(5)
  %34 = alloca i64, align 8, addrspace(5)
  %35 = alloca i64, align 8, addrspace(5)
  %36 = alloca i64, align 8, addrspace(5)
  %37 = alloca i64, align 8, addrspace(5)
  %38 = alloca i64, align 8, addrspace(5)
  %39 = alloca i64, align 8, addrspace(5)
  %40 = alloca i64, align 8, addrspace(5)
  %41 = alloca i32, align 4, addrspace(5)
  %42 = alloca i64, align 8, addrspace(5)
  %43 = alloca i64, align 8, addrspace(5)
  %44 = alloca i64, align 8, addrspace(5)
  %45 = addrspacecast ptr addrspace(5) %13 to ptr
  %46 = addrspacecast ptr addrspace(5) %14 to ptr
  %47 = addrspacecast ptr addrspace(5) %15 to ptr
  %48 = addrspacecast ptr addrspace(5) %16 to ptr
  %49 = addrspacecast ptr addrspace(5) %17 to ptr
  %50 = addrspacecast ptr addrspace(5) %18 to ptr
  %51 = addrspacecast ptr addrspace(5) %19 to ptr
  %52 = addrspacecast ptr addrspace(5) %20 to ptr
  %53 = addrspacecast ptr addrspace(5) %21 to ptr
  %54 = addrspacecast ptr addrspace(5) %22 to ptr
  %55 = addrspacecast ptr addrspace(5) %23 to ptr
  %56 = addrspacecast ptr addrspace(5) %24 to ptr
  %57 = addrspacecast ptr addrspace(5) %25 to ptr
  %58 = addrspacecast ptr addrspace(5) %26 to ptr
  %59 = addrspacecast ptr addrspace(5) %27 to ptr
  %60 = addrspacecast ptr addrspace(5) %28 to ptr
  %61 = addrspacecast ptr addrspace(5) %29 to ptr
  %62 = addrspacecast ptr addrspace(5) %30 to ptr
  %63 = addrspacecast ptr addrspace(5) %31 to ptr
  %64 = addrspacecast ptr addrspace(5) %32 to ptr
  %65 = addrspacecast ptr addrspace(5) %33 to ptr
  %66 = addrspacecast ptr addrspace(5) %34 to ptr
  %67 = addrspacecast ptr addrspace(5) %35 to ptr
  %68 = addrspacecast ptr addrspace(5) %36 to ptr
  %69 = addrspacecast ptr addrspace(5) %37 to ptr
  %70 = addrspacecast ptr addrspace(5) %38 to ptr
  %71 = addrspacecast ptr addrspace(5) %39 to ptr
  %72 = addrspacecast ptr addrspace(5) %40 to ptr
  %73 = addrspacecast ptr addrspace(5) %41 to ptr
  %74 = addrspacecast ptr addrspace(5) %42 to ptr
  %75 = addrspacecast ptr addrspace(5) %43 to ptr
  %76 = addrspacecast ptr addrspace(5) %44 to ptr
  store ptr %0, ptr %45, align 8, !tbaa !9
  store ptr %1, ptr %46, align 8, !tbaa !9
  store i64 %2, ptr %47, align 8, !tbaa !13
  store i64 %3, ptr %48, align 8, !tbaa !13
  store ptr %4, ptr %49, align 8, !tbaa !9
  store ptr %5, ptr %50, align 8, !tbaa !9
  store ptr %6, ptr %51, align 8, !tbaa !9
  store ptr %7, ptr %52, align 8, !tbaa !9
  store ptr %8, ptr %53, align 8, !tbaa !9
  store ptr %9, ptr %54, align 8, !tbaa !9
  store ptr %10, ptr %55, align 8, !tbaa !9
  store ptr %11, ptr %56, align 8, !tbaa !9
  %77 = load ptr, ptr %49, align 8, !tbaa !9
  %78 = load ptr, ptr %50, align 8, !tbaa !9
  %79 = load ptr, ptr %51, align 8, !tbaa !9
  %80 = load ptr, ptr %52, align 8, !tbaa !9
  %81 = load ptr, ptr %53, align 8, !tbaa !9
  %82 = load ptr, ptr %54, align 8, !tbaa !9
  %83 = load ptr, ptr %55, align 8, !tbaa !9
  %84 = load ptr, ptr %56, align 8, !tbaa !9
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %25) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %29) #4
  %85 = load i64, ptr %77, align 8, !tbaa !15
  store i64 %85, ptr %61, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %30) #4
  %86 = load i64, ptr %79, align 8, !tbaa !15
  store i64 %86, ptr %62, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %31) #4
  %87 = load i64, ptr %79, align 8, !tbaa !15
  %88 = load i64, ptr %78, align 8, !tbaa !15
  %89 = add nsw i64 %87, %88
  store i64 %89, ptr %63, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %32) #4
  %90 = load i64, ptr %79, align 8, !tbaa !15
  store i64 %90, ptr %64, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %33) #4
  %91 = load i64, ptr %79, align 8, !tbaa !15
  %92 = load i64, ptr %80, align 8, !tbaa !15
  %93 = add nsw i64 %91, %92
  store i64 %93, ptr %65, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %34) #4
  %94 = load i64, ptr %61, align 8, !tbaa !15
  %95 = sub nsw i64 %94, 0
  %96 = sdiv i64 %95, 1
  %97 = load i64, ptr %63, align 8, !tbaa !15
  %98 = load i64, ptr %62, align 8, !tbaa !15
  %99 = sub i64 %97, %98
  %100 = sub i64 %99, 1
  %101 = add i64 %100, 1
  %102 = udiv i64 %101, 1
  %103 = mul i64 %96, %102
  %104 = load i64, ptr %65, align 8, !tbaa !15
  %105 = load i64, ptr %64, align 8, !tbaa !15
  %106 = sub i64 %104, %105
  %107 = sub i64 %106, 1
  %108 = add i64 %107, 1
  %109 = udiv i64 %108, 1
  %110 = mul i64 %103, %109
  %111 = sub i64 %110, 1
  store i64 %111, ptr %66, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %35) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %36) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %37) #4
  store i64 0, ptr %67, align 8, !tbaa !15
  %112 = load i64, ptr %62, align 8, !tbaa !15
  store i64 %112, ptr %68, align 8, !tbaa !15
  %113 = load i64, ptr %64, align 8, !tbaa !15
  store i64 %113, ptr %69, align 8, !tbaa !15
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %37) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %36) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %35) #4
  %114 = load i64, ptr %61, align 8, !tbaa !15
  %115 = icmp slt i64 0, %114
  br i1 %115, label %116, label %310

116:                                              ; preds = %12
  %117 = load i64, ptr %62, align 8, !tbaa !15
  %118 = load i64, ptr %63, align 8, !tbaa !15
  %119 = icmp slt i64 %117, %118
  br i1 %119, label %120, label %310

120:                                              ; preds = %116
  %121 = load i64, ptr %64, align 8, !tbaa !15
  %122 = load i64, ptr %65, align 8, !tbaa !15
  %123 = icmp slt i64 %121, %122
  br i1 %123, label %124, label %310

124:                                              ; preds = %120
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %38) #4
  store i64 0, ptr %70, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %39) #4
  %125 = load i64, ptr %66, align 8, !tbaa !15
  store i64 %125, ptr %71, align 8, !tbaa !15
  %126 = load i64, ptr %47, align 8, !tbaa !13
  %127 = load i64, ptr %48, align 8, !tbaa !13
  store i64 %126, ptr %70, align 8, !tbaa !15
  store i64 %127, ptr %71, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %40) #4
  store i64 1, ptr %72, align 8, !tbaa !15
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %41) #4
  store i32 0, ptr %73, align 4, !tbaa !19
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %42) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %43) #4
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %44) #4
  %128 = load ptr, ptr %45, align 8
  %129 = load i32, ptr %128, align 4, !tbaa !19
  call void @__kmpc_for_static_init_8u(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %129, i32 33, ptr %73, ptr %70, ptr %71, ptr %72, i64 1, i64 1)
  %130 = load i64, ptr %70, align 8, !tbaa !15
  store i64 %130, ptr %57, align 8, !tbaa !15
  br label %131

131:                                              ; preds = %302, %124
  %132 = load i64, ptr %57, align 8, !tbaa !15
  %133 = load i64, ptr %48, align 8, !tbaa !13
  %134 = add i64 %133, 1
  %135 = icmp ult i64 %132, %134
  br i1 %135, label %137, label %136

136:                                              ; preds = %131
  br label %306

137:                                              ; preds = %131
  %138 = load i64, ptr %57, align 8, !tbaa !15
  %139 = load i64, ptr %63, align 8, !tbaa !15
  %140 = load i64, ptr %62, align 8, !tbaa !15
  %141 = sub i64 %139, %140
  %142 = sub i64 %141, 1
  %143 = add i64 %142, 1
  %144 = udiv i64 %143, 1
  %145 = mul i64 1, %144
  %146 = load i64, ptr %65, align 8, !tbaa !15
  %147 = load i64, ptr %64, align 8, !tbaa !15
  %148 = sub i64 %146, %147
  %149 = sub i64 %148, 1
  %150 = add i64 %149, 1
  %151 = udiv i64 %150, 1
  %152 = mul i64 %145, %151
  %153 = udiv i64 %138, %152
  %154 = mul i64 %153, 1
  %155 = add i64 0, %154
  store i64 %155, ptr %74, align 8, !tbaa !15
  %156 = load i64, ptr %62, align 8, !tbaa !15
  %157 = load i64, ptr %57, align 8, !tbaa !15
  %158 = load i64, ptr %57, align 8, !tbaa !15
  %159 = load i64, ptr %63, align 8, !tbaa !15
  %160 = load i64, ptr %62, align 8, !tbaa !15
  %161 = sub i64 %159, %160
  %162 = sub i64 %161, 1
  %163 = add i64 %162, 1
  %164 = udiv i64 %163, 1
  %165 = mul i64 1, %164
  %166 = load i64, ptr %65, align 8, !tbaa !15
  %167 = load i64, ptr %64, align 8, !tbaa !15
  %168 = sub i64 %166, %167
  %169 = sub i64 %168, 1
  %170 = add i64 %169, 1
  %171 = udiv i64 %170, 1
  %172 = mul i64 %165, %171
  %173 = udiv i64 %158, %172
  %174 = load i64, ptr %63, align 8, !tbaa !15
  %175 = load i64, ptr %62, align 8, !tbaa !15
  %176 = sub i64 %174, %175
  %177 = sub i64 %176, 1
  %178 = add i64 %177, 1
  %179 = udiv i64 %178, 1
  %180 = mul i64 1, %179
  %181 = load i64, ptr %65, align 8, !tbaa !15
  %182 = load i64, ptr %64, align 8, !tbaa !15
  %183 = sub i64 %181, %182
  %184 = sub i64 %183, 1
  %185 = add i64 %184, 1
  %186 = udiv i64 %185, 1
  %187 = mul i64 %180, %186
  %188 = mul i64 %173, %187
  %189 = sub i64 %157, %188
  %190 = load i64, ptr %65, align 8, !tbaa !15
  %191 = load i64, ptr %64, align 8, !tbaa !15
  %192 = sub i64 %190, %191
  %193 = sub i64 %192, 1
  %194 = add i64 %193, 1
  %195 = udiv i64 %194, 1
  %196 = mul i64 1, %195
  %197 = udiv i64 %189, %196
  %198 = mul i64 %197, 1
  %199 = add i64 %156, %198
  store i64 %199, ptr %75, align 8, !tbaa !15
  %200 = load i64, ptr %64, align 8, !tbaa !15
  %201 = load i64, ptr %57, align 8, !tbaa !15
  %202 = load i64, ptr %57, align 8, !tbaa !15
  %203 = load i64, ptr %63, align 8, !tbaa !15
  %204 = load i64, ptr %62, align 8, !tbaa !15
  %205 = sub i64 %203, %204
  %206 = sub i64 %205, 1
  %207 = add i64 %206, 1
  %208 = udiv i64 %207, 1
  %209 = mul i64 1, %208
  %210 = load i64, ptr %65, align 8, !tbaa !15
  %211 = load i64, ptr %64, align 8, !tbaa !15
  %212 = sub i64 %210, %211
  %213 = sub i64 %212, 1
  %214 = add i64 %213, 1
  %215 = udiv i64 %214, 1
  %216 = mul i64 %209, %215
  %217 = udiv i64 %202, %216
  %218 = load i64, ptr %63, align 8, !tbaa !15
  %219 = load i64, ptr %62, align 8, !tbaa !15
  %220 = sub i64 %218, %219
  %221 = sub i64 %220, 1
  %222 = add i64 %221, 1
  %223 = udiv i64 %222, 1
  %224 = mul i64 1, %223
  %225 = load i64, ptr %65, align 8, !tbaa !15
  %226 = load i64, ptr %64, align 8, !tbaa !15
  %227 = sub i64 %225, %226
  %228 = sub i64 %227, 1
  %229 = add i64 %228, 1
  %230 = udiv i64 %229, 1
  %231 = mul i64 %224, %230
  %232 = mul i64 %217, %231
  %233 = sub i64 %201, %232
  %234 = load i64, ptr %57, align 8, !tbaa !15
  %235 = load i64, ptr %57, align 8, !tbaa !15
  %236 = load i64, ptr %63, align 8, !tbaa !15
  %237 = load i64, ptr %62, align 8, !tbaa !15
  %238 = sub i64 %236, %237
  %239 = sub i64 %238, 1
  %240 = add i64 %239, 1
  %241 = udiv i64 %240, 1
  %242 = mul i64 1, %241
  %243 = load i64, ptr %65, align 8, !tbaa !15
  %244 = load i64, ptr %64, align 8, !tbaa !15
  %245 = sub i64 %243, %244
  %246 = sub i64 %245, 1
  %247 = add i64 %246, 1
  %248 = udiv i64 %247, 1
  %249 = mul i64 %242, %248
  %250 = udiv i64 %235, %249
  %251 = load i64, ptr %63, align 8, !tbaa !15
  %252 = load i64, ptr %62, align 8, !tbaa !15
  %253 = sub i64 %251, %252
  %254 = sub i64 %253, 1
  %255 = add i64 %254, 1
  %256 = udiv i64 %255, 1
  %257 = mul i64 1, %256
  %258 = load i64, ptr %65, align 8, !tbaa !15
  %259 = load i64, ptr %64, align 8, !tbaa !15
  %260 = sub i64 %258, %259
  %261 = sub i64 %260, 1
  %262 = add i64 %261, 1
  %263 = udiv i64 %262, 1
  %264 = mul i64 %257, %263
  %265 = mul i64 %250, %264
  %266 = sub i64 %234, %265
  %267 = load i64, ptr %65, align 8, !tbaa !15
  %268 = load i64, ptr %64, align 8, !tbaa !15
  %269 = sub i64 %267, %268
  %270 = sub i64 %269, 1
  %271 = add i64 %270, 1
  %272 = udiv i64 %271, 1
  %273 = mul i64 1, %272
  %274 = udiv i64 %266, %273
  %275 = load i64, ptr %65, align 8, !tbaa !15
  %276 = load i64, ptr %64, align 8, !tbaa !15
  %277 = sub i64 %275, %276
  %278 = sub i64 %277, 1
  %279 = add i64 %278, 1
  %280 = udiv i64 %279, 1
  %281 = mul i64 1, %280
  %282 = mul i64 %274, %281
  %283 = sub i64 %233, %282
  %284 = mul i64 %283, 1
  %285 = add i64 %200, %284
  store i64 %285, ptr %76, align 8, !tbaa !15
  %286 = load float, ptr %84, align 4, !tbaa !17
  %287 = load i64, ptr %76, align 8, !tbaa !15
  %288 = sitofp i64 %287 to float
  %289 = fmul float %286, %288
  %290 = load ptr, ptr %81, align 8, !tbaa !9
  %291 = load i64, ptr %74, align 8, !tbaa !15
  %292 = load i64, ptr %82, align 8, !tbaa !15
  %293 = mul nsw i64 %291, %292
  %294 = load i64, ptr %75, align 8, !tbaa !15
  %295 = add nsw i64 %293, %294
  %296 = load i64, ptr %83, align 8, !tbaa !15
  %297 = mul nsw i64 %295, %296
  %298 = load i64, ptr %76, align 8, !tbaa !15
  %299 = add nsw i64 %297, %298
  %300 = getelementptr inbounds float, ptr %290, i64 %299
  store float %289, ptr %300, align 4, !tbaa !17
  br label %301

301:                                              ; preds = %137
  br label %302

302:                                              ; preds = %301
  %303 = load i64, ptr %57, align 8, !tbaa !15
  %304 = load i64, ptr %72, align 8, !tbaa !15
  %305 = add i64 %303, %304
  store i64 %305, ptr %57, align 8, !tbaa !15
  br label %131

306:                                              ; preds = %136
  br label %307

307:                                              ; preds = %306
  %308 = load ptr, ptr %45, align 8
  %309 = load i32, ptr %308, align 4, !tbaa !19
  call void @__kmpc_for_static_fini(ptr addrspacecast (ptr addrspace(1) @3 to ptr), i32 %309)
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %44) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %43) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %42) #4
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %41) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %40) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %39) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %38) #4
  br label %310

310:                                              ; preds = %307, %120, %116, %12
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %34) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %33) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %32) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %31) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %30) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %29) #4
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %25) #4
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #4

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) #4

; Function Attrs: convergent norecurse nounwind
define internal void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined_omp_outlined_wrapper(i16 noundef zeroext %0, i32 noundef %1) #5 {
  %3 = alloca i16, align 2, addrspace(5)
  %4 = alloca i32, align 4, addrspace(5)
  %5 = alloca i32, align 4, addrspace(5)
  %6 = alloca ptr, align 8, addrspace(5)
  %7 = addrspacecast ptr addrspace(5) %3 to ptr
  %8 = addrspacecast ptr addrspace(5) %4 to ptr
  %9 = addrspacecast ptr addrspace(5) %5 to ptr
  %10 = addrspacecast ptr addrspace(5) %6 to ptr
  store i16 %0, ptr %7, align 2, !tbaa !21
  store i32 %1, ptr %8, align 4, !tbaa !19
  store i32 0, ptr %9, align 4
  call void @__kmpc_get_shared_variables(ptr %10)
  %11 = load ptr, ptr %10, align 8
  %12 = getelementptr inbounds ptr, ptr %11, i64 0
  %13 = load i64, ptr %12, align 8, !tbaa !9
  %14 = getelementptr inbounds ptr, ptr %11, i64 1
  %15 = load i64, ptr %14, align 8, !tbaa !9
  %16 = getelementptr inbounds ptr, ptr %11, i64 2
  %17 = load ptr, ptr %16, align 8, !tbaa !9
  %18 = getelementptr inbounds ptr, ptr %11, i64 3
  %19 = load ptr, ptr %18, align 8, !tbaa !9
  %20 = getelementptr inbounds ptr, ptr %11, i64 4
  %21 = load ptr, ptr %20, align 8, !tbaa !9
  %22 = getelementptr inbounds ptr, ptr %11, i64 5
  %23 = load ptr, ptr %22, align 8, !tbaa !9
  %24 = getelementptr inbounds ptr, ptr %11, i64 6
  %25 = load ptr, ptr %24, align 8, !tbaa !9
  %26 = getelementptr inbounds ptr, ptr %11, i64 7
  %27 = load ptr, ptr %26, align 8, !tbaa !9
  %28 = getelementptr inbounds ptr, ptr %11, i64 8
  %29 = load ptr, ptr %28, align 8, !tbaa !9
  %30 = getelementptr inbounds ptr, ptr %11, i64 9
  %31 = load ptr, ptr %30, align 8, !tbaa !9
  call void @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12_omp_outlined_omp_outlined(ptr %8, ptr %9, i64 %13, i64 %15, ptr %17, ptr %19, ptr %21, ptr %23, ptr %25, ptr %27, ptr %29, ptr %31) #4
  ret void
}

declare void @__kmpc_get_shared_variables(ptr)

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) #6

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) #4

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) #7

; Function Attrs: nosync nounwind
declare void @__kmpc_free_shared(ptr allocptr nocapture, i64) #8

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) #4

declare void @__kmpc_target_deinit()

attributes #0 = { alwaysinline convergent mustprogress norecurse nounwind "amdgpu-flat-work-group-size"="1,257" "kernel" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { alwaysinline convergent norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #2 = { nosync nounwind allocsize(0) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #4 = { nounwind }
attributes #5 = { convergent norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #6 = { alwaysinline }
attributes #7 = { convergent "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx90a" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-fadd-rtn-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #8 = { nosync nounwind }
attributes #9 = { convergent }

!omp_offload.info = !{!0}
!nvvm.annotations = !{!1}
!llvm.module.flags = !{!2, !3, !4, !5, !6}
!llvm.ident = !{!7, !7, !7, !7, !7, !7, !7, !7, !7}
!opencl.ocl.version = !{!8, !8, !8, !8, !8, !8, !8, !8}

!0 = !{i32 0, i32 1549388176, i32 1459617794, !"_Z4stepPfxxxxif", i32 12, i32 0, i32 0}
!1 = !{ptr @__omp_offloading_5c59c990_57000002__Z4stepPfxxxxif_l12, !"kernel", i32 1}
!2 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{!"AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)"}
!8 = !{i32 2, i32 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"any pointer", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14, !14, i64 0}
!14 = !{!"long", !11, i64 0}
!15 = !{!16, !16, i64 0}
!16 = !{!"long long", !11, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"float", !11, i64 0}
!19 = !{!20, !20, i64 0}
!20 = !{!"int", !11, i64 0}
!21 = !{!22, !22, i64 0}
!22 = !{!"short", !11, i64 0}
