/**
 * ofi_device.cuh - libfabric/CXI device-side API
 *
 * Mirrors src/gicc/platform/mlx5/mlx5_device.cuh as closely as the hardware
 * model permits. Both backends expose the same kernel-visible primitives:
 *
 *   gicc::put_no_db(ctx, target_rank,
 *                   dst_buf, dst_offset,
 *                   src_buf, src_offset,
 *                   size, signaled=false)
 *
 *   gicc::get_no_db(ctx, source_rank,
 *                   src_buf, src_offset,
 *                   dst_buf, dst_offset,
 *                   size, signaled=false)
 *
 *   gicc::flush(ctx)
 *   gicc::quiet(ctx)
 *
 * (target_rank, dst_buf, dst_offset) names a slice of the destination
 * peer's registered buffer; (src_buf, src_offset) names a slice of the
 * caller's local buffer. All look-up data (peer base addr / rkey, local
 * base ptr / lkey) lives in the ctx tables that Runtime::exchange()
 * populates — the user never needs to thread those manually.
 *
 * A single launch can issue puts/gets to multiple peers; target_rank +
 * dst_buf are PER-CALL.
 *
 * --- OFI dispatch ---
 *
 * On OFI, put_no_db's device-side body picks one of two paths based on
 * runtime IPC mapping state (built by Runtime::exchange()):
 *
 *   1. IPC route (peer is on the same node and exposed an IPC handle):
 *      direct GPU stores into the peer's IPC-mapped buffer using
 *      block-cooperative memcpy_block. The "send" completes in-kernel.
 *
 *   2. DWQ route (off-node peer): the device-side put_no_db is a no-op.
 *      The host trace generated by gicc-clang-plugin already pre-staged
 *      this op via Runtime::put_no_db(...) on the host (which queued a
 *      DwqWorkBuilder for libfabric). flush() rings the trigger MMIO so
 *      the NIC starts processing the queued ops.
 *
 * Calling contract:
 *   - put_no_db must be called from all threads of block 0. The IPC
 *     branch uses memcpy_block + __syncthreads which deadlocks if not all
 *     block-0 threads enter. (For DWQ-only configs the contract is moot,
 *     but writing kernels to the conservative form is portable across
 *     IPC and non-IPC same-node setups.)
 *   - flush is single-thread (only thread (0,0,0) of block (0,0,0) writes
 *     the trigger MMIO). The IPC route does not pass through flush.
 *   - quiet polls DWQ completion slots cooperatively (any thread of
 *     block 0 can call; loop strides by blockDim.x).
 */
#pragma once

#include <hip/hip_runtime.h>
#include <cstdint>

namespace gicc {

//==============================================================================
// IpcMapEntry — one entry per (peer, dst_buf_idx) populated by Runtime
// after exchange(). When mapped_ptr != nullptr, this peer's buffer is
// reachable via direct GPU stores (IPC fast path); device-side put_no_db
// uses (mapped_ptr + dst_offset) as the destination.
//==============================================================================
struct IpcMapEntry {
    void* mapped_ptr;   // peer's GPU buffer mapped into THIS GPU; nullptr if off-node
};

//==============================================================================
// LocalBufView — one entry per locally registered buffer. Lets the
// device-side put_no_db turn (src_buf, src_offset) into an actual GPU
// pointer without the user having to thread the absolute address.
//==============================================================================
struct LocalBufView {
    void* base;   // GPU pointer returned from hipMalloc
};

//==============================================================================
// IpcCmdSlot — entry in the GPU→CPU command ring used by host_wait_mode +
// monitor-thread IPC. Device-side put_no_db's IPC branch atomically claims
// a slot, writes (dst, src, size), threadfence_system to publish to host.
// A CPU monitor thread polls the head, sees new entries, and issues the
// real hipMemcpyAsync onto the dedicated ipc_stream_.
//
// This preserves "comm fires AT the put_no_db line" semantics — the device
// write happens at the call site in the user's kernel, not at gicc::launch
// call time on the host.
//==============================================================================
struct IpcCmdSlot {
    void*    dst;
    void*    src;
    uint64_t size;
};

//==============================================================================
// DeviceCtx — GPU-accessible context for the libfabric/CXI backend.
//
// completion_ points to the BASE of an n_ops_-element array. Each slot
// is the atomic_result GPU memory location for one queued DWQ op;
// quiet() returns once every slot has reached 1.
//
// ipc_map_ / max_bufs_per_rank_ let device put_no_db do (peer, dst_buf)
// → peer-mapped pointer lookup with no host involvement.
//
// local_bufs_ lets device put_no_db / get_no_db turn (src_buf,
// src_offset) into a real GPU pointer. n_local_bufs_ bounds it.
//==============================================================================
struct DeviceCtx {
    volatile uint64_t* trigger_addr_;       // MMIO trigger counter
    volatile uint64_t* completion_;         // base of n_ops_ × uint64_t poll slots
    uint64_t           trigger_val_;        // value to write to trigger_addr_
    uint64_t           n_ops_;              // number of slots to wait on

    const IpcMapEntry*  ipc_map_;           // [n_peers * max_bufs_per_rank_]
    int                 max_bufs_per_rank_;

    const LocalBufView* local_bufs_;        // [n_local_bufs_]
    int                 n_local_bufs_;

    // Monitor-thread IPC ring (host_wait_mode + Pattern C). When
    // ipc_cmd_ring_ != nullptr, device put_no_db's IPC route pushes a
    // command to the ring (atomically incrementing ipc_cmd_head_) and
    // returns. CPU monitor thread polls the head and issues
    // hipMemcpyAsync on Runtime::ipc_stream_. Ring size must be a
    // power of 2; ipc_ring_mask_ = size - 1.
    IpcCmdSlot*         ipc_cmd_ring_;
    volatile uint64_t*  ipc_cmd_head_;
    int                 ipc_ring_mask_;
};

//==============================================================================
// Block-cooperative device-to-device memcpy for IPC fast path.
// Inspired by nvshmemi_memcpy_threadgroup: progressively tries 16B, 8B, 4B,
// 2B, 1B chunks based on src/dst alignment. Each thread in the block takes
// a stride of chunks. Callers MUST invoke from a single block; typical use
// is the same thread block that triggered the kernel's compute+flush.
//==============================================================================
namespace detail {
__device__ __forceinline__
int tid_in_block() {
    return threadIdx.x
         + threadIdx.y * blockDim.x
         + threadIdx.z * blockDim.x * blockDim.y;
}
__device__ __forceinline__
int block_size() {
    return blockDim.x * blockDim.y * blockDim.z;
}
} // namespace detail

__device__ __forceinline__
void memcpy_block(void* __restrict__ dst_v, const void* __restrict__ src_v,
                  uint64_t len)
{
    int tid   = detail::tid_in_block();
    int nth   = detail::block_size();
    char* dst = (char*)dst_v;
    const char* src = (const char*)src_v;

    if (((uintptr_t)dst % 16 == 0) && ((uintptr_t)src % 16 == 0) && len >= 16) {
        uint64_t n = len / 16;
        int4* d = (int4*)dst; const int4* s = (const int4*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 16; dst += n * 16; src += n * 16;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 8 == 0) && ((uintptr_t)src % 8 == 0) && len >= 8) {
        uint64_t n = len / 8;
        uint64_t* d = (uint64_t*)dst; const uint64_t* s = (const uint64_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 8; dst += n * 8; src += n * 8;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 4 == 0) && ((uintptr_t)src % 4 == 0) && len >= 4) {
        uint64_t n = len / 4;
        uint32_t* d = (uint32_t*)dst; const uint32_t* s = (const uint32_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 4; dst += n * 4; src += n * 4;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 2 == 0) && ((uintptr_t)src % 2 == 0) && len >= 2) {
        uint64_t n = len / 2;
        uint16_t* d = (uint16_t*)dst; const uint16_t* s = (const uint16_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 2; dst += n * 2; src += n * 2;
        if (len == 0) return;
    }
    for (uint64_t i = tid; i < len; i += nth) dst[i] = src[i];
}

//==============================================================================
// flush — ring the (virtual) doorbell.
// Single-thread MMIO write. Only thread (0,0,0) of block (0,0,0) ticks
// the trigger counter; the NIC then executes every RMA queued by
// Runtime::put_no_db() since the last reset(). IPC-routed ops are NOT
// flushed here — they were already executed in put_no_db's device-side
// body via direct GPU stores to the peer's IPC-mapped pointer.
//==============================================================================
// User-visible API (flush / quiet / put_no_db / get_no_db): we drop
// __forceinline so the call sites survive AST → IR translation. The
// LTO host/device passes pattern-match on the mangled name and either
// erase the call or replace it with a target-specific lowering. For
// non-LTO (AST-plugin) builds the optimizer's normal inliner still
// inlines the small bodies at -O3, so there's no measurable cost.
__device__ inline
void flush(DeviceCtx* ctx) {
    if (threadIdx.x == 0 && threadIdx.y == 0 && threadIdx.z == 0
        && blockIdx.x == 0 && blockIdx.y == 0 && blockIdx.z == 0) {
        *ctx->trigger_addr_ = ctx->trigger_val_;
        __threadfence_system();
    }
}

//==============================================================================
// quiet — wait for every queued RMA's chained atomic to fire.
// Each thread polls a stride of slots starting at threadIdx.x. With 1 thread
// the polling is sequential. With n_ops_ threads each thread polls one slot.
//==============================================================================
__device__ inline
void quiet(DeviceCtx* ctx) {
    if (ctx->completion_ == nullptr) return;   // overlap pattern, no quiet
    for (uint64_t i = threadIdx.x; i < ctx->n_ops_; i += blockDim.x) {
        while (ctx->completion_[i] < 1) {}
    }
}

//==============================================================================
// put_no_db — kernel-visible RDMA write.
//
// Names a slice of the caller's local buffer (src_buf, src_offset) and a
// slice of the target peer's registered buffer (target_rank, dst_buf,
// dst_offset). Local / remote base addresses + MR keys are looked up via
// ctx tables; the user never threads them.
//
// On OFI the body is one of:
//   * IPC: ctx->ipc_map_[target_rank * max_bufs + dst_buf].mapped_ptr is
//     non-null. Compute (mapped_ptr + dst_offset) and block-cooperative
//     memcpy_block. The op completes in-kernel.
//   * DWQ: the IPC slot is null. The host trace already pre-staged a
//     DwqWorkBuilder; here we do nothing. flush() will ring the trigger
//     and the NIC executes the queued op.
//==============================================================================
__device__ inline
void put_no_db(DeviceCtx* ctx,
               int target_rank,
               int dst_buf, size_t dst_offset,
               int src_buf, size_t src_offset,
               size_t size, bool /*signaled*/ = false)
{
    if (ctx->ipc_map_ == nullptr) return;   // no IPC table; everything is DWQ

    int idx = target_rank * ctx->max_bufs_per_rank_ + dst_buf;
    void* peer_mapped = ctx->ipc_map_[idx].mapped_ptr;
    if (peer_mapped == nullptr) return;     // DWQ route: pre-staged on host

    // Pattern C — push command to host ring, CPU monitor thread will
    // pick it up and dispatch hipMemcpyAsync on the IPC stream.
    // Single-thread atomic claim; only thread (0,0,0) of block (0,0,0)
    // writes the command. Other threads early-return.
    if (ctx->ipc_cmd_ring_ != nullptr) {
        if (threadIdx.x == 0 && threadIdx.y == 0 && threadIdx.z == 0
            && blockIdx.x == 0 && blockIdx.y == 0 && blockIdx.z == 0) {
            uint64_t slot = atomicAdd((unsigned long long*)ctx->ipc_cmd_head_,
                                      1ULL);
            int ring_idx = (int)(slot & (uint64_t)ctx->ipc_ring_mask_);
            void* src_ptr = (char*)ctx->local_bufs_[src_buf].base + src_offset;
            void* dst_ptr = (char*)peer_mapped + dst_offset;
            ctx->ipc_cmd_ring_[ring_idx].dst  = dst_ptr;
            ctx->ipc_cmd_ring_[ring_idx].src  = src_ptr;
            ctx->ipc_cmd_ring_[ring_idx].size = (uint64_t)size;
            __threadfence_system();   // publish to host monitor
        }
        return;
    }

    // Fallback: legacy in-kernel block-cooperative memcpy (slower but
    // self-contained, used when monitor thread / ring isn't set up).

    // IPC route: grid-cooperative GPU memcpy. EVERY thread of EVERY
    // block participates, striped by (gridDim * blockDim). This lets
    // halo-only kernels launched with multi-block grids saturate
    // xGMI bandwidth instead of being limited to one CU. Cross-block
    // ordering relies on the host hipDeviceSynchronize() that follows
    // the kernel; no in-kernel grid sync is required because peer
    // ranks won't read this data until after MPI_Barrier (which
    // implies hipDeviceSynchronize on our side).
    char* dst = (char*)peer_mapped + dst_offset;
    const char* src = (const char*)ctx->local_bufs_[src_buf].base + src_offset;

    int gtid_in_block = threadIdx.x
                      + threadIdx.y * blockDim.x
                      + threadIdx.z * blockDim.x * blockDim.y;
    int block_threads = blockDim.x * blockDim.y * blockDim.z;
    int block_id = blockIdx.x
                 + blockIdx.y * gridDim.x
                 + blockIdx.z * gridDim.x * gridDim.y;
    int total_blocks = gridDim.x * gridDim.y * gridDim.z;
    uint64_t gtid = (uint64_t)block_id * block_threads + gtid_in_block;
    uint64_t gnth = (uint64_t)total_blocks * block_threads;

    if (((uintptr_t)dst % 16 == 0) && ((uintptr_t)src % 16 == 0) && size >= 16) {
        uint64_t n = size / 16;
        int4* d = (int4*)dst; const int4* s = (const int4*)src;
        for (uint64_t i = gtid; i < n; i += gnth) d[i] = s[i];
        size -= n * 16; dst += n * 16; src += n * 16;
        if (size == 0) return;
    }
    if (((uintptr_t)dst % 8 == 0) && ((uintptr_t)src % 8 == 0) && size >= 8) {
        uint64_t n = size / 8;
        uint64_t* d = (uint64_t*)dst; const uint64_t* s = (const uint64_t*)src;
        for (uint64_t i = gtid; i < n; i += gnth) d[i] = s[i];
        size -= n * 8; dst += n * 8; src += n * 8;
        if (size == 0) return;
    }
    if (((uintptr_t)dst % 4 == 0) && ((uintptr_t)src % 4 == 0) && size >= 4) {
        uint64_t n = size / 4;
        uint32_t* d = (uint32_t*)dst; const uint32_t* s = (const uint32_t*)src;
        for (uint64_t i = gtid; i < n; i += gnth) d[i] = s[i];
        size -= n * 4; dst += n * 4; src += n * 4;
        if (size == 0) return;
    }
    for (uint64_t i = gtid; i < size; i += gnth) dst[i] = src[i];
}

//==============================================================================
// get_no_db — kernel-visible RDMA read.
//
// (source_rank, src_buf, src_offset) names a slice of the source peer's
// buffer. (dst_buf, dst_offset) names where to land it locally.
//
// IPC route currently NOT IMPLEMENTED for get; same-node reads still go
// through DWQ. (See unified-compiler-codegen design §12 "Out of Scope".)
// Falls through to no-op so the host-trace DWQ pre-staging takes effect.
//==============================================================================
__device__ inline
void get_no_db(DeviceCtx* /*ctx*/,
               int /*source_rank*/,
               int /*src_buf*/, size_t /*src_offset*/,
               int /*dst_buf*/, size_t /*dst_offset*/,
               size_t /*size*/, bool /*signaled*/ = false) {}

} // namespace gicc
