/**
 * ofi_device.cuh - libfabric/CXI device-side API
 *
 * Mirrors src/gicc/platform/mlx5/mlx5_device.cuh as closely as the hardware
 * model permits. Both backends expose the same kernel-visible primitives:
 *
 *   gicc::put_no_db(ctx, peer, dst_buf, src, lk, ra, rk, sz, signaled=false)
 *   gicc::get_no_db(ctx, peer, src_buf, dst, lk, sa, rk, sz, signaled=false)
 *   gicc::flush(ctx)
 *   gicc::quiet(ctx)
 *
 * The first two args after ctx (peer + buf_idx) are PER-CALL — a single
 * launch can issue puts/gets to multiple peers from the same kernel.
 *
 * --- OFI dispatch ---
 *
 * On OFI, put_no_db's device-side body picks one of two paths based on
 * runtime IPC mapping state (built by Runtime::exchange()):
 *
 *   1. IPC route (peer is on the same node and exposed an IPC handle):
 *      direct GPU stores into the peer's IPC-mapped buffer using
 *      block-cooperative memcpy_block. The "send" completes in-kernel.
 *
 *   2. DWQ route (off-node peer): the device-side put_no_db is a no-op.
 *      The host trace generated by gicc-clang-plugin already pre-staged
 *      this op via Runtime::put_no_db(...) on the host (which queued a
 *      DwqWorkBuilder for libfabric). The kernel only needs flush() to
 *      ring the trigger MMIO so the NIC starts processing the queued ops.
 *
 * Calling contract:
 *   - put_no_db must be called from all threads of block 0. The IPC
 *     branch uses memcpy_block + __syncthreads which deadlocks if not all
 *     block-0 threads enter. (For DWQ-only configs the contract is moot,
 *     but writing kernels to the conservative form is portable across
 *     IPC and non-IPC same-node setups.)
 *   - flush is single-thread (only thread (0,0,0) of block (0,0,0) writes
 *     the trigger MMIO). The IPC route does not pass through flush.
 *   - quiet polls DWQ completion slots cooperatively (any thread of
 *     block 0 can call; loop strides by blockDim.x).
 */
#pragma once

#include <hip/hip_runtime.h>
#include <cstdint>

namespace gicc {

//==============================================================================
// IpcMapEntry — one entry per (peer, dst_buf_idx) populated by Runtime
// after exchange(). When mapped_ptr != nullptr, this peer's buffer is
// reachable via direct GPU stores (IPC fast path); device-side put_no_db
// uses (mapped_ptr + (dst_addr - remote_base)) as the destination.
//==============================================================================
struct IpcMapEntry {
    void*    mapped_ptr;     // peer's GPU buffer mapped into THIS GPU; nullptr if off-node
    uint64_t remote_base;    // peer's registered base addr — for offset computation
};

//==============================================================================
// LocalOp (DEPRECATED) — staged IPC descriptor used by the explicit-form
// rt.put_no_db host path. Kept until all callers (jacobi, etc.) migrate
// to the new device-side put_no_db that does the IPC memcpy itself via
// ipc_map_. New code should not depend on this struct.
//==============================================================================
struct LocalOp {
    void*    dst;
    void*    src;
    uint64_t size;
};

//==============================================================================
// DeviceCtx — GPU-accessible context for the libfabric/CXI backend.
//
// completion_ points to the BASE of an n_ops_-element array of POINTERS,
// one per queued DWQ op. Each pointer references its op's atomic_result
// GPU memory location. quiet() returns once every pointed-to value has
// reached 1.
//
// ipc_map_ / max_bufs_per_rank_ let device put_no_db do (peer, dst_buf) →
// peer-mapped pointer lookup with no host involvement.
//
// local_ops_ / n_local_ops_ are DEPRECATED — used only by the legacy
// explicit-form put_local() path. New unified-form kernels do not touch
// them; the new put_no_db dispatches via ipc_map_ instead.
//==============================================================================
struct DeviceCtx {
    volatile uint64_t* trigger_addr_;       // MMIO trigger counter
    volatile uint64_t* completion_;         // base of n_ops_ × uint64_t poll slots
    uint64_t           trigger_val_;        // value to write to trigger_addr_
    uint64_t           n_ops_;              // number of slots to wait on

    const IpcMapEntry* ipc_map_;            // [n_peers * max_bufs_per_rank_]
    int                max_bufs_per_rank_;  // for indexing

    // DEPRECATED (used only by put_local()):
    LocalOp*           local_ops_;
    uint64_t           n_local_ops_;
};

//==============================================================================
// Block-cooperative device-to-device memcpy for IPC fast path.
// Inspired by nvshmemi_memcpy_threadgroup: progressively tries 16B, 8B, 4B,
// 2B, 1B chunks based on src/dst alignment. Each thread in the block takes
// a stride of chunks. Callers MUST invoke from a single block; typical use
// is the same thread block that triggered the kernel's compute+flush.
//==============================================================================
namespace detail {
__device__ __forceinline__
int tid_in_block() {
    return threadIdx.x
         + threadIdx.y * blockDim.x
         + threadIdx.z * blockDim.x * blockDim.y;
}
__device__ __forceinline__
int block_size() {
    return blockDim.x * blockDim.y * blockDim.z;
}
} // namespace detail

__device__ __forceinline__
void memcpy_block(void* __restrict__ dst_v, const void* __restrict__ src_v,
                  uint64_t len)
{
    int tid   = detail::tid_in_block();
    int nth   = detail::block_size();
    char* dst = (char*)dst_v;
    const char* src = (const char*)src_v;

    if (((uintptr_t)dst % 16 == 0) && ((uintptr_t)src % 16 == 0) && len >= 16) {
        uint64_t n = len / 16;
        int4* d = (int4*)dst; const int4* s = (const int4*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 16; dst += n * 16; src += n * 16;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 8 == 0) && ((uintptr_t)src % 8 == 0) && len >= 8) {
        uint64_t n = len / 8;
        uint64_t* d = (uint64_t*)dst; const uint64_t* s = (const uint64_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 8; dst += n * 8; src += n * 8;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 4 == 0) && ((uintptr_t)src % 4 == 0) && len >= 4) {
        uint64_t n = len / 4;
        uint32_t* d = (uint32_t*)dst; const uint32_t* s = (const uint32_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 4; dst += n * 4; src += n * 4;
        if (len == 0) return;
    }
    if (((uintptr_t)dst % 2 == 0) && ((uintptr_t)src % 2 == 0) && len >= 2) {
        uint64_t n = len / 2;
        uint16_t* d = (uint16_t*)dst; const uint16_t* s = (const uint16_t*)src;
        for (uint64_t i = tid; i < n; i += nth) d[i] = s[i];
        len -= n * 2; dst += n * 2; src += n * 2;
        if (len == 0) return;
    }
    for (uint64_t i = tid; i < len; i += nth) dst[i] = src[i];
}

//==============================================================================
// flush — ring the (virtual) doorbell.
// Single-thread MMIO write. Only thread (0,0,0) of block (0,0,0) ticks
// the trigger counter; the NIC then executes every RMA queued by
// Runtime::put_no_db() since the last reset(). IPC-routed ops are NOT
// flushed here — they were already executed in put_no_db's device-side
// body via direct GPU stores to the peer's IPC-mapped pointer.
//==============================================================================
__device__ __forceinline__
void flush(DeviceCtx* ctx) {
    if (threadIdx.x == 0 && threadIdx.y == 0 && threadIdx.z == 0
        && blockIdx.x == 0 && blockIdx.y == 0 && blockIdx.z == 0) {
        *ctx->trigger_addr_ = ctx->trigger_val_;
        __threadfence_system();
    }
}

//==============================================================================
// quiet — wait for every queued RMA's chained atomic to fire.
// Each thread polls a stride of slots starting at threadIdx.x. With 1 thread
// the polling is sequential. With n_ops_ threads each thread polls one slot.
//==============================================================================
__device__ __forceinline__
void quiet(DeviceCtx* ctx) {
    if (ctx->completion_ == nullptr) return;   // overlap pattern, no quiet
    for (uint64_t i = threadIdx.x; i < ctx->n_ops_; i += blockDim.x) {
        while (ctx->completion_[i] < 1) {}
    }
}

//==============================================================================
// put_no_db — kernel-visible RDMA write entry.
//
// Per-call peer + dst_buf identify the destination rank and remote buffer
// index; src_addr / src_lkey describe the local source region; dst_addr /
// dst_rkey describe the remote address (typically rt.remote_buffer(peer,
// dst_buf).addr + offset).
//
// Two routes inside this body:
//   * IPC: ctx->ipc_map_[peer * max_bufs_per_rank + dst_buf].mapped_ptr is
//     non-null. We compute (mapped_ptr + (dst_addr - remote_base)) and do
//     a block-cooperative memcpy_block. The op completes IN THIS KERNEL.
//   * DWQ: the IPC slot is null. The host trace has already pre-staged a
//     DwqWorkBuilder; here we do nothing. flush() will ring the trigger
//     and the NIC will execute the queued op.
//==============================================================================
__device__ __forceinline__
void put_no_db(DeviceCtx* ctx, int peer, int dst_buf,
               uint64_t src_addr, uint32_t /*src_lkey*/,
               uint64_t dst_addr, uint32_t /*dst_rkey*/,
               uint32_t size, bool /*signaled*/ = false)
{
    if (blockIdx.x != 0 || blockIdx.y != 0 || blockIdx.z != 0) return;
    if (ctx->ipc_map_ == nullptr) return;   // no IPC table built; everything is DWQ

    int idx = peer * ctx->max_bufs_per_rank_ + dst_buf;
    const IpcMapEntry e = ctx->ipc_map_[idx];
    if (e.mapped_ptr == nullptr) return;    // DWQ route: pre-staged on host

    // IPC route: direct GPU memcpy.
    size_t dst_offset = (size_t)(dst_addr - e.remote_base);
    memcpy_block((char*)e.mapped_ptr + dst_offset,
                 (const void*)src_addr, (uint64_t)size);
    __syncthreads();
    if (detail::tid_in_block() == 0) __threadfence_system();
}

//==============================================================================
// get_no_db — kernel-visible RDMA read entry.
//
// Same dispatch model as put_no_db. The "src_buf" / "dst_addr" naming
// reflects that the local buffer is the destination of the read pull.
//
// IPC route currently NOT IMPLEMENTED for get; same-node reads still go
// through DWQ. (See unified-compiler-codegen design §12 "Out of Scope".)
// Falls through to no-op so the host-trace DWQ pre-staging takes effect.
//==============================================================================
__device__ __forceinline__
void get_no_db(DeviceCtx* /*ctx*/, int /*peer*/, int /*src_buf*/,
               uint64_t /*dst_addr*/, uint32_t /*dst_lkey*/,
               uint64_t /*src_addr*/, uint32_t /*src_rkey*/,
               uint32_t /*size*/, bool /*signaled*/ = false) {}

// ============================================================================
// DEPRECATED legacy overloads (no per-call peer / dst_buf).
//
// Kept so explicit-form code paths (jacobi's prepare_trigger pattern, plus
// any user code written against the v1 API) keep compiling during the
// migration. These are no-op stubs on OFI; the actual host-side queueing
// happened via the trace lift OR an explicit rt.put_no_db call. The IPC
// route for these old overloads is handled by the put_local() shim below.
// New code MUST use the per-peer overloads above.
// ============================================================================
__device__ __forceinline__
void put_no_db(DeviceCtx*, uint64_t /*src_addr*/, uint32_t /*src_lkey*/,
               uint64_t /*dst_addr*/, uint32_t /*dst_rkey*/,
               uint32_t /*size*/, bool /*signaled*/ = false) {}

__device__ __forceinline__
void get_no_db(DeviceCtx*, uint64_t /*dst_addr*/, uint32_t /*dst_lkey*/,
               uint64_t /*src_addr*/, uint32_t /*src_rkey*/,
               uint32_t /*size*/, bool /*signaled*/ = false) {}

//==============================================================================
// put_local (DEPRECATED) — execute every IPC copy staged by the
// explicit-form Runtime::put_no_db on the host.
//
// New unified-form kernels do NOT call this; the new device-side put_no_db
// (with per-call peer + dst_buf) executes IPC copies in-place via ipc_map_.
// Retained while jacobi and any external explicit-form code complete the
// migration. Will be removed once they are gone.
//==============================================================================
__device__ __forceinline__
void put_local(DeviceCtx* ctx) {
    if (blockIdx.x != 0 || blockIdx.y != 0 || blockIdx.z != 0) return;
    if (ctx->local_ops_ == nullptr) return;
    for (uint64_t i = 0; i < ctx->n_local_ops_; i++) {
        memcpy_block(ctx->local_ops_[i].dst,
                     ctx->local_ops_[i].src,
                     ctx->local_ops_[i].size);
    }
    __syncthreads();
    if (detail::tid_in_block() == 0) __threadfence_system();
}

} // namespace gicc
