; Generated by gen.sh from Inputs/bad_opaque_call.cpp -- do not edit.
;
; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-chunk-analysis -disable-output %s 2>&1 | %FileCheck %s
;
; // An unknown call in the loop body may write anything.
; #include <cstddef>
; #pragma omp declare target
; extern "C" void ompx_put(int peer, void* dst, const void* src, size_t bytes);
; extern "C" void ompx_pipelined_put(int peer, void* dst, const void* src, size_t bytes);
; extern "C" void opaque(float* p, int i);
; #pragma omp end declare target
;
; void step(float* src, float* dst, int n, int peer, float a) {
;     #pragma omp target teams is_device_ptr(src, dst)
;     {
;         #pragma omp distribute parallel for
;         for (int i = 0; i < n; ++i)
;             opaque(src, i);
;         ompx_pipelined_put(peer, dst, src, n * sizeof(float));
;     }
; }
;
; // CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfS_iif_l{{[0-9]+}}
; // CHECK-NEXT: ompx_pipelined_put: ILLEGAL: call to 'opaque' in the parallel region may write memory

source_filename = "Inputs/bad_opaque_call.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 1, i8 1, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8
@_shared = internal addrspace(3) global [8 x i8] poison, align 16
@_shared1 = internal addrspace(3) global [4 x i8] poison, align 16

; Function Attrs: alwaysinline convergent norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10(ptr noalias noundef %0, i64 noundef %1, ptr noundef %2, i64 noundef %3, ptr noundef %4) local_unnamed_addr #0 {
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  %9 = alloca i32, align 4
  %10 = alloca [4 x ptr], align 8
  %11 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_kernel_environment, ptr %0) #2
  %12 = icmp eq i32 %11, -1
  br i1 %12, label %14, label %13

13:                                               ; preds = %5, %51
  ret void

14:                                               ; preds = %5
  %15 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %10)
  %16 = trunc i64 %1 to i32
  store i32 %16, ptr addrspace(3) @_shared1, align 16, !tbaa !8, !noalias !12
  store ptr %2, ptr addrspace(3) @_shared, align 16, !tbaa !15, !noalias !12
  %17 = icmp sgt i32 %16, 0
  br i1 %17, label %18, label %51

18:                                               ; preds = %14
  %19 = add nsw i32 %16, -1
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %6) #2, !noalias !12
  %20 = addrspacecast ptr %6 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %20, align 4, !tbaa !8, !noalias !12
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %7) #2, !noalias !12
  %21 = addrspacecast ptr %7 to ptr addrspace(5)
  store i32 %19, ptr addrspace(5) %21, align 4, !tbaa !8, !noalias !12
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #2, !noalias !12
  %22 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 1, ptr addrspace(5) %22, align 4, !tbaa !8, !noalias !12
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %9) #2, !noalias !12
  %23 = addrspacecast ptr %9 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %23, align 4, !tbaa !8, !noalias !12
  call void @__kmpc_distribute_static_init_4(ptr nonnull @2, i32 %15, i32 92, ptr nonnull %9, ptr nonnull %6, ptr nonnull %7, ptr nonnull %8, i32 1, i32 1) #2, !noalias !12
  %24 = load i32, ptr addrspace(5) %21, align 4, !tbaa !8, !noalias !12
  %25 = call i32 @llvm.smin.i32(i32 %24, i32 %19)
  store i32 %25, ptr addrspace(5) %21, align 4, !tbaa !8, !noalias !12
  %26 = load i32, ptr addrspace(5) %20, align 4, !tbaa !8, !noalias !12
  %27 = icmp sgt i32 %26, %25
  br i1 %27, label %48, label %28

28:                                               ; preds = %18
  %29 = addrspacecast ptr %10 to ptr addrspace(5)
  %30 = getelementptr inbounds nuw i8, ptr %10, i64 8
  %31 = addrspacecast ptr %30 to ptr addrspace(5)
  %32 = getelementptr inbounds nuw i8, ptr %10, i64 16
  %33 = addrspacecast ptr %32 to ptr addrspace(5)
  %34 = getelementptr inbounds nuw i8, ptr %10, i64 24
  %35 = addrspacecast ptr %34 to ptr addrspace(5)
  br label %36

36:                                               ; preds = %28, %36
  %37 = phi i32 [ %25, %28 ], [ %46, %36 ]
  %38 = phi i32 [ %26, %28 ], [ %45, %36 ]
  %39 = load i32, ptr addrspace(5) %20, align 4, !noalias !12
  %40 = zext i32 %39 to i64
  %41 = zext i32 %37 to i64
  %42 = inttoptr i64 %40 to ptr
  store ptr %42, ptr addrspace(5) %29, align 8, !tbaa !18, !noalias !12
  %43 = inttoptr i64 %41 to ptr
  store ptr %43, ptr addrspace(5) %31, align 8, !tbaa !18, !noalias !12
  store ptr addrspacecast (ptr addrspace(3) @_shared1 to ptr), ptr addrspace(5) %33, align 8, !tbaa !18, !noalias !12
  store ptr addrspacecast (ptr addrspace(3) @_shared to ptr), ptr addrspace(5) %35, align 8, !tbaa !18, !noalias !12
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %15, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined, ptr nonnull @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined_wrapper, ptr nonnull %10, i64 4) #2, !noalias !12
  %44 = load i32, ptr addrspace(5) %22, align 4, !tbaa !8, !noalias !12
  %45 = add nsw i32 %44, %38
  %46 = load i32, ptr addrspace(5) %21, align 4, !tbaa !8, !noalias !12
  %47 = icmp sgt i32 %45, %46
  br i1 %47, label %48, label %36

48:                                               ; preds = %36, %18
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %15) #2, !noalias !12
  %49 = load ptr, ptr addrspace(3) @_shared, align 16, !tbaa !15, !noalias !12
  %50 = load i32, ptr addrspace(3) @_shared1, align 16, !tbaa !8, !noalias !12
  br label %51

51:                                               ; preds = %14, %48
  %52 = phi i32 [ %16, %14 ], [ %50, %48 ]
  %53 = phi ptr [ %2, %14 ], [ %49, %48 ]
  %54 = trunc i64 %3 to i32
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %9) #2, !noalias !12
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !12
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %7) #2, !noalias !12
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %6) #2, !noalias !12
  %55 = sext i32 %52 to i64
  %56 = shl nsw i64 %55, 2
  call void @ompx_pipelined_put(i32 noundef %54, ptr noundef %4, ptr noundef %53, i64 noundef %56) #8, !noalias !12
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %10)
  call void @__kmpc_target_deinit() #2
  br label %13
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined(ptr noalias noundef readonly nocapture %0, ptr noalias readnone nocapture %1, i64 noundef %2, i64 noundef %3, ptr noundef nonnull readonly align 4 nocapture dereferenceable(4) %4, ptr noundef nonnull readonly align 8 nocapture dereferenceable(8) %5) #3 {
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  %9 = alloca i32, align 4
  %10 = alloca i32, align 4
  %11 = load i32, ptr %4, align 4, !tbaa !8
  %12 = icmp sgt i32 %11, 0
  br i1 %12, label %13, label %32

13:                                               ; preds = %6
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %7) #9
  %14 = addrspacecast ptr %7 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #9
  %15 = addrspacecast ptr %8 to ptr addrspace(5)
  %16 = trunc i64 %2 to i32
  %17 = trunc i64 %3 to i32
  store i32 %16, ptr addrspace(5) %14, align 4, !tbaa !8
  store i32 %17, ptr addrspace(5) %15, align 4, !tbaa !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %9) #9
  %18 = addrspacecast ptr %9 to ptr addrspace(5)
  store i32 1, ptr addrspace(5) %18, align 4, !tbaa !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %10) #9
  %19 = addrspacecast ptr %10 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %19, align 4, !tbaa !8
  %20 = load i32, ptr %0, align 4, !tbaa !8
  call void @__kmpc_for_static_init_4(ptr nonnull @3, i32 %20, i32 33, ptr nonnull %10, ptr nonnull %7, ptr nonnull %8, ptr nonnull %9, i32 1, i32 1) #2
  %21 = load i32, ptr addrspace(5) %14, align 4, !tbaa !8
  %22 = sext i32 %21 to i64
  %23 = icmp ult i64 %3, %22
  br i1 %23, label %31, label %24

24:                                               ; preds = %13, %24
  %25 = phi i32 [ %28, %24 ], [ %21, %13 ]
  %26 = load ptr, ptr %5, align 8, !tbaa !15
  call void @opaque(ptr noundef %26, i32 noundef %25) #8
  %27 = load i32, ptr addrspace(5) %18, align 4, !tbaa !8
  %28 = add nsw i32 %27, %25
  %29 = sext i32 %28 to i64
  %30 = icmp ult i64 %3, %29
  br i1 %30, label %31, label %24

31:                                               ; preds = %24, %13
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %20) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %7) #2
  br label %32

32:                                               ; preds = %31, %6
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: convergent
declare void @opaque(ptr noundef, i32 noundef) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined_wrapper(i16 zeroext %0, i32 noundef %1) #5 {
  %3 = alloca i32, align 4
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  %6 = alloca i32, align 4
  %7 = alloca ptr, align 8
  call void @__kmpc_get_shared_variables(ptr nonnull %7) #2
  %8 = addrspacecast ptr %7 to ptr addrspace(5)
  %9 = load ptr, ptr addrspace(5) %8, align 8
  %10 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %11 = load i64, ptr %10, align 8, !tbaa !20
  %12 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %13 = load ptr, ptr %12, align 8, !tbaa !22
  %14 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %15 = load ptr, ptr %14, align 8, !tbaa !22
  %16 = load i32, ptr %13, align 4, !tbaa !8, !noalias !23
  %17 = icmp sgt i32 %16, 0
  br i1 %17, label %18, label %37

18:                                               ; preds = %2
  %19 = load i64, ptr %9, align 8, !tbaa !20
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %3) #9, !noalias !23
  %20 = addrspacecast ptr %3 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %4) #9, !noalias !23
  %21 = addrspacecast ptr %4 to ptr addrspace(5)
  %22 = trunc i64 %19 to i32
  %23 = trunc i64 %11 to i32
  store i32 %22, ptr addrspace(5) %20, align 4, !tbaa !8, !noalias !23
  store i32 %23, ptr addrspace(5) %21, align 4, !tbaa !8, !noalias !23
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %5) #9, !noalias !23
  %24 = addrspacecast ptr %5 to ptr addrspace(5)
  store i32 1, ptr addrspace(5) %24, align 4, !tbaa !8, !noalias !23
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %6) #9, !noalias !23
  %25 = addrspacecast ptr %6 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %25, align 4, !tbaa !8, !noalias !23
  call void @__kmpc_for_static_init_4(ptr nonnull @3, i32 %1, i32 33, ptr nonnull %6, ptr nonnull %3, ptr nonnull %4, ptr nonnull %5, i32 1, i32 1) #2, !noalias !23
  %26 = load i32, ptr addrspace(5) %20, align 4, !tbaa !8, !noalias !23
  %27 = sext i32 %26 to i64
  %28 = icmp ult i64 %11, %27
  br i1 %28, label %36, label %29

29:                                               ; preds = %18, %29
  %30 = phi i32 [ %33, %29 ], [ %26, %18 ]
  %31 = load ptr, ptr %15, align 8, !tbaa !15, !noalias !23
  call void @opaque(ptr noundef %31, i32 noundef %30) #8, !noalias !23
  %32 = load i32, ptr addrspace(5) %24, align 4, !tbaa !8, !noalias !23
  %33 = add nsw i32 %32, %30
  %34 = sext i32 %33 to i64
  %35 = icmp ult i64 %11, %34
  br i1 %35, label %36, label %29

36:                                               ; preds = %29, %18
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %1) #2, !noalias !23
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %6) #2, !noalias !23
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %5) #2, !noalias !23
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %4) #2, !noalias !23
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %3) #2, !noalias !23
  br label %37

37:                                               ; preds = %2, %36
  ret void
}

declare void @__kmpc_get_shared_variables(ptr) local_unnamed_addr

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #6

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) local_unnamed_addr #4

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #7

attributes #0 = { alwaysinline convergent norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { convergent "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #5 = { convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #6 = { alwaysinline }
attributes #7 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #8 = { convergent nounwind }
attributes #9 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526711067, !"_Z4stepPfS_iif", i32 10, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9, !9, i64 0}
!9 = !{!"int", !10, i64 0}
!10 = !{!"omnipotent char", !11, i64 0}
!11 = !{!"Simple C++ TBAA"}
!12 = !{!13}
!13 = distinct !{!13, !14, !"__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined: argument 0"}
!14 = distinct !{!14, !"__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined"}
!15 = !{!16, !16, i64 0}
!16 = !{!"p1 float", !17, i64 0}
!17 = !{!"any pointer", !10, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"any p2 pointer", !17, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"p1 long", !17, i64 0}
!22 = !{!17, !17, i64 0}
!23 = !{!24}
!24 = distinct !{!24, !25, !"__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined: argument 0"}
!25 = distinct !{!25, !"__omp_offloading_6bc59cba_a5003ce5__Z4stepPfS_iif_l10_omp_outlined_omp_outlined"}
