#!/usr/bin/env bash
# Regenerate the chunk-analysis lit tests from Inputs/*.cpp.
#
# Each Inputs/<case>.cpp is compiled to NVPTX OpenMP device IR; <case>.ll
# is the RUN lines, the source as comments (its CHECK lines included), and
# the IR. Two more tests are mutations of legal_static's IR that clang
# never emits but the analysis must still reject.
#
# Usage: LLVM=<llvm prefix with NVPTX offload> ./gen.sh
set -euo pipefail
cd "$(dirname "$0")"
LLVM=${LLVM:-/projects/bfyi/lwshanbd/llvm-omp}

RUN='; RUN: env GICC_MODE=chunk-analyze %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-chunk-analysis -disable-output %s 2>&1 | %FileCheck %s'

device_ir() {
    "$LLVM/bin/clang++" -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda \
        --offload-arch=sm_90 --offload-device-only -S -emit-llvm -O2 \
        "$1" -o - | grep -v '^; ModuleID'
}

emit() {   # out.ll, header comment, source file, ir
    {
        echo "$2"
        echo ";"
        echo "$RUN"
        echo ";"
        sed 's/^/; /; s/ *$//' "$3"
        echo
        echo "$4"
    } > "$1"
}

for src in Inputs/*.cpp; do
    name=$(basename "$src" .cpp)
    emit "$name.ll" "; Generated by gen.sh from Inputs/$name.cpp -- do not edit." \
         "$src" "$(device_ir "$src")"
done

# Mutations of legal_static's outlined worksharing loop. Each must be
# rejected; clang does not produce these shapes, so only a hand-edited
# loop exercises the exit-condition and entry-guard checks.
base=$(device_ir Inputs/legal_static.cpp)
mutate() {   # name, sed expression, what it breaks, expected CHECK line
    local ir
    ir=$(sed "$2" <<<"$base")
    [ "$ir" != "$base" ] || { echo "gen.sh: mutation $1 did not apply" >&2; exit 1; }
    local hdr="; Generated by gen.sh: Inputs/legal_static.cpp with $3 -- do not edit.
;
; CHECK: [gicc-chunk] kernel __omp_offloading_{{.*}}_Z4stepPfS_iif_l{{[0-9]+}}
; CHECK-NEXT: $4"
    {
        echo "$hdr"
        echo ";"
        echo "$RUN"
        echo
        echo "$ir"
    } > "$1.ll"
}
# Exit when UB <= i.next: the last iteration i == UB is skipped.
mutate mut_exit_skips_ub 's/icmp ult i64 %3, %36/icmp ule i64 %3, %36/' \
    "the latch exit changed from 'UB < i.next' to 'UB <= i.next'" \
    "ompx_pipelined_put: ILLEGAL: loop exit is not 'continue while i <= UB'"
# No entry guard: a thread whose lb > UB still runs one iteration.
mutate mut_no_entry_guard 's/br i1 %24, label %38, label %25/br label %25/' \
    "the 'lb > UB' entry guard removed" \
    "ompx_pipelined_put: ILLEGAL: first iteration is not guarded by lb <= UB"

# Block-grain lowering: each LEGAL put becomes one ompx__block_put right
# after the block's __kmpc_parallel_51, and the marker is gone.
lower_test() {   # name, input
    local ir
    ir=$(device_ir "Inputs/$2.cpp")
    {
        echo "; Generated by gen.sh: Inputs/$2.cpp lowered in GICC_MODE=chunk-lower -- do not edit."
        echo ";"
        echo "; RUN: env GICC_MODE=chunk-lower GICC_CHUNK_GRAIN=block %opt -load-pass-plugin=%gicc_passes_so \\"
        echo "; RUN:   -passes=gicc-chunk-analysis -S %s 2>/dev/null | %FileCheck %s"
        echo ";"
        echo "; CHECK-LABEL: define {{.*}} @__omp_offloading_"
        echo "; CHECK: call void @__kmpc_distribute_static_init"
        echo "; CHECK: call void @__kmpc_parallel_51("
        echo "; CHECK-NEXT: [[LB:%.*]] = {{sext|zext}} i{{32|64}} {{%.*}} to i64"
        echo "; CHECK: call void @ompx__block_put(i32 {{%.*}}, ptr {{%.*}}, ptr {{%.*}}, i64 {{%.*}})"
        echo "; CHECK: call void @__kmpc_distribute_static_fini"
        echo "; CHECK-NOT: ompx_pipelined_put"
        echo "; CHECK-LABEL: define internal void @__omp_offloading_"
        echo
        echo "$ir"
    } > "lower_$1.ll"
}
lower_test static legal_static
lower_test dist_chunked legal_dist_chunked

# Lowering through the whole -O3 pipeline, from IR straight out of clang:
# GICCChunkPrepPass keeps the outlined region out of its wrapper, the
# lowering rewrites the put, and the region is alwaysinline again after.
unoptimized_ir() {
    "$LLVM/bin/clang++" -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda \
        --offload-arch=sm_90 --offload-device-only -S -emit-llvm -O3 \
        -Xclang -disable-llvm-passes "$1" -o - | grep -v '^; ModuleID'
}
lower_o3_test() {   # name, input, what it checks, CHECK lines (one per line)
    local ir
    ir=$(unoptimized_ir "Inputs/$2.cpp")
    {
        echo "; Generated by gen.sh: Inputs/$2.cpp before any optimization,"
        echo "; lowered at element grain through default<O3> -- $3. Do not edit."
        echo ";"
        echo "; RUN: env GICC_MODE=chunk-lower GICC_CHUNK_GRAIN=element %opt -load-pass-plugin=%gicc_passes_so \\"
        echo "; RUN:   -passes='default<O3>' -S %s 2>&1 | %FileCheck %s"
        echo ";"
        sed 's/^/; /' <<<"$4"
        echo
        echo "$ir"
    } > "lower_$1.ll"
}

lower_o3_test element legal_size_t_inner_loop \
    "the store is mirrored, with the per-block fallback" \
"CHECK: lowered: element grain
The kernel computes the peer address once and hands it to the region.
CHECK-LABEL: define {{.*}} @__omp_offloading_
CHECK: [[PD:%.*]] = {{.*}}call {{.*}}ptr @ompx__peer_addr(
CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.chunk.delta
CHECK: store i8 {{%.*}}, ptr addrspace(3) @gicc.chunk.mirror
CHECK: call void @__kmpc_distribute_static_init
CHECK: call void @__kmpc_parallel_51(
Fallback only when the peer is not mapped.
CHECK: br i1 {{%.*}}, label {{%.*}}, label {{%.*}}
CHECK: call void @ompx__block_put_one(
CHECK-NOT: ompx_pipelined_put
The worksharing loop stores every word locally and to the peer.
CHECK-LABEL: define internal void @__omp_offloading_{{.*}}_omp_outlined_omp_outlined(
CHECK: load i64, ptr addrspace(3) @gicc.chunk.delta
CHECK: store i32 [[V:%.*]], ptr [[P:%.*]], align 4
CHECK-NEXT: [[R:%.*]] = getelementptr i8, ptr [[P]], i64 {{%.*}}
CHECK-NEXT: [[T:%.*]] = select i1 {{%.*}}, ptr [[R]], ptr [[P]]
CHECK-NEXT: store i32 [[V]], ptr [[T]], align 4
And it is alwaysinline again, with the prep marker gone.
CHECK-NOT: gicc-chunk-noinline"

lower_o3_test conditional_write legal_conditional_write \
    "only some words are stored, so it falls back to block grain" \
"CHECK: no write covers the range on every iteration
CHECK: lowered: block grain
CHECK-LABEL: define {{.*}} @__omp_offloading_
CHECK-NOT: ompx__peer_addr
CHECK: call void @ompx__block_put(
CHECK-NOT: ompx_pipelined_put"

lower_o3_test two_puts legal_two_puts \
    "two plans, split only after both are expanded" \
"CHECK-COUNT-2: lowered: element grain
CHECK-LABEL: define {{.*}} @__omp_offloading_
CHECK-COUNT-2: call {{.*}}ptr @ompx__peer_addr(
CHECK: call void @__kmpc_parallel_51(
CHECK-COUNT-2: call void @ompx__block_put_one(
CHECK-NOT: ompx_pipelined_put"
