; Generated by gen.sh: Inputs/legal_conditional_write.cpp before any optimization,
; lowered at element grain through default<O3> -- only some words are stored, so it falls back to block grain. Do not edit.
;
; RUN: env GICC_MODE=chunk-lower GICC_CHUNK_GRAIN=element %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes='default<O3>' -S %s 2>&1 | %FileCheck %s
;
; CHECK: no write covers the range on every iteration
; CHECK: lowered: block grain
; CHECK-LABEL: define {{.*}} @__omp_offloading_
; CHECK-NOT: ompx__peer_addr
; CHECK: call void @ompx__block_put(
; CHECK-NOT: ompx_pipelined_put

source_filename = "Inputs/legal_conditional_write.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 1, i8 1, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline convergent mustprogress norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9(ptr noalias noundef %0, i64 noundef %1, ptr noundef %2, ptr noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef %6) #0 {
  %8 = alloca ptr, align 8
  %9 = alloca i64, align 8
  %10 = alloca ptr, align 8
  %11 = alloca ptr, align 8
  %12 = alloca i64, align 8
  %13 = alloca i64, align 8
  %14 = alloca ptr, align 8
  %15 = alloca i64, align 8
  %16 = alloca i64, align 8
  %17 = alloca i64, align 8
  %18 = alloca i32, align 4
  %19 = alloca i32, align 4
  store ptr %0, ptr %8, align 8, !tbaa !8
  store i64 %1, ptr %9, align 8, !tbaa !12
  store ptr %2, ptr %10, align 8, !tbaa !14
  store ptr %3, ptr %11, align 8, !tbaa !16
  store i64 %4, ptr %12, align 8, !tbaa !12
  store i64 %5, ptr %13, align 8, !tbaa !12
  store ptr %6, ptr %14, align 8, !tbaa !16
  %20 = call i32 @__kmpc_target_init(ptr @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_kernel_environment, ptr %0)
  %21 = icmp eq i32 %20, -1
  br i1 %21, label %22, label %33

22:                                               ; preds = %7
  %23 = call i32 @__kmpc_global_thread_num(ptr @1)
  %24 = load i32, ptr %9, align 4, !tbaa !18
  store i32 %24, ptr %15, align 4, !tbaa !18
  %25 = load i64, ptr %15, align 8, !tbaa !12
  %26 = load ptr, ptr %10, align 8, !tbaa !14
  %27 = load ptr, ptr %11, align 8, !tbaa !16
  %28 = load float, ptr %12, align 4, !tbaa !20
  store float %28, ptr %16, align 4, !tbaa !20
  %29 = load i64, ptr %16, align 8, !tbaa !12
  %30 = load i32, ptr %13, align 4, !tbaa !18
  store i32 %30, ptr %17, align 4, !tbaa !18
  %31 = load i64, ptr %17, align 8, !tbaa !12
  %32 = load ptr, ptr %14, align 8, !tbaa !16
  store i32 0, ptr %18, align 4
  store i32 %23, ptr %19, align 4, !tbaa !18
  call void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined(ptr %19, ptr %18, i64 %25, ptr %26, ptr %27, i64 %29, i64 %31, ptr %32) #4
  call void @__kmpc_target_deinit()
  ret void

33:                                               ; preds = %7
  ret void
}

declare i32 @__kmpc_target_init(ptr, ptr)

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, ptr noundef %3, ptr noundef %4, i64 noundef %5, i64 noundef %6, ptr noundef %7) #1 {
  %9 = alloca ptr, align 8
  %10 = alloca ptr, align 8
  %11 = alloca i64, align 8
  %12 = alloca ptr, align 8
  %13 = alloca ptr, align 8
  %14 = alloca i64, align 8
  %15 = alloca i64, align 8
  %16 = alloca ptr, align 8
  %17 = alloca i32, align 4
  %18 = alloca i32, align 4
  %19 = alloca i32, align 4
  %20 = alloca i32, align 4
  %21 = alloca i32, align 4
  %22 = alloca i32, align 4
  %23 = alloca i32, align 4
  %24 = alloca i32, align 4
  %25 = alloca i32, align 4
  %26 = alloca i32, align 4
  %27 = alloca [6 x ptr], align 8
  store ptr %0, ptr %9, align 8, !tbaa !14
  store ptr %1, ptr %10, align 8, !tbaa !14
  store i64 %2, ptr %11, align 8, !tbaa !12
  store ptr %3, ptr %12, align 8, !tbaa !14
  store ptr %4, ptr %13, align 8, !tbaa !16
  store i64 %5, ptr %14, align 8, !tbaa !12
  store i64 %6, ptr %15, align 8, !tbaa !12
  store ptr %7, ptr %16, align 8, !tbaa !16
  %28 = load i32, ptr %11, align 4, !tbaa !18
  %29 = call align 16 ptr @__kmpc_alloc_shared(i64 4)
  store i32 %28, ptr %29, align 4, !tbaa !18
  %30 = load ptr, ptr %12, align 8, !tbaa !14
  %31 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store ptr %30, ptr %31, align 8, !tbaa !14
  %32 = load ptr, ptr %13, align 8, !tbaa !16
  %33 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store ptr %32, ptr %33, align 8, !tbaa !16
  %34 = load float, ptr %14, align 4, !tbaa !20
  %35 = call align 16 ptr @__kmpc_alloc_shared(i64 4)
  store float %34, ptr %35, align 4, !tbaa !20
  call void @llvm.lifetime.start.p0(i64 4, ptr %17) #4
  call void @llvm.lifetime.start.p0(i64 4, ptr %19) #4
  %36 = load i32, ptr %29, align 4, !tbaa !18
  store i32 %36, ptr %19, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %20) #4
  %37 = load i32, ptr %19, align 4, !tbaa !18
  %38 = sub nsw i32 %37, 0
  %39 = sdiv i32 %38, 1
  %40 = sub nsw i32 %39, 1
  store i32 %40, ptr %20, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %21) #4
  store i32 0, ptr %21, align 4, !tbaa !18
  call void @llvm.lifetime.end.p0(i64 4, ptr %21) #4
  %41 = load i32, ptr %19, align 4, !tbaa !18
  %42 = icmp slt i32 0, %41
  br i1 %42, label %43, label %85

43:                                               ; preds = %8
  call void @llvm.lifetime.start.p0(i64 4, ptr %22) #4
  store i32 0, ptr %22, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %23) #4
  %44 = load i32, ptr %20, align 4, !tbaa !18
  store i32 %44, ptr %23, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %24) #4
  store i32 1, ptr %24, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %25) #4
  store i32 0, ptr %25, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %26) #4
  %45 = load ptr, ptr %9, align 8
  %46 = load i32, ptr %45, align 4, !tbaa !18
  call void @__kmpc_distribute_static_init_4(ptr @2, i32 %46, i32 92, ptr %25, ptr %22, ptr %23, ptr %24, i32 1, i32 1)
  %47 = load i32, ptr %23, align 4, !tbaa !18
  %48 = load i32, ptr %20, align 4, !tbaa !18
  %49 = icmp sgt i32 %47, %48
  br i1 %49, label %50, label %52

50:                                               ; preds = %43
  %51 = load i32, ptr %20, align 4, !tbaa !18
  br label %54

52:                                               ; preds = %43
  %53 = load i32, ptr %23, align 4, !tbaa !18
  br label %54

54:                                               ; preds = %52, %50
  %55 = phi i32 [ %51, %50 ], [ %53, %52 ]
  store i32 %55, ptr %23, align 4, !tbaa !18
  %56 = load i32, ptr %22, align 4, !tbaa !18
  store i32 %56, ptr %17, align 4, !tbaa !18
  br label %57

57:                                               ; preds = %77, %54
  %58 = load i32, ptr %17, align 4, !tbaa !18
  %59 = load i32, ptr %23, align 4, !tbaa !18
  %60 = icmp sle i32 %58, %59
  br i1 %60, label %62, label %61

61:                                               ; preds = %57
  br label %81

62:                                               ; preds = %57
  %63 = load i32, ptr %22, align 4
  %64 = zext i32 %63 to i64
  %65 = load i32, ptr %23, align 4
  %66 = zext i32 %65 to i64
  %67 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 0
  %68 = inttoptr i64 %64 to ptr
  store ptr %68, ptr %67, align 8, !tbaa !22
  %69 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 1
  %70 = inttoptr i64 %66 to ptr
  store ptr %70, ptr %69, align 8, !tbaa !22
  %71 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 2
  store ptr %29, ptr %71, align 8, !tbaa !22
  %72 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 3
  store ptr %31, ptr %72, align 8, !tbaa !22
  %73 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 4
  store ptr %33, ptr %73, align 8, !tbaa !22
  %74 = getelementptr inbounds [6 x ptr], ptr %27, i64 0, i64 5
  store ptr %35, ptr %74, align 8, !tbaa !22
  %75 = load ptr, ptr %9, align 8
  %76 = load i32, ptr %75, align 4, !tbaa !18
  call void @__kmpc_parallel_51(ptr @1, i32 %76, i32 1, i32 -1, i32 -1, ptr @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined_omp_outlined, ptr @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined_omp_outlined_wrapper, ptr %27, i64 6)
  br label %77

77:                                               ; preds = %62
  %78 = load i32, ptr %17, align 4, !tbaa !18
  %79 = load i32, ptr %24, align 4, !tbaa !18
  %80 = add nsw i32 %78, %79
  store i32 %80, ptr %17, align 4, !tbaa !18
  br label %57

81:                                               ; preds = %61
  br label %82

82:                                               ; preds = %81
  %83 = load ptr, ptr %9, align 8
  %84 = load i32, ptr %83, align 4, !tbaa !18
  call void @__kmpc_distribute_static_fini(ptr @2, i32 %84)
  call void @llvm.lifetime.end.p0(i64 4, ptr %26) #4
  br label %85

85:                                               ; preds = %82, %8
  call void @llvm.lifetime.end.p0(i64 4, ptr %25) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %24) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %23) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %22) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %20) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %19) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %17) #4
  %86 = load i32, ptr %15, align 4, !tbaa !18
  %87 = load ptr, ptr %16, align 8, !tbaa !16
  %88 = load ptr, ptr %33, align 8, !tbaa !16
  %89 = load i32, ptr %29, align 4, !tbaa !18
  %90 = sext i32 %89 to i64
  %91 = mul i64 %90, 4
  call void @ompx_pipelined_put(i32 noundef %86, ptr noundef %87, ptr noundef %88, i64 noundef %91) #9
  call void @__kmpc_free_shared(ptr %35, i64 4)
  call void @__kmpc_free_shared(ptr %33, i64 8)
  call void @__kmpc_free_shared(ptr %31, i64 8)
  call void @__kmpc_free_shared(ptr %29, i64 4)
  ret void
}

; Function Attrs: nosync nounwind allocsize(0)
declare noalias ptr @__kmpc_alloc_shared(i64) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #3

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) #4

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, ptr noundef nonnull align 4 dereferenceable(4) %4, ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 8 dereferenceable(8) %6, ptr noundef nonnull align 4 dereferenceable(4) %7) #1 {
  %9 = alloca ptr, align 8
  %10 = alloca ptr, align 8
  %11 = alloca i64, align 8
  %12 = alloca i64, align 8
  %13 = alloca ptr, align 8
  %14 = alloca ptr, align 8
  %15 = alloca ptr, align 8
  %16 = alloca ptr, align 8
  %17 = alloca i32, align 4
  %18 = alloca i32, align 4
  %19 = alloca i32, align 4
  %20 = alloca i32, align 4
  %21 = alloca i32, align 4
  %22 = alloca i32, align 4
  %23 = alloca i32, align 4
  %24 = alloca i32, align 4
  %25 = alloca i32, align 4
  %26 = alloca i32, align 4
  store ptr %0, ptr %9, align 8, !tbaa !14
  store ptr %1, ptr %10, align 8, !tbaa !14
  store i64 %2, ptr %11, align 8, !tbaa !12
  store i64 %3, ptr %12, align 8, !tbaa !12
  store ptr %4, ptr %13, align 8, !tbaa !14
  store ptr %5, ptr %14, align 8, !tbaa !24
  store ptr %6, ptr %15, align 8, !tbaa !26
  store ptr %7, ptr %16, align 8, !tbaa !16
  %27 = load ptr, ptr %13, align 8, !tbaa !14, !nonnull !28, !align !29
  %28 = load ptr, ptr %14, align 8, !tbaa !24, !nonnull !28, !align !30
  %29 = load ptr, ptr %15, align 8, !tbaa !26, !nonnull !28, !align !30
  %30 = load ptr, ptr %16, align 8, !tbaa !16, !nonnull !28, !align !29
  call void @llvm.lifetime.start.p0(i64 4, ptr %17) #4
  call void @llvm.lifetime.start.p0(i64 4, ptr %19) #4
  %31 = load i32, ptr %27, align 4, !tbaa !18
  store i32 %31, ptr %19, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %20) #4
  %32 = load i32, ptr %19, align 4, !tbaa !18
  %33 = sub nsw i32 %32, 0
  %34 = sdiv i32 %33, 1
  %35 = sub nsw i32 %34, 1
  store i32 %35, ptr %20, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %21) #4
  store i32 0, ptr %21, align 4, !tbaa !18
  call void @llvm.lifetime.end.p0(i64 4, ptr %21) #4
  %36 = load i32, ptr %19, align 4, !tbaa !18
  %37 = icmp slt i32 0, %36
  br i1 %37, label %38, label %82

38:                                               ; preds = %8
  call void @llvm.lifetime.start.p0(i64 4, ptr %22) #4
  store i32 0, ptr %22, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %23) #4
  %39 = load i32, ptr %20, align 4, !tbaa !18
  store i32 %39, ptr %23, align 4, !tbaa !18
  %40 = load i64, ptr %11, align 8, !tbaa !12
  %41 = trunc i64 %40 to i32
  %42 = load i64, ptr %12, align 8, !tbaa !12
  %43 = trunc i64 %42 to i32
  store i32 %41, ptr %22, align 4, !tbaa !18
  store i32 %43, ptr %23, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %24) #4
  store i32 1, ptr %24, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %25) #4
  store i32 0, ptr %25, align 4, !tbaa !18
  call void @llvm.lifetime.start.p0(i64 4, ptr %26) #4
  %44 = load ptr, ptr %9, align 8
  %45 = load i32, ptr %44, align 4, !tbaa !18
  call void @__kmpc_for_static_init_4(ptr @3, i32 %45, i32 33, ptr %25, ptr %22, ptr %23, ptr %24, i32 1, i32 1)
  %46 = load i32, ptr %22, align 4, !tbaa !18
  store i32 %46, ptr %17, align 4, !tbaa !18
  br label %47

47:                                               ; preds = %74, %38
  %48 = load i32, ptr %17, align 4, !tbaa !18
  %49 = sext i32 %48 to i64
  %50 = load i64, ptr %12, align 8, !tbaa !12
  %51 = icmp ule i64 %49, %50
  br i1 %51, label %53, label %52

52:                                               ; preds = %47
  br label %78

53:                                               ; preds = %47
  %54 = load i32, ptr %17, align 4, !tbaa !18
  %55 = mul nsw i32 %54, 1
  %56 = add nsw i32 0, %55
  store i32 %56, ptr %26, align 4, !tbaa !18
  %57 = load ptr, ptr %28, align 8, !tbaa !14
  %58 = load i32, ptr %26, align 4, !tbaa !18
  %59 = sext i32 %58 to i64
  %60 = getelementptr inbounds i32, ptr %57, i64 %59
  %61 = load i32, ptr %60, align 4, !tbaa !18
  %62 = icmp ne i32 %61, 0
  br i1 %62, label %63, label %72

63:                                               ; preds = %53
  %64 = load float, ptr %30, align 4, !tbaa !20
  %65 = load i32, ptr %26, align 4, !tbaa !18
  %66 = sitofp i32 %65 to float
  %67 = fmul float %64, %66
  %68 = load ptr, ptr %29, align 8, !tbaa !16
  %69 = load i32, ptr %26, align 4, !tbaa !18
  %70 = sext i32 %69 to i64
  %71 = getelementptr inbounds float, ptr %68, i64 %70
  store float %67, ptr %71, align 4, !tbaa !20
  br label %72

72:                                               ; preds = %63, %53
  br label %73

73:                                               ; preds = %72
  br label %74

74:                                               ; preds = %73
  %75 = load i32, ptr %17, align 4, !tbaa !18
  %76 = load i32, ptr %24, align 4, !tbaa !18
  %77 = add nsw i32 %75, %76
  store i32 %77, ptr %17, align 4, !tbaa !18
  br label %47

78:                                               ; preds = %52
  br label %79

79:                                               ; preds = %78
  %80 = load ptr, ptr %9, align 8
  %81 = load i32, ptr %80, align 4, !tbaa !18
  call void @__kmpc_for_static_fini(ptr @3, i32 %81)
  call void @llvm.lifetime.end.p0(i64 4, ptr %26) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %25) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %24) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %23) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %22) #4
  br label %82

82:                                               ; preds = %79, %8
  call void @llvm.lifetime.end.p0(i64 4, ptr %20) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %19) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %17) #4
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) #4

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) #4

; Function Attrs: convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined_omp_outlined_wrapper(i16 noundef zeroext %0, i32 noundef %1) #5 {
  %3 = alloca i16, align 2
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  %6 = alloca ptr, align 8
  store i16 %0, ptr %3, align 2, !tbaa !31
  store i32 %1, ptr %4, align 4, !tbaa !18
  store i32 0, ptr %5, align 4
  call void @__kmpc_get_shared_variables(ptr %6)
  %7 = load ptr, ptr %6, align 8
  %8 = getelementptr inbounds ptr, ptr %7, i64 0
  %9 = load i64, ptr %8, align 8, !tbaa !33
  %10 = getelementptr inbounds ptr, ptr %7, i64 1
  %11 = load i64, ptr %10, align 8, !tbaa !33
  %12 = getelementptr inbounds ptr, ptr %7, i64 2
  %13 = load ptr, ptr %12, align 8, !tbaa !8
  %14 = getelementptr inbounds ptr, ptr %7, i64 3
  %15 = load ptr, ptr %14, align 8, !tbaa !8
  %16 = getelementptr inbounds ptr, ptr %7, i64 4
  %17 = load ptr, ptr %16, align 8, !tbaa !8
  %18 = getelementptr inbounds ptr, ptr %7, i64 5
  %19 = load ptr, ptr %18, align 8, !tbaa !8
  call void @__omp_offloading_6bc59cba_a500482d__Z4stepPfS_PKiiif_l9_omp_outlined_omp_outlined(ptr %4, ptr %5, i64 %9, i64 %11, ptr %13, ptr %15, ptr %17, ptr %19) #4
  ret void
}

declare void @__kmpc_get_shared_variables(ptr)

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) #6

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) #4

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) #7

; Function Attrs: nosync nounwind
declare void @__kmpc_free_shared(ptr allocptr nocapture, i64) #8

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) #4

declare void @__kmpc_target_deinit()

attributes #0 = { alwaysinline convergent mustprogress norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { alwaysinline convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #2 = { nosync nounwind allocsize(0) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #4 = { nounwind }
attributes #5 = { convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #6 = { alwaysinline }
attributes #7 = { convergent "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #8 = { nosync nounwind }
attributes #9 = { convergent }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708179, !"_Z4stepPfS_PKiiif", i32 9, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9, !9, i64 0}
!9 = !{!"any pointer", !10, i64 0}
!10 = !{!"omnipotent char", !11, i64 0}
!11 = !{!"Simple C++ TBAA"}
!12 = !{!13, !13, i64 0}
!13 = !{!"long", !10, i64 0}
!14 = !{!15, !15, i64 0}
!15 = !{!"p1 int", !9, i64 0}
!16 = !{!17, !17, i64 0}
!17 = !{!"p1 float", !9, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"int", !10, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !10, i64 0}
!22 = !{!23, !23, i64 0}
!23 = !{!"any p2 pointer", !9, i64 0}
!24 = !{!25, !25, i64 0}
!25 = !{!"p2 int", !23, i64 0}
!26 = !{!27, !27, i64 0}
!27 = !{!"p2 float", !23, i64 0}
!28 = !{}
!29 = !{i64 4}
!30 = !{i64 8}
!31 = !{!32, !32, i64 0}
!32 = !{!"short", !10, i64 0}
!33 = !{!34, !34, i64 0}
!34 = !{!"p1 long", !9, i64 0}
