; Generated by gen.sh: Inputs/legal_size_t_inner_loop.cpp before any optimization,
; lowered at element grain through default<O3> -- do not edit.
;
; RUN: env GICC_MODE=chunk-lower GICC_CHUNK_GRAIN=element %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes='default<O3>' -S %s 2>/dev/null | %FileCheck %s
;
; The kernel computes the peer address once and hands it to the region.
; CHECK-LABEL: define {{.*}} @__omp_offloading_
; CHECK: [[PD:%.*]] = {{.*}}call {{.*}}ptr @ompx__peer_addr(
; CHECK: store i64 {{%.*}}, ptr addrspace(3) @gicc.chunk.delta
; CHECK: store i8 {{%.*}}, ptr addrspace(3) @gicc.chunk.mirror
; CHECK: call void @__kmpc_distribute_static_init
; CHECK: call void @__kmpc_parallel_51(
; Fallback only when the peer is not mapped.
; CHECK: br i1 {{%.*}}, label {{%.*}}, label {{%.*}}
; CHECK: call void @ompx__block_put_one(
; CHECK-NOT: ompx_pipelined_put
;
; The worksharing loop stores every word locally and to the peer.
; CHECK-LABEL: define internal void @__omp_offloading_{{.*}}_omp_outlined_omp_outlined(
; CHECK: load i64, ptr addrspace(3) @gicc.chunk.delta
; CHECK: store i32 [[V:%.*]], ptr [[P:%.*]], align 4
; CHECK-NEXT: [[R:%.*]] = getelementptr i8, ptr [[P]], i64 {{%.*}}
; CHECK-NEXT: [[T:%.*]] = select i1 {{%.*}}, ptr [[R]], ptr [[P]]
; CHECK-NEXT: store i32 [[V]], ptr [[T]], align 4
;
; And it is alwaysinline again, with the prep marker gone.
; CHECK-NOT: gicc-chunk-noinline

source_filename = "Inputs/legal_size_t_inner_loop.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 1, i8 1, i8 1, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline convergent mustprogress norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3, i64 noundef %4, i64 noundef %5, i64 noundef %6, ptr noundef %7) #0 {
  %9 = alloca ptr, align 8
  %10 = alloca i64, align 8
  %11 = alloca i64, align 8
  %12 = alloca ptr, align 8
  %13 = alloca i64, align 8
  %14 = alloca i64, align 8
  %15 = alloca i64, align 8
  %16 = alloca ptr, align 8
  %17 = alloca i64, align 8
  %18 = alloca i64, align 8
  %19 = alloca i64, align 8
  %20 = alloca i64, align 8
  %21 = alloca i64, align 8
  %22 = alloca i32, align 4
  %23 = alloca i32, align 4
  store ptr %0, ptr %9, align 8, !tbaa !8
  store i64 %1, ptr %10, align 8, !tbaa !12
  store i64 %2, ptr %11, align 8, !tbaa !12
  store ptr %3, ptr %12, align 8, !tbaa !14
  store i64 %4, ptr %13, align 8, !tbaa !12
  store i64 %5, ptr %14, align 8, !tbaa !12
  store i64 %6, ptr %15, align 8, !tbaa !12
  store ptr %7, ptr %16, align 8, !tbaa !14
  %24 = call i32 @__kmpc_target_init(ptr @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_kernel_environment, ptr %0)
  %25 = icmp eq i32 %24, -1
  br i1 %25, label %26, label %40

26:                                               ; preds = %8
  %27 = call i32 @__kmpc_global_thread_num(ptr @1)
  %28 = load i64, ptr %10, align 8, !tbaa !12
  store i64 %28, ptr %17, align 8, !tbaa !12
  %29 = load i64, ptr %17, align 8, !tbaa !12
  %30 = load i64, ptr %11, align 8, !tbaa !12
  store i64 %30, ptr %18, align 8, !tbaa !12
  %31 = load i64, ptr %18, align 8, !tbaa !12
  %32 = load ptr, ptr %12, align 8, !tbaa !14
  %33 = load i32, ptr %13, align 4, !tbaa !16
  store i32 %33, ptr %19, align 4, !tbaa !16
  %34 = load i64, ptr %19, align 8, !tbaa !12
  %35 = load i32, ptr %14, align 4, !tbaa !16
  store i32 %35, ptr %20, align 4, !tbaa !16
  %36 = load i64, ptr %20, align 8, !tbaa !12
  %37 = load i32, ptr %15, align 4, !tbaa !16
  store i32 %37, ptr %21, align 4, !tbaa !16
  %38 = load i64, ptr %21, align 8, !tbaa !12
  %39 = load ptr, ptr %16, align 8, !tbaa !14
  store i32 0, ptr %22, align 4
  store i32 %27, ptr %23, align 4, !tbaa !16
  call void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined(ptr %23, ptr %22, i64 %29, i64 %31, ptr %32, i64 %34, i64 %36, i64 %38, ptr %39) #4
  call void @__kmpc_target_deinit()
  ret void

40:                                               ; preds = %8
  ret void
}

declare i32 @__kmpc_target_init(ptr, ptr)

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, ptr noundef %4, i64 noundef %5, i64 noundef %6, i64 noundef %7, ptr noundef %8) #1 {
  %10 = alloca ptr, align 8
  %11 = alloca ptr, align 8
  %12 = alloca i64, align 8
  %13 = alloca i64, align 8
  %14 = alloca ptr, align 8
  %15 = alloca i64, align 8
  %16 = alloca i64, align 8
  %17 = alloca i64, align 8
  %18 = alloca ptr, align 8
  %19 = alloca i64, align 8
  %20 = alloca i64, align 8
  %21 = alloca i64, align 8
  %22 = alloca i64, align 8
  %23 = alloca i64, align 8
  %24 = alloca i64, align 8
  %25 = alloca i64, align 8
  %26 = alloca i64, align 8
  %27 = alloca i32, align 4
  %28 = alloca i64, align 8
  %29 = alloca [6 x ptr], align 8
  store ptr %0, ptr %10, align 8, !tbaa !14
  store ptr %1, ptr %11, align 8, !tbaa !14
  store i64 %2, ptr %12, align 8, !tbaa !12
  store i64 %3, ptr %13, align 8, !tbaa !12
  store ptr %4, ptr %14, align 8, !tbaa !14
  store i64 %5, ptr %15, align 8, !tbaa !12
  store i64 %6, ptr %16, align 8, !tbaa !12
  store i64 %7, ptr %17, align 8, !tbaa !12
  store ptr %8, ptr %18, align 8, !tbaa !14
  %30 = load i64, ptr %13, align 8, !tbaa !12
  %31 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store i64 %30, ptr %31, align 8, !tbaa !12
  %32 = load ptr, ptr %14, align 8, !tbaa !14
  %33 = call align 16 ptr @__kmpc_alloc_shared(i64 8)
  store ptr %32, ptr %33, align 8, !tbaa !14
  %34 = load i32, ptr %15, align 4, !tbaa !16
  %35 = call align 16 ptr @__kmpc_alloc_shared(i64 4)
  store i32 %34, ptr %35, align 4, !tbaa !16
  %36 = load i32, ptr %16, align 4, !tbaa !16
  %37 = call align 16 ptr @__kmpc_alloc_shared(i64 4)
  store i32 %36, ptr %37, align 4, !tbaa !16
  call void @llvm.lifetime.start.p0(i64 8, ptr %19) #4
  call void @llvm.lifetime.start.p0(i64 8, ptr %21) #4
  %38 = load i64, ptr %31, align 8, !tbaa !12
  store i64 %38, ptr %21, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %22) #4
  %39 = load i64, ptr %21, align 8, !tbaa !12
  %40 = sub i64 %39, 0
  %41 = udiv i64 %40, 1
  %42 = sub i64 %41, 1
  store i64 %42, ptr %22, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %23) #4
  store i64 0, ptr %23, align 8, !tbaa !12
  call void @llvm.lifetime.end.p0(i64 8, ptr %23) #4
  %43 = load i64, ptr %21, align 8, !tbaa !12
  %44 = icmp ult i64 0, %43
  br i1 %44, label %45, label %103

45:                                               ; preds = %9
  call void @llvm.lifetime.start.p0(i64 8, ptr %24) #4
  store i64 0, ptr %24, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %25) #4
  %46 = load i64, ptr %22, align 8, !tbaa !12
  store i64 %46, ptr %25, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %26) #4
  store i64 1, ptr %26, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 4, ptr %27) #4
  store i32 0, ptr %27, align 4, !tbaa !16
  call void @llvm.lifetime.start.p0(i64 8, ptr %28) #4
  %47 = load i64, ptr %12, align 8, !tbaa !12
  %48 = load ptr, ptr %10, align 8
  %49 = load i32, ptr %48, align 4, !tbaa !16
  call void @__kmpc_distribute_static_init_8u(ptr @2, i32 %49, i32 91, ptr %27, ptr %24, ptr %25, ptr %26, i64 1, i64 %47)
  %50 = load i64, ptr %25, align 8, !tbaa !12
  %51 = load i64, ptr %22, align 8, !tbaa !12
  %52 = icmp ugt i64 %50, %51
  br i1 %52, label %53, label %55

53:                                               ; preds = %45
  %54 = load i64, ptr %22, align 8, !tbaa !12
  br label %57

55:                                               ; preds = %45
  %56 = load i64, ptr %25, align 8, !tbaa !12
  br label %57

57:                                               ; preds = %55, %53
  %58 = phi i64 [ %54, %53 ], [ %56, %55 ]
  store i64 %58, ptr %25, align 8, !tbaa !12
  %59 = load i64, ptr %24, align 8, !tbaa !12
  store i64 %59, ptr %19, align 8, !tbaa !12
  br label %60

60:                                               ; preds = %96, %57
  %61 = load i64, ptr %19, align 8, !tbaa !12
  %62 = load i64, ptr %22, align 8, !tbaa !12
  %63 = add i64 %62, 1
  %64 = icmp ult i64 %61, %63
  br i1 %64, label %66, label %65

65:                                               ; preds = %60
  br label %99

66:                                               ; preds = %60
  %67 = load i64, ptr %24, align 8
  %68 = load i64, ptr %25, align 8
  %69 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 0
  %70 = inttoptr i64 %67 to ptr
  store ptr %70, ptr %69, align 8, !tbaa !18
  %71 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 1
  %72 = inttoptr i64 %68 to ptr
  store ptr %72, ptr %71, align 8, !tbaa !18
  %73 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 2
  store ptr %31, ptr %73, align 8, !tbaa !18
  %74 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 3
  store ptr %33, ptr %74, align 8, !tbaa !18
  %75 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 4
  store ptr %35, ptr %75, align 8, !tbaa !18
  %76 = getelementptr inbounds [6 x ptr], ptr %29, i64 0, i64 5
  store ptr %37, ptr %76, align 8, !tbaa !18
  %77 = load ptr, ptr %10, align 8
  %78 = load i32, ptr %77, align 4, !tbaa !16
  call void @__kmpc_parallel_51(ptr @1, i32 %78, i32 1, i32 -1, i32 -1, ptr @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined_omp_outlined, ptr @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined_omp_outlined_wrapper, ptr %29, i64 6)
  br label %79

79:                                               ; preds = %66
  %80 = load i64, ptr %19, align 8, !tbaa !12
  %81 = load i64, ptr %26, align 8, !tbaa !12
  %82 = add i64 %80, %81
  store i64 %82, ptr %19, align 8, !tbaa !12
  %83 = load i64, ptr %24, align 8, !tbaa !12
  %84 = load i64, ptr %26, align 8, !tbaa !12
  %85 = add i64 %83, %84
  store i64 %85, ptr %24, align 8, !tbaa !12
  %86 = load i64, ptr %25, align 8, !tbaa !12
  %87 = load i64, ptr %26, align 8, !tbaa !12
  %88 = add i64 %86, %87
  store i64 %88, ptr %25, align 8, !tbaa !12
  %89 = load i64, ptr %25, align 8, !tbaa !12
  %90 = load i64, ptr %22, align 8, !tbaa !12
  %91 = icmp ugt i64 %89, %90
  br i1 %91, label %92, label %94

92:                                               ; preds = %79
  %93 = load i64, ptr %22, align 8, !tbaa !12
  br label %96

94:                                               ; preds = %79
  %95 = load i64, ptr %25, align 8, !tbaa !12
  br label %96

96:                                               ; preds = %94, %92
  %97 = phi i64 [ %93, %92 ], [ %95, %94 ]
  store i64 %97, ptr %25, align 8, !tbaa !12
  %98 = load i64, ptr %24, align 8, !tbaa !12
  store i64 %98, ptr %19, align 8, !tbaa !12
  br label %60

99:                                               ; preds = %65
  br label %100

100:                                              ; preds = %99
  %101 = load ptr, ptr %10, align 8
  %102 = load i32, ptr %101, align 4, !tbaa !16
  call void @__kmpc_distribute_static_fini(ptr @2, i32 %102)
  call void @llvm.lifetime.end.p0(i64 8, ptr %28) #4
  br label %103

103:                                              ; preds = %100, %9
  call void @llvm.lifetime.end.p0(i64 4, ptr %27) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %26) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %25) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %24) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %22) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %21) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %19) #4
  %104 = load i32, ptr %17, align 4, !tbaa !16
  %105 = load ptr, ptr %18, align 8, !tbaa !14
  %106 = load ptr, ptr %33, align 8, !tbaa !14
  %107 = load i64, ptr %31, align 8, !tbaa !12
  %108 = mul i64 %107, 4
  call void @ompx_pipelined_put(i32 noundef %104, ptr noundef %105, ptr noundef %106, i64 noundef %108) #10
  call void @__kmpc_free_shared(ptr %37, i64 4)
  call void @__kmpc_free_shared(ptr %35, i64 4)
  call void @__kmpc_free_shared(ptr %33, i64 8)
  call void @__kmpc_free_shared(ptr %31, i64 8)
  ret void
}

; Function Attrs: nosync nounwind allocsize(0)
declare noalias ptr @__kmpc_alloc_shared(i64) #2

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr captures(none)) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr captures(none)) #3

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #4

; Function Attrs: alwaysinline convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined_omp_outlined(ptr noalias noundef %0, ptr noalias noundef %1, i64 noundef %2, i64 noundef %3, ptr noundef nonnull align 8 dereferenceable(8) %4, ptr noundef nonnull align 8 dereferenceable(8) %5, ptr noundef nonnull align 4 dereferenceable(4) %6, ptr noundef nonnull align 4 dereferenceable(4) %7) #1 {
  %9 = alloca ptr, align 8
  %10 = alloca ptr, align 8
  %11 = alloca i64, align 8
  %12 = alloca i64, align 8
  %13 = alloca ptr, align 8
  %14 = alloca ptr, align 8
  %15 = alloca ptr, align 8
  %16 = alloca ptr, align 8
  %17 = alloca i64, align 8
  %18 = alloca i64, align 8
  %19 = alloca i64, align 8
  %20 = alloca i64, align 8
  %21 = alloca i64, align 8
  %22 = alloca i64, align 8
  %23 = alloca i64, align 8
  %24 = alloca i64, align 8
  %25 = alloca i32, align 4
  %26 = alloca i64, align 8
  store ptr %0, ptr %9, align 8, !tbaa !14
  store ptr %1, ptr %10, align 8, !tbaa !14
  store i64 %2, ptr %11, align 8, !tbaa !12
  store i64 %3, ptr %12, align 8, !tbaa !12
  store ptr %4, ptr %13, align 8, !tbaa !20
  store ptr %5, ptr %14, align 8, !tbaa !22
  store ptr %6, ptr %15, align 8, !tbaa !14
  store ptr %7, ptr %16, align 8, !tbaa !14
  %27 = load ptr, ptr %13, align 8, !tbaa !20, !nonnull !24, !align !25
  %28 = load ptr, ptr %14, align 8, !tbaa !22, !nonnull !24, !align !25
  %29 = load ptr, ptr %15, align 8, !tbaa !14, !nonnull !24, !align !26
  %30 = load ptr, ptr %16, align 8, !tbaa !14, !nonnull !24, !align !26
  call void @llvm.lifetime.start.p0(i64 8, ptr %17) #4
  call void @llvm.lifetime.start.p0(i64 8, ptr %19) #4
  %31 = load i64, ptr %27, align 8, !tbaa !12
  store i64 %31, ptr %19, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %20) #4
  %32 = load i64, ptr %19, align 8, !tbaa !12
  %33 = sub i64 %32, 0
  %34 = udiv i64 %33, 1
  %35 = sub i64 %34, 1
  store i64 %35, ptr %20, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %21) #4
  store i64 0, ptr %21, align 8, !tbaa !12
  call void @llvm.lifetime.end.p0(i64 8, ptr %21) #4
  %36 = load i64, ptr %19, align 8, !tbaa !12
  %37 = icmp ult i64 0, %36
  br i1 %37, label %38, label %71

38:                                               ; preds = %8
  call void @llvm.lifetime.start.p0(i64 8, ptr %22) #4
  store i64 0, ptr %22, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %23) #4
  %39 = load i64, ptr %20, align 8, !tbaa !12
  store i64 %39, ptr %23, align 8, !tbaa !12
  %40 = load i64, ptr %11, align 8, !tbaa !12
  %41 = load i64, ptr %12, align 8, !tbaa !12
  store i64 %40, ptr %22, align 8, !tbaa !12
  store i64 %41, ptr %23, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 8, ptr %24) #4
  store i64 1, ptr %24, align 8, !tbaa !12
  call void @llvm.lifetime.start.p0(i64 4, ptr %25) #4
  store i32 0, ptr %25, align 4, !tbaa !16
  call void @llvm.lifetime.start.p0(i64 8, ptr %26) #4
  %42 = load ptr, ptr %9, align 8
  %43 = load i32, ptr %42, align 4, !tbaa !16
  call void @__kmpc_for_static_init_8u(ptr @3, i32 %43, i32 33, ptr %25, ptr %22, ptr %23, ptr %24, i64 1, i64 1)
  %44 = load i64, ptr %22, align 8, !tbaa !12
  store i64 %44, ptr %17, align 8, !tbaa !12
  br label %45

45:                                               ; preds = %63, %38
  %46 = load i64, ptr %17, align 8, !tbaa !12
  %47 = load i64, ptr %12, align 8, !tbaa !12
  %48 = add i64 %47, 1
  %49 = icmp ult i64 %46, %48
  br i1 %49, label %51, label %50

50:                                               ; preds = %45
  br label %67

51:                                               ; preds = %45
  %52 = load i64, ptr %17, align 8, !tbaa !12
  %53 = mul i64 %52, 1
  %54 = add i64 0, %53
  store i64 %54, ptr %26, align 8, !tbaa !12
  %55 = load i32, ptr %29, align 4, !tbaa !16
  %56 = load i64, ptr %26, align 8, !tbaa !12
  %57 = load i32, ptr %30, align 4, !tbaa !16
  %58 = call noundef i32 @_ZL7produceimi(i32 noundef %55, i64 noundef %56, i32 noundef %57) #10
  %59 = load ptr, ptr %28, align 8, !tbaa !14
  %60 = load i64, ptr %26, align 8, !tbaa !12
  %61 = getelementptr inbounds nuw i32, ptr %59, i64 %60
  store i32 %58, ptr %61, align 4, !tbaa !16
  br label %62

62:                                               ; preds = %51
  br label %63

63:                                               ; preds = %62
  %64 = load i64, ptr %17, align 8, !tbaa !12
  %65 = load i64, ptr %24, align 8, !tbaa !12
  %66 = add i64 %64, %65
  store i64 %66, ptr %17, align 8, !tbaa !12
  br label %45

67:                                               ; preds = %50
  br label %68

68:                                               ; preds = %67
  %69 = load ptr, ptr %9, align 8
  %70 = load i32, ptr %69, align 4, !tbaa !16
  call void @__kmpc_for_static_fini(ptr @3, i32 %70)
  call void @llvm.lifetime.end.p0(i64 8, ptr %26) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %25) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %24) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %23) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %22) #4
  br label %71

71:                                               ; preds = %68, %8
  call void @llvm.lifetime.end.p0(i64 8, ptr %20) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %19) #4
  call void @llvm.lifetime.end.p0(i64 8, ptr %17) #4
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) #4

; Function Attrs: convergent inlinehint mustprogress nounwind
define internal noundef i32 @_ZL7produceimi(i32 noundef %0, i64 noundef %1, i32 noundef %2) #5 {
  %4 = alloca i32, align 4
  %5 = alloca i64, align 8
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  store i32 %0, ptr %4, align 4, !tbaa !16
  store i64 %1, ptr %5, align 8, !tbaa !12
  store i32 %2, ptr %6, align 4, !tbaa !16
  call void @llvm.lifetime.start.p0(i64 4, ptr %7) #4
  %9 = load i32, ptr %4, align 4, !tbaa !16
  %10 = mul i32 %9, -1640531535
  %11 = load i64, ptr %5, align 8, !tbaa !12
  %12 = trunc i64 %11 to i32
  %13 = xor i32 %10, %12
  store i32 %13, ptr %7, align 4, !tbaa !16
  call void @llvm.lifetime.start.p0(i64 4, ptr %8) #4
  store i32 0, ptr %8, align 4, !tbaa !16
  br label %14

14:                                               ; preds = %32, %3
  %15 = load i32, ptr %8, align 4, !tbaa !16
  %16 = load i32, ptr %6, align 4, !tbaa !16
  %17 = icmp slt i32 %15, %16
  br i1 %17, label %19, label %18

18:                                               ; preds = %14
  call void @llvm.lifetime.end.p0(i64 4, ptr %8) #4
  br label %35

19:                                               ; preds = %14
  %20 = load i32, ptr %7, align 4, !tbaa !16
  %21 = shl i32 %20, 13
  %22 = load i32, ptr %7, align 4, !tbaa !16
  %23 = xor i32 %22, %21
  store i32 %23, ptr %7, align 4, !tbaa !16
  %24 = load i32, ptr %7, align 4, !tbaa !16
  %25 = lshr i32 %24, 17
  %26 = load i32, ptr %7, align 4, !tbaa !16
  %27 = xor i32 %26, %25
  store i32 %27, ptr %7, align 4, !tbaa !16
  %28 = load i32, ptr %7, align 4, !tbaa !16
  %29 = shl i32 %28, 5
  %30 = load i32, ptr %7, align 4, !tbaa !16
  %31 = xor i32 %30, %29
  store i32 %31, ptr %7, align 4, !tbaa !16
  br label %32

32:                                               ; preds = %19
  %33 = load i32, ptr %8, align 4, !tbaa !16
  %34 = add nsw i32 %33, 1
  store i32 %34, ptr %8, align 4, !tbaa !16
  br label %14, !llvm.loop !27

35:                                               ; preds = %18
  %36 = load i32, ptr %7, align 4, !tbaa !16
  call void @llvm.lifetime.end.p0(i64 4, ptr %7) #4
  ret i32 %36
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) #4

; Function Attrs: convergent norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined_omp_outlined_wrapper(i16 noundef zeroext %0, i32 noundef %1) #6 {
  %3 = alloca i16, align 2
  %4 = alloca i32, align 4
  %5 = alloca i32, align 4
  %6 = alloca ptr, align 8
  store i16 %0, ptr %3, align 2, !tbaa !29
  store i32 %1, ptr %4, align 4, !tbaa !16
  store i32 0, ptr %5, align 4
  call void @__kmpc_get_shared_variables(ptr %6)
  %7 = load ptr, ptr %6, align 8
  %8 = getelementptr inbounds ptr, ptr %7, i64 0
  %9 = load i64, ptr %8, align 8, !tbaa !20
  %10 = getelementptr inbounds ptr, ptr %7, i64 1
  %11 = load i64, ptr %10, align 8, !tbaa !20
  %12 = getelementptr inbounds ptr, ptr %7, i64 2
  %13 = load ptr, ptr %12, align 8, !tbaa !8
  %14 = getelementptr inbounds ptr, ptr %7, i64 3
  %15 = load ptr, ptr %14, align 8, !tbaa !8
  %16 = getelementptr inbounds ptr, ptr %7, i64 4
  %17 = load ptr, ptr %16, align 8, !tbaa !8
  %18 = getelementptr inbounds ptr, ptr %7, i64 5
  %19 = load ptr, ptr %18, align 8, !tbaa !8
  call void @__omp_offloading_6bc59cba_a5003e92__Z4stepPjS_miimi_l16_omp_outlined_omp_outlined(ptr %4, ptr %5, i64 %9, i64 %11, ptr %13, ptr %15, ptr %17, ptr %19) #4
  ret void
}

declare void @__kmpc_get_shared_variables(ptr)

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) #7

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) #4

; Function Attrs: convergent
declare void @ompx_pipelined_put(i32 noundef, ptr noundef, ptr noundef, i64 noundef) #8

; Function Attrs: nosync nounwind
declare void @__kmpc_free_shared(ptr allocptr captures(none), i64) #9

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) #4

declare void @__kmpc_target_deinit()

attributes #0 = { alwaysinline convergent mustprogress norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { alwaysinline convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #2 = { nosync nounwind allocsize(0) }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #4 = { nounwind }
attributes #5 = { convergent inlinehint mustprogress nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #6 = { convergent norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #7 = { alwaysinline }
attributes #8 = { convergent "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #9 = { nosync nounwind }
attributes #10 = { convergent }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526710638, !"_Z4stepPjS_miimi", i32 16, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9, !9, i64 0}
!9 = !{!"any pointer", !10, i64 0}
!10 = !{!"omnipotent char", !11, i64 0}
!11 = !{!"Simple C++ TBAA"}
!12 = !{!13, !13, i64 0}
!13 = !{!"long", !10, i64 0}
!14 = !{!15, !15, i64 0}
!15 = !{!"p1 int", !9, i64 0}
!16 = !{!17, !17, i64 0}
!17 = !{!"int", !10, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"any p2 pointer", !9, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"p1 long", !9, i64 0}
!22 = !{!23, !23, i64 0}
!23 = !{!"p2 int", !19, i64 0}
!24 = !{}
!25 = !{i64 8}
!26 = !{i64 4}
!27 = distinct !{!27, !28}
!28 = !{!"llvm.loop.mustprogress"}
!29 = !{!30, !30, i64 0}
!30 = !{!"short", !10, i64 0}
