/**
 * TraceEmitter.cpp — see TraceEmitter.h for design intent.
 *
 * F1 (this commit): build a kernel_trace<&K> specialization with an empty
 * body (just `(void)`-cast on each forwarded arg to silence unused-param
 * warnings) and write it to /tmp/<basename>.gicc.cpp. The body for lifted
 * put_no_db / get_no_db calls comes in F2.
 *
 * The sidecar file is per-TU: every validated kernel in the TU appends
 * its specialization into the same file. The first specialization
 * truncates and writes the file header (#includes); subsequent ones append.
 */
#include "TraceEmitter.h"

#include "clang/AST/PrettyPrinter.h"
#include "clang/Basic/SourceManager.h"

#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"

#include <fstream>

namespace gicc_plugin {

namespace {

// Compute the sidecar path for a given main-file path. v1 uses /tmp so
// lit-test source trees (which are read-only) work without extra plumbing.
// Phase G will replace this with a CMake-build-dir-aware path.
std::string sidecar_path_for(const std::string& main_file) {
    std::string base = llvm::sys::path::stem(main_file).str();
    return std::string("/tmp/") + base + ".gicc.cpp";
}

// Render a kernel param list as "T0 n0, T1 n1, ..." with the leading
// DeviceCtx* (param 0) skipped. Uses a SuppressTagKeyword printing
// policy so we get "gicc::DeviceCtx*" rather than "class gicc::DeviceCtx*".
std::string param_decl_list(const clang::FunctionDecl* fd) {
    clang::PrintingPolicy pp(fd->getASTContext().getLangOpts());
    pp.SuppressTagKeyword = true;
    pp.Bool = true;
    std::string out;
    for (unsigned i = 1; i < fd->getNumParams(); i++) {
        if (i > 1) out += ", ";
        const auto* p = fd->getParamDecl(i);
        out += p->getType().getAsString(pp);
        out += " ";
        out += p->getNameAsString();
    }
    return out;
}

} // namespace

std::string TraceEmitter::emit(const KernelInfo& ki, const HKAnalysis& /*hk*/) {
    auto& sm = CI_.getSourceManager();
    auto file_id = sm.getMainFileID();
    auto file_ref = sm.getFileEntryRefForID(file_id);
    std::string main_file = file_ref
        ? std::string(file_ref->getName())
        : std::string("unknown");
    std::string sidecar = sidecar_path_for(main_file);

    const bool first_open = opened_sidecars_.insert(sidecar).second;
    std::ofstream out(sidecar, first_open ? std::ios::trunc : std::ios::app);
    if (!out) {
        llvm::errs() << "[gicc-plugin] FAIL to open sidecar " << sidecar << "\n";
        return sidecar;
    }

    if (first_open) {
        // Header: pull in everything the trace body needs. The user must
        // build the sidecar with the same GICC_PLATFORM_* / bootstrap
        // defines as the main TU; Phase G will arrange that automatically.
        out << "// AUTO-GENERATED by gicc-clang-plugin. DO NOT EDIT.\n";
        out << "// Trace specializations for kernels in " << main_file << "\n\n";
        out << "#include <hip/hip_runtime.h>\n";
        out << "#include \"gicc/gicc.hpp\"\n\n";
    }

    const std::string kname = ki.decl->getNameAsString();
    const std::string params = param_decl_list(ki.decl);

    // Forward-declare the kernel so &kname is a well-formed expression
    // inside the specialization. In v1 we deliberately avoid pulling the
    // user's TU header into the sidecar; the prototype here is the
    // minimum surface needed to take the address.
    {
        clang::PrintingPolicy pp(ki.decl->getASTContext().getLangOpts());
        pp.SuppressTagKeyword = true;
        pp.Bool = true;
        out << "__global__ void " << kname << "(";
        for (unsigned i = 0; i < ki.decl->getNumParams(); i++) {
            if (i > 0) out << ", ";
            const auto* p = ki.decl->getParamDecl(i);
            out << p->getType().getAsString(pp);
        }
        out << ");\n\n";
    }

    out << "namespace gicc {\n";
    out << "namespace detail {\n";
    out << "template<> struct kernel_trace<&" << kname << "> {\n";
    out << "    static void run(gicc::Runtime& rt, int peer, "
           "dim3 grid, dim3 block";
    if (!params.empty()) out << ", " << params;
    out << ") {\n";
    out << "        (void)rt; (void)peer; (void)grid; (void)block;\n";
    for (unsigned i = 1; i < ki.decl->getNumParams(); i++) {
        out << "        (void)" << ki.decl->getParamDecl(i)->getNameAsString()
            << ";\n";
    }
    // F2 will replace the body with lifted put_no_db calls.
    out << "    }\n";
    out << "};\n";
    out << "} // namespace detail\n";
    out << "} // namespace gicc\n\n";

    llvm::errs() << "[gicc-plugin]   trace emitted: " << sidecar
                 << " for kernel " << kname << "\n";
    return sidecar;
}

} // namespace gicc_plugin
