#include "GICCOmpDeviceDiscovery.h"
#include "GICCPassConfig.h"
#include "KernelInventory.h"
#include "MetadataIO.h"
#include "SiteId.h"
#include "TraceTemplateBuilder.h"

#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"

using namespace llvm;

namespace gicc::pass {

// Classify a CallInst as an omp_dwq marker. The omp_dwq markers mangle
// differently from the HIP gicc:: API so we cannot reuse classifyGICCCall
// without modifying the shared KernelInventory — instead use a local
// classifier keyed on the omp_dwq-specific Itanium substrings:
//
//   gicc::omp_dwq::put   -> contains "7omp_dwq3put"
//   gicc::omp_dwq::flush -> contains "7omp_dwq5flush"
//
// Map put -> PutNoDb and flush -> Flush to match what TraceTemplateBuilder
// expects (it uses opKindName() to write the JSON "kind" field).
static bool classifyOmpDwqCall(const CallInst &CI, GICCOpKind &out) {
    auto *F = CI.getCalledFunction();
    if (!F) return false;
    StringRef n = F->getName();
    if (n.contains("7omp_dwq3put")) {
        out = GICCOpKind::PutNoDb;
        return true;
    }
    if (n.contains("7omp_dwq5flush")) {
        out = GICCOpKind::Flush;
        return true;
    }
    return false;
}

// Collect omp_dwq marker call sites from F. Populates info using the same
// field layout as collectGICCSites() so that buildKernelTemplate() can
// consume the result unchanged.
static void collectOmpDwqSites(Function &F, GICCKernelInfo &info) {
    info.kernel      = &F;
    info.mangledName = F.getName().str();
    // simpleName stays as the full kernel name for omp offload kernels;
    // callers that want a shorter label use mangledName directly.
    info.simpleName  = F.getName().str();
    info.sites.clear();

    unsigned idx = 0;
    for (BasicBlock &BB : F) {
        for (Instruction &I : BB) {
            auto *CI = dyn_cast<CallInst>(&I);
            if (!CI) continue;
            GICCOpKind kind;
            if (!classifyOmpDwqCall(*CI, kind)) continue;

            GICCCallSite s;
            s.CI                = CI;
            s.kind              = kind;
            s.callIndexInKernel = idx;
            s.siteId            = buildSiteId(CI, &F, idx);
            // hk_capable defaults to true; buildKernelTemplate / HKAnalysis
            // will evaluate the actual operands and update it.
            s.hk_capable        = true;
            info.sites.push_back(s);
            ++idx;
        }
    }
}

// Extract the source-mangled substring from an OpenMP offload kernel name.
// The naming convention is:
//   __omp_offloading_<hex>_<hex>_<SrcMangled>_l<line>
// where <SrcMangled> starts with "_Z" and runs up to (but not including)
// the final "_l<digits>" suffix.
//
// We extract <SrcMangled> so that the host OmpDeviceDiscovery pass (Task 3)
// can match the template by looking up by the source-level mangled name —
// the same name the host sees in the offload entry descriptor.
//
// If the pattern doesn't match (e.g. synthetic/anonymous lambda kernels)
// we fall back to the full kernel name as the JSON key.
static std::string extractOmpKernelKey(StringRef name) {
    // Find the "_Z" that begins the source-mangled portion.
    auto zpos = name.find("_Z");
    if (zpos == StringRef::npos)
        return name.str();
    StringRef suffix = name.drop_front(zpos);
    // Strip the trailing "_l<digits>" generated by the OpenMP offload naming.
    // Search backwards for "_l" followed by only digits.
    auto lpos = suffix.rfind("_l");
    if (lpos != StringRef::npos) {
        StringRef tail = suffix.drop_front(lpos + 2); // skip "_l"
        bool allDigits = !tail.empty();
        for (char c : tail) {
            if (c < '0' || c > '9') { allDigits = false; break; }
        }
        if (allDigits)
            suffix = suffix.take_front(lpos);
    }
    return suffix.str();
}

PreservedAnalyses GICCOmpDeviceDiscoveryPass::run(Module &M,
                                                   ModuleAnalysisManager &MAM) {
    const auto &cfg = getConfig();
    if (cfg.mode != Mode::OmpDwq)
        return PreservedAnalyses::all();

    // Only act on the AMD GPU (amdgcn) device module. The host module gets
    // the same pass registered but has no amdgpu_kernel functions.
    if (!Triple(M.getTargetTriple()).isAMDGCN())
        return PreservedAnalyses::all();

    auto &FAM = MAM.getResult<FunctionAnalysisManagerModuleProxy>(M).getManager();

    for (Function &F : M) {
        if (F.isDeclaration()) continue;
        if (!isGPUKernel(F)) continue;
        if (!F.getName().starts_with("__omp_offloading_")) continue;

        GICCKernelInfo info;
        collectOmpDwqSites(F, info);
        if (info.sites.empty()) continue;

        // Derive the JSON key: the source-mangled portion of the kernel name
        // so that the host-side pass can look it up by offload entry name.
        std::string kernelKey = extractOmpKernelKey(F.getName());

        errs() << "[omp-dwq-discovery] kernel " << F.getName()
               << " -> key=" << kernelKey
               << " has " << info.sites.size() << " sites\n";
        for (const auto &s : info.sites) {
            errs() << "[omp-dwq-discovery]   site_id=" << s.siteId
                   << " kind=" << opKindName(s.kind) << "\n";
        }

        // Override mangledName in info so buildKernelTemplate uses the
        // extracted key (not the full __omp_offloading_... name) in the JSON.
        info.mangledName = kernelKey;
        // simpleName can be the extracted key too for readability.
        info.simpleName  = kernelKey;

        LoopInfo      &LI = FAM.getResult<LoopAnalysis>(F);
        DominatorTree &DT = FAM.getResult<DominatorTreeAnalysis>(F);
        KernelTemplate t  = buildKernelTemplate(info, &LI, &DT);

        if (!writeKernelTemplate(cfg.metaDir, t)) {
            errs() << "[omp-dwq-discovery] WARN: failed to write template for "
                   << kernelKey << " under " << cfg.metaDir << "\n";
        } else {
            errs() << "[omp-dwq-discovery]   wrote " << cfg.metaDir << '/'
                   << kernelKey << ".json\n";
        }
    }

    return PreservedAnalyses::all();
}

}  // namespace gicc::pass
