; Generated by gen.sh from Inputs/collapse2_transposed.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // Stores walk the array column-major: strides swap, still one box.
; #include <cstddef>
; void step(float* a, int n, int m) {
;     #pragma omp target teams distribute parallel for collapse(2) is_device_ptr(a)
;     for (int i = 0; i < n; ++i)
;         for (int j = 0; j < m; ++j)
;             a[(size_t)j * n + i] = 1.0f;
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when ((trunc i64 %1 to i32) > 0) ((trunc i64 %2 to i32) > 0)
; // CHECK-NEXT: arg#3: 2-D box extent=[(sext i32 (trunc i64 %1 to i32) to i64), (sext i32 (trunc i64 %2 to i32) to i64)] stride=[4, (4 * (sext i32 (trunc i64 %1 to i32) to i64))<nsw>] offset=0 (trusts loop-variable trunc)

source_filename = "Inputs/collapse2_transposed.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3) local_unnamed_addr #0 {
  %5 = alloca i64, align 8
  %6 = alloca i64, align 8
  %7 = alloca i64, align 8
  %8 = alloca i32, align 4
  %9 = alloca [5 x ptr], align 8
  %10 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_kernel_environment, ptr %0) #2
  %11 = icmp eq i32 %10, -1
  br i1 %11, label %13, label %12

12:                                               ; preds = %4, %62
  ret void

13:                                               ; preds = %4
  %14 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  %15 = and i64 %1, 4294967295
  %16 = and i64 %2, 4294967295
  call void @llvm.lifetime.start.p0(i64 40, ptr nonnull %9)
  %17 = trunc i64 %1 to i32
  %18 = trunc i64 %2 to i32
  %19 = shl nuw i64 %15, 32
  %20 = ashr exact i64 %19, 32
  %21 = shl nuw i64 %16, 32
  %22 = ashr exact i64 %21, 32
  %23 = mul nsw i64 %22, %20
  %24 = add nsw i64 %23, -1
  %25 = icmp sgt i32 %17, 0
  %26 = icmp sgt i32 %18, 0
  %27 = and i1 %25, %26
  br i1 %27, label %28, label %62

28:                                               ; preds = %13
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %5) #6, !noalias !8
  %29 = addrspacecast ptr %5 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %6) #6, !noalias !8
  %30 = addrspacecast ptr %6 to ptr addrspace(5)
  store i64 %24, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %31 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #6, !noalias !8
  %32 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %32, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8(ptr nonnull @2, i32 %14, i32 91, ptr nonnull %8, ptr nonnull %5, ptr nonnull %6, ptr nonnull %7, i64 1, i64 128) #2, !noalias !8
  %33 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %34 = call i64 @llvm.smin.i64(i64 %33, i64 %24)
  store i64 %34, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %35 = load i64, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %36 = icmp slt i64 %35, %23
  br i1 %36, label %37, label %61

37:                                               ; preds = %28
  %38 = addrspacecast ptr %9 to ptr addrspace(5)
  %39 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %40 = addrspacecast ptr %39 to ptr addrspace(5)
  %41 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %42 = inttoptr i64 %15 to ptr
  %43 = addrspacecast ptr %41 to ptr addrspace(5)
  %44 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %45 = inttoptr i64 %16 to ptr
  %46 = addrspacecast ptr %44 to ptr addrspace(5)
  %47 = getelementptr inbounds nuw i8, ptr %9, i64 32
  %48 = addrspacecast ptr %47 to ptr addrspace(5)
  br label %49

49:                                               ; preds = %37, %49
  %50 = phi i64 [ %34, %37 ], [ %59, %49 ]
  %51 = phi i64 [ %35, %37 ], [ %56, %49 ]
  %52 = inttoptr i64 %51 to ptr
  store ptr %52, ptr addrspace(5) %38, align 8, !tbaa !17, !noalias !8
  %53 = inttoptr i64 %50 to ptr
  store ptr %53, ptr addrspace(5) %40, align 8, !tbaa !17, !noalias !8
  store ptr %42, ptr addrspace(5) %43, align 8, !tbaa !17, !noalias !8
  store ptr %45, ptr addrspace(5) %46, align 8, !tbaa !17, !noalias !8
  store ptr %3, ptr addrspace(5) %48, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %14, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_omp_outlined_omp_outlined, ptr null, ptr nonnull %9, i64 5) #2, !noalias !8
  %54 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %55 = load i64, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %56 = add nsw i64 %55, %54
  store i64 %56, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %57 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %58 = add nsw i64 %57, %54
  %59 = call i64 @llvm.smin.i64(i64 %58, i64 %24)
  store i64 %59, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %60 = icmp slt i64 %56, %23
  br i1 %60, label %49, label %61

61:                                               ; preds = %49, %28
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %14) #2, !noalias !8
  br label %62

62:                                               ; preds = %13, %61
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %5) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 40, ptr nonnull %9)
  call void @__kmpc_target_deinit() #2
  br label %12
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_omp_outlined_omp_outlined(ptr noalias noundef readonly nocapture %0, ptr noalias readnone nocapture %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef writeonly nocapture %6) #3 {
  %8 = alloca i64, align 8
  %9 = alloca i64, align 8
  %10 = alloca i64, align 8
  %11 = alloca i32, align 4
  %12 = trunc i64 %4 to i32
  %13 = trunc i64 %5 to i32
  %14 = shl i64 %4, 32
  %15 = ashr exact i64 %14, 32
  %16 = shl i64 %5, 32
  %17 = ashr exact i64 %16, 32
  %18 = icmp sgt i32 %12, 0
  %19 = icmp sgt i32 %13, 0
  %20 = and i1 %18, %19
  br i1 %20, label %21, label %46

21:                                               ; preds = %7
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #2
  %22 = addrspacecast ptr %8 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #2
  %23 = addrspacecast ptr %9 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %22, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %23, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %24 = addrspacecast ptr %10 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %24, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %11) #2
  %25 = addrspacecast ptr %11 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %25, align 4, !tbaa !15
  %26 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8(ptr nonnull @3, i32 %26, i32 33, ptr nonnull %11, ptr nonnull %8, ptr nonnull %9, ptr nonnull %10, i64 1, i64 1) #2
  %27 = load i64, ptr addrspace(5) %22, align 8, !tbaa !11
  %28 = icmp ugt i64 %27, %3
  br i1 %28, label %45, label %29

29:                                               ; preds = %21
  %30 = load i64, ptr addrspace(5) %24, align 8, !tbaa !11
  br label %31

31:                                               ; preds = %29, %31
  %32 = phi i64 [ %27, %29 ], [ %43, %31 ]
  %33 = sdiv i64 %32, %17
  %34 = mul i64 %33, %5
  %35 = sub i64 %32, %34
  %36 = shl i64 %35, 32
  %37 = ashr exact i64 %36, 32
  %38 = mul nsw i64 %37, %15
  %39 = shl i64 %33, 32
  %40 = getelementptr float, ptr %6, i64 %38
  %41 = ashr exact i64 %39, 30
  %42 = getelementptr i8, ptr %40, i64 %41
  store float 1.000000e+00, ptr %42, align 4, !tbaa !20
  %43 = add nsw i64 %30, %32
  %44 = icmp ugt i64 %43, %3
  br i1 %44, label %45, label %31

45:                                               ; preds = %31, %21
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %26) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2
  br label %46

46:                                               ; preds = %45, %7
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708963, !"_Z4stepPfii", i32 4, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a500451d__Z4stepPfii_l4_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !13, i64 0}
