; Generated by gen.sh from Inputs/collapse2_size_t_inner.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // An unsigned inner bound: the loop is guarded by W != 0, not W > 0, and
; // that is enough for a trip count (put_signal's shape).
; #include <cstddef>
; void step(unsigned* sbuf, int K, size_t W) {
;     #pragma omp target teams distribute parallel for collapse(2) is_device_ptr(sbuf)
;     for (int k = 0; k < K; ++k)
;         for (size_t i = 0; i < W; ++i)
;             sbuf[k * W + i] = (unsigned)(k + i);
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when ((trunc i64 %1 to i32) > 0) (%2 != 0)
; // CHECK-NEXT: arg#3: 2-D box extent=[(sext i32 (trunc i64 %1 to i32) to i64), %2] stride=[(4 * %2), 4] offset=0 (trusts loop-variable trunc)

source_filename = "Inputs/collapse2_size_t_inner.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3) local_unnamed_addr #0 {
  %5 = alloca i64, align 8
  %6 = alloca i64, align 8
  %7 = alloca i64, align 8
  %8 = alloca i32, align 4
  %9 = alloca [5 x ptr], align 8
  %10 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_kernel_environment, ptr %0) #2
  %11 = icmp eq i32 %10, -1
  br i1 %11, label %13, label %12

12:                                               ; preds = %4, %58
  ret void

13:                                               ; preds = %4
  %14 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  %15 = and i64 %1, 4294967295
  call void @llvm.lifetime.start.p0(i64 40, ptr nonnull %9)
  %16 = trunc i64 %1 to i32
  %17 = shl nuw i64 %15, 32
  %18 = ashr exact i64 %17, 32
  %19 = mul i64 %18, %2
  %20 = add i64 %19, -1
  %21 = icmp sgt i32 %16, 0
  %22 = icmp ne i64 %2, 0
  %23 = and i1 %21, %22
  br i1 %23, label %24, label %58

24:                                               ; preds = %13
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %5) #6, !noalias !8
  %25 = addrspacecast ptr %5 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %25, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %6) #6, !noalias !8
  %26 = addrspacecast ptr %6 to ptr addrspace(5)
  store i64 %20, ptr addrspace(5) %26, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %27 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %27, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #6, !noalias !8
  %28 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %28, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8u(ptr nonnull @2, i32 %14, i32 91, ptr nonnull %8, ptr nonnull %5, ptr nonnull %6, ptr nonnull %7, i64 1, i64 128) #2, !noalias !8
  %29 = load i64, ptr addrspace(5) %26, align 8, !tbaa !11, !noalias !8
  %30 = call i64 @llvm.umin.i64(i64 %29, i64 %20)
  store i64 %30, ptr addrspace(5) %26, align 8, !tbaa !11, !noalias !8
  %31 = load i64, ptr addrspace(5) %25, align 8, !tbaa !11, !noalias !8
  %32 = icmp ult i64 %31, %19
  br i1 %32, label %33, label %57

33:                                               ; preds = %24
  %34 = addrspacecast ptr %9 to ptr addrspace(5)
  %35 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %36 = addrspacecast ptr %35 to ptr addrspace(5)
  %37 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %38 = inttoptr i64 %15 to ptr
  %39 = addrspacecast ptr %37 to ptr addrspace(5)
  %40 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %41 = inttoptr i64 %2 to ptr
  %42 = addrspacecast ptr %40 to ptr addrspace(5)
  %43 = getelementptr inbounds nuw i8, ptr %9, i64 32
  %44 = addrspacecast ptr %43 to ptr addrspace(5)
  br label %45

45:                                               ; preds = %33, %45
  %46 = phi i64 [ %30, %33 ], [ %55, %45 ]
  %47 = phi i64 [ %31, %33 ], [ %52, %45 ]
  %48 = inttoptr i64 %47 to ptr
  store ptr %48, ptr addrspace(5) %34, align 8, !tbaa !17, !noalias !8
  %49 = inttoptr i64 %46 to ptr
  store ptr %49, ptr addrspace(5) %36, align 8, !tbaa !17, !noalias !8
  store ptr %38, ptr addrspace(5) %39, align 8, !tbaa !17, !noalias !8
  store ptr %41, ptr addrspace(5) %42, align 8, !tbaa !17, !noalias !8
  store ptr %3, ptr addrspace(5) %44, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %14, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_omp_outlined_omp_outlined, ptr null, ptr nonnull %9, i64 5) #2, !noalias !8
  %50 = load i64, ptr addrspace(5) %27, align 8, !tbaa !11, !noalias !8
  %51 = load i64, ptr addrspace(5) %25, align 8, !tbaa !11, !noalias !8
  %52 = add i64 %51, %50
  store i64 %52, ptr addrspace(5) %25, align 8, !tbaa !11, !noalias !8
  %53 = load i64, ptr addrspace(5) %26, align 8, !tbaa !11, !noalias !8
  %54 = add i64 %53, %50
  %55 = call i64 @llvm.umin.i64(i64 %54, i64 %20)
  store i64 %55, ptr addrspace(5) %26, align 8, !tbaa !11, !noalias !8
  %56 = icmp ult i64 %52, %19
  br i1 %56, label %45, label %57

57:                                               ; preds = %45, %24
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %14) #2, !noalias !8
  br label %58

58:                                               ; preds = %13, %57
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %5) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 40, ptr nonnull %9)
  call void @__kmpc_target_deinit() #2
  br label %12
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_omp_outlined_omp_outlined(ptr noalias noundef readonly nocapture %0, ptr noalias readnone nocapture %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef writeonly nocapture %6) #3 {
  %8 = alloca i64, align 8
  %9 = alloca i64, align 8
  %10 = alloca i64, align 8
  %11 = alloca i32, align 4
  %12 = trunc i64 %4 to i32
  %13 = icmp sgt i32 %12, 0
  %14 = icmp ne i64 %5, 0
  %15 = and i1 %13, %14
  br i1 %15, label %16, label %42

16:                                               ; preds = %7
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #2
  %17 = addrspacecast ptr %8 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #2
  %18 = addrspacecast ptr %9 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %17, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %18, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %19 = addrspacecast ptr %10 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %19, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %11) #2
  %20 = addrspacecast ptr %11 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %20, align 4, !tbaa !15
  %21 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8u(ptr nonnull @3, i32 %21, i32 33, ptr nonnull %11, ptr nonnull %8, ptr nonnull %9, ptr nonnull %10, i64 1, i64 1) #2
  %22 = load i64, ptr addrspace(5) %17, align 8, !tbaa !11
  %23 = add i64 %3, 1
  %24 = icmp ult i64 %22, %23
  br i1 %24, label %25, label %41

25:                                               ; preds = %16
  %26 = load i64, ptr addrspace(5) %19, align 8, !tbaa !11
  br label %27

27:                                               ; preds = %25, %27
  %28 = phi i64 [ %22, %25 ], [ %39, %27 ]
  %29 = udiv i64 %28, %5
  %30 = mul i64 %29, %5
  %31 = sub nuw i64 %28, %30
  %32 = shl i64 %29, 32
  %33 = ashr exact i64 %32, 32
  %34 = add i64 %31, %29
  %35 = trunc i64 %34 to i32
  %36 = mul i64 %33, %5
  %37 = getelementptr i32, ptr %6, i64 %36
  %38 = getelementptr i32, ptr %37, i64 %31
  store i32 %35, ptr %38, align 4, !tbaa !15
  %39 = add i64 %26, %28
  %40 = icmp ult i64 %39, %23
  br i1 %40, label %27, label %41

41:                                               ; preds = %27, %16
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %21) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2
  br label %42

42:                                               ; preds = %41, %7
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.umin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708303, !"_Z4stepPjim", i32 5, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a50047b1__Z4stepPjim_l5_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
