; Generated by gen.sh from Inputs/collapse4.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // collapse(4): the decomposition is not limited to three digits.
; typedef long long llint;
; void step(float* a, llint n0, llint n1, llint n2, llint n3) {
;     #pragma omp target teams distribute parallel for collapse(4) is_device_ptr(a)
;     for (llint p = 0; p < n0; ++p)
;         for (llint q = 0; q < n1; ++q)
;             for (llint r = 0; r < n2; ++r)
;                 for (llint s = 0; s < n3; ++s)
;                     a[((p * n1 + q) * n2 + r) * n3 + s] = 1.0f;
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when (%1 > 0) (%2 > 0) (%3 > 0) (%4 > 0)
; // CHECK-NEXT: arg#5: 4-D box extent=[%1, %2, %3, %4] stride=[(4 * %2 * %3 * %4), (4 * %3 * %4), (4 * %4), 4] offset=0

source_filename = "Inputs/collapse4.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef %5) local_unnamed_addr #0 {
  %7 = alloca i64, align 8
  %8 = alloca i64, align 8
  %9 = alloca i64, align 8
  %10 = alloca i32, align 4
  %11 = alloca [7 x ptr], align 8
  %12 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_kernel_environment, ptr %0) #2
  %13 = icmp eq i32 %12, -1
  br i1 %13, label %15, label %14

14:                                               ; preds = %6, %68
  ret void

15:                                               ; preds = %6
  %16 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  call void @llvm.lifetime.start.p0(i64 56, ptr nonnull %11)
  %17 = mul nsw i64 %2, %1
  %18 = mul nsw i64 %17, %3
  %19 = mul nsw i64 %18, %4
  %20 = add nsw i64 %19, -1
  %21 = icmp sgt i64 %1, 0
  %22 = icmp sgt i64 %2, 0
  %23 = and i1 %21, %22
  %24 = icmp sgt i64 %3, 0
  %25 = and i1 %23, %24
  %26 = icmp sgt i64 %4, 0
  %27 = and i1 %25, %26
  br i1 %27, label %28, label %68

28:                                               ; preds = %15
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %29 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #6, !noalias !8
  %30 = addrspacecast ptr %8 to ptr addrspace(5)
  store i64 %20, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #6, !noalias !8
  %31 = addrspacecast ptr %9 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %10) #6, !noalias !8
  %32 = addrspacecast ptr %10 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %32, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8(ptr nonnull @2, i32 %16, i32 91, ptr nonnull %10, ptr nonnull %7, ptr nonnull %8, ptr nonnull %9, i64 1, i64 128) #2, !noalias !8
  %33 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %34 = call i64 @llvm.smin.i64(i64 %33, i64 %20)
  store i64 %34, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %35 = load i64, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %36 = icmp slt i64 %35, %19
  br i1 %36, label %37, label %67

37:                                               ; preds = %28
  %38 = addrspacecast ptr %11 to ptr addrspace(5)
  %39 = getelementptr inbounds nuw i8, ptr %11, i64 8
  %40 = addrspacecast ptr %39 to ptr addrspace(5)
  %41 = getelementptr inbounds nuw i8, ptr %11, i64 16
  %42 = inttoptr i64 %1 to ptr
  %43 = addrspacecast ptr %41 to ptr addrspace(5)
  %44 = getelementptr inbounds nuw i8, ptr %11, i64 24
  %45 = inttoptr i64 %2 to ptr
  %46 = addrspacecast ptr %44 to ptr addrspace(5)
  %47 = getelementptr inbounds nuw i8, ptr %11, i64 32
  %48 = inttoptr i64 %3 to ptr
  %49 = addrspacecast ptr %47 to ptr addrspace(5)
  %50 = getelementptr inbounds nuw i8, ptr %11, i64 40
  %51 = inttoptr i64 %4 to ptr
  %52 = addrspacecast ptr %50 to ptr addrspace(5)
  %53 = getelementptr inbounds nuw i8, ptr %11, i64 48
  %54 = addrspacecast ptr %53 to ptr addrspace(5)
  br label %55

55:                                               ; preds = %37, %55
  %56 = phi i64 [ %34, %37 ], [ %65, %55 ]
  %57 = phi i64 [ %35, %37 ], [ %62, %55 ]
  %58 = inttoptr i64 %57 to ptr
  store ptr %58, ptr addrspace(5) %38, align 8, !tbaa !17, !noalias !8
  %59 = inttoptr i64 %56 to ptr
  store ptr %59, ptr addrspace(5) %40, align 8, !tbaa !17, !noalias !8
  store ptr %42, ptr addrspace(5) %43, align 8, !tbaa !17, !noalias !8
  store ptr %45, ptr addrspace(5) %46, align 8, !tbaa !17, !noalias !8
  store ptr %48, ptr addrspace(5) %49, align 8, !tbaa !17, !noalias !8
  store ptr %51, ptr addrspace(5) %52, align 8, !tbaa !17, !noalias !8
  store ptr %5, ptr addrspace(5) %54, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %16, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_omp_outlined_omp_outlined, ptr null, ptr nonnull %11, i64 7) #2, !noalias !8
  %60 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %61 = load i64, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %62 = add nsw i64 %61, %60
  store i64 %62, ptr addrspace(5) %29, align 8, !tbaa !11, !noalias !8
  %63 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %64 = add nsw i64 %63, %60
  %65 = call i64 @llvm.smin.i64(i64 %64, i64 %20)
  store i64 %65, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %66 = icmp slt i64 %62, %19
  br i1 %66, label %55, label %67

67:                                               ; preds = %55, %28
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %16) #2, !noalias !8
  br label %68

68:                                               ; preds = %15, %67
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %10) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 56, ptr nonnull %11)
  call void @__kmpc_target_deinit() #2
  br label %14
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_omp_outlined_omp_outlined(ptr noalias noundef readonly captures(none) %0, ptr noalias readnone captures(none) %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, i64 noundef %6, i64 noundef %7, ptr noundef writeonly captures(none) %8) #3 {
  %10 = alloca i64, align 8
  %11 = alloca i64, align 8
  %12 = alloca i64, align 8
  %13 = alloca i32, align 4
  %14 = icmp sgt i64 %4, 0
  %15 = icmp sgt i64 %5, 0
  %16 = and i1 %14, %15
  %17 = icmp sgt i64 %6, 0
  %18 = and i1 %16, %17
  %19 = icmp sgt i64 %7, 0
  %20 = and i1 %18, %19
  br i1 %20, label %21, label %55

21:                                               ; preds = %9
  %22 = mul i64 %7, %6
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %23 = addrspacecast ptr %10 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %11) #2
  %24 = addrspacecast ptr %11 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %23, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %24, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %12) #2
  %25 = addrspacecast ptr %12 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %25, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %13) #2
  %26 = addrspacecast ptr %13 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %26, align 4, !tbaa !15
  %27 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8(ptr nonnull @3, i32 %27, i32 33, ptr nonnull %13, ptr nonnull %10, ptr nonnull %11, ptr nonnull %12, i64 1, i64 1) #2
  %28 = load i64, ptr addrspace(5) %23, align 8, !tbaa !11
  %29 = icmp ugt i64 %28, %3
  br i1 %29, label %54, label %30

30:                                               ; preds = %21
  %31 = mul i64 %7, %5
  %32 = mul i64 %31, %6
  %33 = load i64, ptr addrspace(5) %25, align 8, !tbaa !11
  br label %34

34:                                               ; preds = %30, %34
  %35 = phi i64 [ %28, %30 ], [ %52, %34 ]
  %36 = sdiv i64 %35, %32
  %37 = mul nsw i64 %36, %32
  %38 = sub nsw i64 %35, %37
  %39 = sdiv i64 %38, %22
  %40 = mul nsw i64 %39, %22
  %41 = sub nsw i64 %38, %40
  %42 = sdiv i64 %41, %7
  %43 = mul nsw i64 %42, %7
  %44 = sub nsw i64 %41, %43
  %45 = mul nsw i64 %36, %5
  %46 = add nsw i64 %45, %39
  %47 = mul nsw i64 %46, %6
  %48 = add nsw i64 %47, %42
  %49 = mul nsw i64 %48, %7
  %50 = getelementptr float, ptr %8, i64 %49
  %51 = getelementptr float, ptr %50, i64 %44
  store float 1.000000e+00, ptr %51, align 4, !tbaa !20
  %52 = add nsw i64 %33, %35
  %53 = icmp ugt i64 %52, %3
  br i1 %53, label %54, label %34

54:                                               ; preds = %34, %21
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %27) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %13) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %12) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  br label %55

55:                                               ; preds = %54, %9
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708961, !"_Z4stepPfxxxx", i32 4, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a500451f__Z4stepPfxxxx_l4_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !13, i64 0}
