; Generated by gen.sh from Inputs/collapse2_int_offset.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // collapse(2) over int loops starting at 1, rows of C (jacobi's shape): the
; // radix is divided sign-extended and multiplied back zero-extended.
; #include <cstddef>
; void step(float* pb, const float* pa, int R, int C) {
;     #pragma omp target teams distribute parallel for collapse(2) is_device_ptr(pa, pb)
;     for (int i = 1; i <= R; ++i)
;         for (int j = 0; j < C; ++j)
;             pb[(size_t)i * C + j] = 0.5f * (pa[(size_t)(i - 1) * C + j] + pa[(size_t)(i + 1) * C + j]);
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when ((trunc i64 %1 to i32) > 0) ((trunc i64 %2 to i32) > 0)
; // CHECK-NEXT: arg#3: 2-D box extent=[(sext i32 (trunc i64 %1 to i32) to i64), (sext i32 (trunc i64 %2 to i32) to i64)] stride=[(4 * (sext i32 (trunc i64 %2 to i32) to i64))<nsw>, 4] offset=(4 * (sext i32 (trunc i64 %2 to i32) to i64))<nsw> (trusts loop-variable trunc)

source_filename = "Inputs/collapse2_int_offset.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3, ptr noundef %4) local_unnamed_addr #0 {
  %6 = alloca i64, align 8
  %7 = alloca i64, align 8
  %8 = alloca i64, align 8
  %9 = alloca i32, align 4
  %10 = alloca [6 x ptr], align 8
  %11 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_kernel_environment, ptr %0) #2
  %12 = icmp eq i32 %11, -1
  br i1 %12, label %14, label %13

13:                                               ; preds = %5, %65
  ret void

14:                                               ; preds = %5
  %15 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  %16 = and i64 %1, 4294967295
  %17 = and i64 %2, 4294967295
  call void @llvm.lifetime.start.p0(i64 48, ptr nonnull %10)
  %18 = trunc i64 %1 to i32
  %19 = trunc i64 %2 to i32
  %20 = shl nuw i64 %16, 32
  %21 = ashr exact i64 %20, 32
  %22 = shl nuw i64 %17, 32
  %23 = ashr exact i64 %22, 32
  %24 = mul nsw i64 %23, %21
  %25 = add nsw i64 %24, -1
  %26 = icmp sgt i32 %18, 0
  %27 = icmp sgt i32 %19, 0
  %28 = and i1 %26, %27
  br i1 %28, label %29, label %65

29:                                               ; preds = %14
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %6) #6, !noalias !8
  %30 = addrspacecast ptr %6 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %31 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 %25, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #6, !noalias !8
  %32 = addrspacecast ptr %8 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %32, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %9) #6, !noalias !8
  %33 = addrspacecast ptr %9 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %33, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8(ptr nonnull @2, i32 %15, i32 91, ptr nonnull %9, ptr nonnull %6, ptr nonnull %7, ptr nonnull %8, i64 1, i64 128) #2, !noalias !8
  %34 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %35 = call i64 @llvm.smin.i64(i64 %34, i64 %25)
  store i64 %35, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %36 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %37 = icmp slt i64 %36, %24
  br i1 %37, label %38, label %64

38:                                               ; preds = %29
  %39 = addrspacecast ptr %10 to ptr addrspace(5)
  %40 = getelementptr inbounds nuw i8, ptr %10, i64 8
  %41 = addrspacecast ptr %40 to ptr addrspace(5)
  %42 = getelementptr inbounds nuw i8, ptr %10, i64 16
  %43 = inttoptr i64 %16 to ptr
  %44 = addrspacecast ptr %42 to ptr addrspace(5)
  %45 = getelementptr inbounds nuw i8, ptr %10, i64 24
  %46 = inttoptr i64 %17 to ptr
  %47 = addrspacecast ptr %45 to ptr addrspace(5)
  %48 = getelementptr inbounds nuw i8, ptr %10, i64 32
  %49 = addrspacecast ptr %48 to ptr addrspace(5)
  %50 = getelementptr inbounds nuw i8, ptr %10, i64 40
  %51 = addrspacecast ptr %50 to ptr addrspace(5)
  br label %52

52:                                               ; preds = %38, %52
  %53 = phi i64 [ %35, %38 ], [ %62, %52 ]
  %54 = phi i64 [ %36, %38 ], [ %59, %52 ]
  %55 = inttoptr i64 %54 to ptr
  store ptr %55, ptr addrspace(5) %39, align 8, !tbaa !17, !noalias !8
  %56 = inttoptr i64 %53 to ptr
  store ptr %56, ptr addrspace(5) %41, align 8, !tbaa !17, !noalias !8
  store ptr %43, ptr addrspace(5) %44, align 8, !tbaa !17, !noalias !8
  store ptr %46, ptr addrspace(5) %47, align 8, !tbaa !17, !noalias !8
  store ptr %3, ptr addrspace(5) %49, align 8, !tbaa !17, !noalias !8
  store ptr %4, ptr addrspace(5) %51, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %15, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_omp_outlined_omp_outlined, ptr null, ptr nonnull %10, i64 6) #2, !noalias !8
  %57 = load i64, ptr addrspace(5) %32, align 8, !tbaa !11, !noalias !8
  %58 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %59 = add nsw i64 %58, %57
  store i64 %59, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %60 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %61 = add nsw i64 %60, %57
  %62 = call i64 @llvm.smin.i64(i64 %61, i64 %25)
  store i64 %62, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %63 = icmp slt i64 %59, %24
  br i1 %63, label %52, label %64

64:                                               ; preds = %52, %29
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %15) #2, !noalias !8
  br label %65

65:                                               ; preds = %14, %64
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %9) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 48, ptr nonnull %10)
  call void @__kmpc_target_deinit() #2
  br label %13
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_omp_outlined_omp_outlined(ptr noalias noundef readonly captures(none) %0, ptr noalias readnone captures(none) %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef writeonly captures(none) %6, ptr noundef readonly captures(none) %7) #3 {
  %9 = alloca i64, align 8
  %10 = alloca i64, align 8
  %11 = alloca i64, align 8
  %12 = alloca i32, align 4
  %13 = trunc i64 %4 to i32
  %14 = trunc i64 %5 to i32
  %15 = shl i64 %5, 32
  %16 = ashr exact i64 %15, 32
  %17 = icmp sgt i32 %13, 0
  %18 = icmp sgt i32 %14, 0
  %19 = and i1 %17, %18
  br i1 %19, label %20, label %59

20:                                               ; preds = %8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #2
  %21 = addrspacecast ptr %9 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %22 = addrspacecast ptr %10 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %21, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %22, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %11) #2
  %23 = addrspacecast ptr %11 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %23, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %12) #2
  %24 = addrspacecast ptr %12 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %24, align 4, !tbaa !15
  %25 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8(ptr nonnull @3, i32 %25, i32 33, ptr nonnull %12, ptr nonnull %9, ptr nonnull %10, ptr nonnull %11, i64 1, i64 1) #2
  %26 = load i64, ptr addrspace(5) %21, align 8, !tbaa !11
  %27 = icmp ugt i64 %26, %3
  br i1 %27, label %58, label %28

28:                                               ; preds = %20
  %29 = load i64, ptr addrspace(5) %23, align 8, !tbaa !11
  br label %30

30:                                               ; preds = %28, %30
  %31 = phi i64 [ %26, %28 ], [ %56, %30 ]
  %32 = sdiv i64 %31, %16
  %33 = mul i64 %32, %5
  %34 = sub i64 %31, %33
  %35 = shl i64 %32, 32
  %36 = ashr exact i64 %35, 32
  %37 = mul nsw i64 %36, %16
  %38 = shl i64 %34, 32
  %39 = ashr exact i64 %38, 32
  %40 = getelementptr float, ptr %7, i64 %37
  %41 = getelementptr float, ptr %40, i64 %39
  %42 = load float, ptr %41, align 4, !tbaa !20
  %43 = add i64 %35, 8589934592
  %44 = ashr exact i64 %43, 32
  %45 = mul nsw i64 %44, %16
  %46 = getelementptr float, ptr %7, i64 %45
  %47 = getelementptr float, ptr %46, i64 %39
  %48 = load float, ptr %47, align 4, !tbaa !20
  %49 = fadd float %42, %48
  %50 = fmul float %49, 5.000000e-01
  %51 = add i64 %35, 4294967296
  %52 = ashr exact i64 %51, 32
  %53 = mul nsw i64 %52, %16
  %54 = getelementptr float, ptr %6, i64 %53
  %55 = getelementptr float, ptr %54, i64 %39
  store float %50, ptr %55, align 4, !tbaa !20
  %56 = add nsw i64 %29, %31
  %57 = icmp ugt i64 %56, %3
  br i1 %57, label %58, label %30

58:                                               ; preds = %30, %20
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %25) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %12) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2
  br label %59

59:                                               ; preds = %58, %8
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708965, !"_Z4stepPfPKfii", i32 5, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a500451b__Z4stepPfPKfii_l5_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !13, i64 0}
