#!/usr/bin/env bash
# Regenerate the write-summary lit tests from Inputs/*.cpp.
#
# Each Inputs/<case>.cpp carries its own CHECK lines; <case>.ll is the RUN
# line, the source as comments and the NVPTX OpenMP device IR, so running
# the tests needs only opt. The CHECK lines were written from reviewed
# output: when a change moves one, re-derive the box by hand before
# accepting it.
#
# Usage: LLVM=<llvm prefix with NVPTX offload> ./gen.sh
set -euo pipefail
cd "$(dirname "$0")"
LLVM=${LLVM:-/projects/bfyi/lwshanbd/llvm-omp}

for src in Inputs/*.cpp; do
    name=$(basename "$src" .cpp)
    {
        echo "; Generated by gen.sh from Inputs/$name.cpp -- do not edit."
        echo ";"
        echo "; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \\"
        echo "; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s"
        echo ";"
        sed 's/^/; /; s/ *$//' "$src"
        echo
        "$LLVM/bin/clang++" -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda \
            --offload-arch=sm_90 --offload-device-only -S -emit-llvm -O3 \
            "$src" -o - | grep -v '^; ModuleID' |
            # LLVM 19 (ROCm 6.4) parses only the pre-21 spelling; LLVM 21
            # still reads it.
            sed 's/captures(none)/nocapture/g'
    } > "$name.ll"
done
