; Generated by gen.sh from Inputs/reject_step2_int.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // A 32-bit inner loop with step 2: clang masks the radix it divides by, and
; // the analysis cannot prove the mask a no-op.
; void step(float* a, int n, int m) {
;     #pragma omp target teams distribute parallel for collapse(2) is_device_ptr(a)
;     for (int i = 0; i < n; ++i)
;         for (int j = 0; j < m; j += 2)
;             a[i * m + j] = 1.0f;
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: store to ptr not analysable: store address: sign extension of index arithmetic that may have wrapped (no nsw)

source_filename = "Inputs/reject_step2_int.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3) local_unnamed_addr #0 {
  %5 = alloca i64, align 8
  %6 = alloca i64, align 8
  %7 = alloca i64, align 8
  %8 = alloca i32, align 4
  %9 = alloca [5 x ptr], align 8
  %10 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_kernel_environment, ptr %0) #2
  %11 = icmp eq i32 %10, -1
  br i1 %11, label %13, label %12

12:                                               ; preds = %4, %63
  ret void

13:                                               ; preds = %4
  %14 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  %15 = and i64 %1, 4294967295
  %16 = and i64 %2, 4294967295
  call void @llvm.lifetime.start.p0(i64 40, ptr nonnull %9)
  %17 = trunc i64 %1 to i32
  %18 = trunc i64 %2 to i32
  %19 = shl nuw i64 %15, 32
  %20 = ashr exact i64 %19, 32
  %21 = add i64 %2, 1
  %22 = lshr i64 %21, 1
  %23 = and i64 %22, 2147483647
  %24 = mul nsw i64 %23, %20
  %25 = add nsw i64 %24, -1
  %26 = icmp sgt i32 %17, 0
  %27 = icmp sgt i32 %18, 0
  %28 = and i1 %26, %27
  br i1 %28, label %29, label %63

29:                                               ; preds = %13
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %5) #6, !noalias !8
  %30 = addrspacecast ptr %5 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %6) #6, !noalias !8
  %31 = addrspacecast ptr %6 to ptr addrspace(5)
  store i64 %25, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %32 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %32, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #6, !noalias !8
  %33 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %33, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8(ptr nonnull @2, i32 %14, i32 91, ptr nonnull %8, ptr nonnull %5, ptr nonnull %6, ptr nonnull %7, i64 1, i64 128) #2, !noalias !8
  %34 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %35 = call i64 @llvm.smin.i64(i64 %34, i64 %25)
  store i64 %35, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %36 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %37 = icmp slt i64 %36, %24
  br i1 %37, label %38, label %62

38:                                               ; preds = %29
  %39 = addrspacecast ptr %9 to ptr addrspace(5)
  %40 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %41 = addrspacecast ptr %40 to ptr addrspace(5)
  %42 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %43 = inttoptr i64 %15 to ptr
  %44 = addrspacecast ptr %42 to ptr addrspace(5)
  %45 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %46 = inttoptr i64 %16 to ptr
  %47 = addrspacecast ptr %45 to ptr addrspace(5)
  %48 = getelementptr inbounds nuw i8, ptr %9, i64 32
  %49 = addrspacecast ptr %48 to ptr addrspace(5)
  br label %50

50:                                               ; preds = %38, %50
  %51 = phi i64 [ %35, %38 ], [ %60, %50 ]
  %52 = phi i64 [ %36, %38 ], [ %57, %50 ]
  %53 = inttoptr i64 %52 to ptr
  store ptr %53, ptr addrspace(5) %39, align 8, !tbaa !17, !noalias !8
  %54 = inttoptr i64 %51 to ptr
  store ptr %54, ptr addrspace(5) %41, align 8, !tbaa !17, !noalias !8
  store ptr %43, ptr addrspace(5) %44, align 8, !tbaa !17, !noalias !8
  store ptr %46, ptr addrspace(5) %47, align 8, !tbaa !17, !noalias !8
  store ptr %3, ptr addrspace(5) %49, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %14, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_omp_outlined_omp_outlined, ptr null, ptr nonnull %9, i64 5) #2, !noalias !8
  %55 = load i64, ptr addrspace(5) %32, align 8, !tbaa !11, !noalias !8
  %56 = load i64, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %57 = add nsw i64 %56, %55
  store i64 %57, ptr addrspace(5) %30, align 8, !tbaa !11, !noalias !8
  %58 = load i64, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %59 = add nsw i64 %58, %55
  %60 = call i64 @llvm.smin.i64(i64 %59, i64 %25)
  store i64 %60, ptr addrspace(5) %31, align 8, !tbaa !11, !noalias !8
  %61 = icmp slt i64 %57, %24
  br i1 %61, label %50, label %62

62:                                               ; preds = %50, %29
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %14) #2, !noalias !8
  br label %63

63:                                               ; preds = %13, %62
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %5) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 40, ptr nonnull %9)
  call void @__kmpc_target_deinit() #2
  br label %12
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_omp_outlined_omp_outlined(ptr noalias noundef readonly captures(none) %0, ptr noalias readnone captures(none) %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef writeonly captures(none) %6) #3 {
  %8 = alloca i64, align 8
  %9 = alloca i64, align 8
  %10 = alloca i64, align 8
  %11 = alloca i32, align 4
  %12 = trunc i64 %4 to i32
  %13 = trunc i64 %5 to i32
  %14 = add i64 %5, 1
  %15 = lshr i64 %14, 1
  %16 = and i64 %15, 2147483647
  %17 = icmp sgt i32 %12, 0
  %18 = icmp sgt i32 %13, 0
  %19 = and i1 %17, %18
  br i1 %19, label %20, label %45

20:                                               ; preds = %7
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #2
  %21 = addrspacecast ptr %8 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #2
  %22 = addrspacecast ptr %9 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %21, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %22, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %23 = addrspacecast ptr %10 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %23, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %11) #2
  %24 = addrspacecast ptr %11 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %24, align 4, !tbaa !15
  %25 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8(ptr nonnull @3, i32 %25, i32 33, ptr nonnull %11, ptr nonnull %8, ptr nonnull %9, ptr nonnull %10, i64 1, i64 1) #2
  %26 = load i64, ptr addrspace(5) %21, align 8, !tbaa !11
  %27 = icmp ugt i64 %26, %3
  br i1 %27, label %44, label %28

28:                                               ; preds = %20
  %29 = load i64, ptr addrspace(5) %23, align 8, !tbaa !11
  br label %30

30:                                               ; preds = %28, %30
  %31 = phi i64 [ %26, %28 ], [ %42, %30 ]
  %32 = sdiv i64 %31, %16
  %33 = trunc i64 %32 to i32
  %34 = mul i64 %32, %15
  %35 = sub i64 %31, %34
  %36 = trunc i64 %35 to i32
  %37 = shl i32 %36, 1
  %38 = mul nsw i32 %33, %13
  %39 = add nsw i32 %37, %38
  %40 = sext i32 %39 to i64
  %41 = getelementptr inbounds float, ptr %6, i64 %40
  store float 1.000000e+00, ptr %41, align 4, !tbaa !20
  %42 = add nsw i64 %29, %31
  %43 = icmp ugt i64 %42, %3
  br i1 %43, label %44, label %30

44:                                               ; preds = %30, %20
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %25) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2
  br label %45

45:                                               ; preds = %44, %7
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708958, !"_Z4stepPfii", i32 4, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a5004522__Z4stepPfii_l4_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !13, i64 0}
