; Generated by gen.sh from Inputs/reject_user_division.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // A division of the IV the user wrote, not a collapse: i / m walks a[0..k)
; // only when m > 0, which nothing here establishes (m = -2, k = -2 passes the
; // k*m > 0 precondition and writes a[0] and a[-1]). The radix m must be
; // proven positive before a box is claimed.
; typedef long long llint;
; void step(float* a, llint k, llint m) {
;     #pragma omp target teams distribute parallel for is_device_ptr(a)
;     for (llint i = 0; i < k * m; ++i)
;         a[i / m] = 1.0f;
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when ((%1 * %2) > 0)
; // CHECK-NEXT: store to ptr not analysable: store address: collapse radix %4 cannot be proven positive (a division the source wrote?)

source_filename = "Inputs/reject_user_division.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7(ptr noalias noundef %0, i64 noundef %1, i64 noundef %2, ptr noundef %3) local_unnamed_addr #0 {
  %5 = alloca i64, align 8
  %6 = alloca i64, align 8
  %7 = alloca i64, align 8
  %8 = alloca i32, align 4
  %9 = alloca [5 x ptr], align 8
  %10 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_kernel_environment, ptr %0) #2
  %11 = icmp eq i32 %10, -1
  br i1 %11, label %13, label %12

12:                                               ; preds = %4, %52
  ret void

13:                                               ; preds = %4
  %14 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  call void @llvm.lifetime.start.p0(i64 40, ptr nonnull %9)
  %15 = mul nsw i64 %2, %1
  %16 = add nsw i64 %15, -1
  %17 = icmp sgt i64 %15, 0
  br i1 %17, label %18, label %52

18:                                               ; preds = %13
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %5) #6, !noalias !8
  %19 = addrspacecast ptr %5 to ptr addrspace(5)
  store i64 0, ptr addrspace(5) %19, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %6) #6, !noalias !8
  %20 = addrspacecast ptr %6 to ptr addrspace(5)
  store i64 %16, ptr addrspace(5) %20, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %7) #6, !noalias !8
  %21 = addrspacecast ptr %7 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %21, align 8, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #6, !noalias !8
  %22 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %22, align 4, !tbaa !15, !noalias !8
  call void @__kmpc_distribute_static_init_8(ptr nonnull @2, i32 %14, i32 91, ptr nonnull %8, ptr nonnull %5, ptr nonnull %6, ptr nonnull %7, i64 1, i64 128) #2, !noalias !8
  %23 = load i64, ptr addrspace(5) %20, align 8, !tbaa !11, !noalias !8
  %24 = call i64 @llvm.smin.i64(i64 %23, i64 %16)
  store i64 %24, ptr addrspace(5) %20, align 8, !tbaa !11, !noalias !8
  %25 = load i64, ptr addrspace(5) %19, align 8, !tbaa !11, !noalias !8
  %26 = icmp slt i64 %25, %15
  br i1 %26, label %27, label %51

27:                                               ; preds = %18
  %28 = addrspacecast ptr %9 to ptr addrspace(5)
  %29 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %30 = addrspacecast ptr %29 to ptr addrspace(5)
  %31 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %32 = inttoptr i64 %1 to ptr
  %33 = addrspacecast ptr %31 to ptr addrspace(5)
  %34 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %35 = inttoptr i64 %2 to ptr
  %36 = addrspacecast ptr %34 to ptr addrspace(5)
  %37 = getelementptr inbounds nuw i8, ptr %9, i64 32
  %38 = addrspacecast ptr %37 to ptr addrspace(5)
  br label %39

39:                                               ; preds = %27, %39
  %40 = phi i64 [ %24, %27 ], [ %49, %39 ]
  %41 = phi i64 [ %25, %27 ], [ %46, %39 ]
  %42 = inttoptr i64 %41 to ptr
  store ptr %42, ptr addrspace(5) %28, align 8, !tbaa !17, !noalias !8
  %43 = inttoptr i64 %40 to ptr
  store ptr %43, ptr addrspace(5) %30, align 8, !tbaa !17, !noalias !8
  store ptr %32, ptr addrspace(5) %33, align 8, !tbaa !17, !noalias !8
  store ptr %35, ptr addrspace(5) %36, align 8, !tbaa !17, !noalias !8
  store ptr %3, ptr addrspace(5) %38, align 8, !tbaa !17, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %14, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_omp_outlined_omp_outlined, ptr null, ptr nonnull %9, i64 5) #2, !noalias !8
  %44 = load i64, ptr addrspace(5) %21, align 8, !tbaa !11, !noalias !8
  %45 = load i64, ptr addrspace(5) %19, align 8, !tbaa !11, !noalias !8
  %46 = add nsw i64 %45, %44
  store i64 %46, ptr addrspace(5) %19, align 8, !tbaa !11, !noalias !8
  %47 = load i64, ptr addrspace(5) %20, align 8, !tbaa !11, !noalias !8
  %48 = add nsw i64 %47, %44
  %49 = call i64 @llvm.smin.i64(i64 %48, i64 %16)
  store i64 %49, ptr addrspace(5) %20, align 8, !tbaa !11, !noalias !8
  %50 = icmp slt i64 %46, %15
  br i1 %50, label %39, label %51

51:                                               ; preds = %39, %18
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %14) #2, !noalias !8
  br label %52

52:                                               ; preds = %13, %51
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %5) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 40, ptr nonnull %9)
  call void @__kmpc_target_deinit() #2
  br label %12
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr captures(none)) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_omp_outlined_omp_outlined(ptr noalias noundef readonly captures(none) %0, ptr noalias readnone captures(none) %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, i64 noundef %5, ptr noundef writeonly captures(none) %6) #3 {
  %8 = alloca i64, align 8
  %9 = alloca i64, align 8
  %10 = alloca i64, align 8
  %11 = alloca i32, align 4
  %12 = mul nsw i64 %5, %4
  %13 = icmp sgt i64 %12, 0
  br i1 %13, label %14, label %31

14:                                               ; preds = %7
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %8) #2
  %15 = addrspacecast ptr %8 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %9) #2
  %16 = addrspacecast ptr %9 to ptr addrspace(5)
  store i64 %2, ptr addrspace(5) %15, align 8, !tbaa !11
  store i64 %3, ptr addrspace(5) %16, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %10) #2
  %17 = addrspacecast ptr %10 to ptr addrspace(5)
  store i64 1, ptr addrspace(5) %17, align 8, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %11) #2
  %18 = addrspacecast ptr %11 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %18, align 4, !tbaa !15
  %19 = load i32, ptr %0, align 4, !tbaa !15
  call void @__kmpc_for_static_init_8(ptr nonnull @3, i32 %19, i32 33, ptr nonnull %11, ptr nonnull %8, ptr nonnull %9, ptr nonnull %10, i64 1, i64 1) #2
  %20 = load i64, ptr addrspace(5) %15, align 8, !tbaa !11
  %21 = icmp ugt i64 %20, %3
  br i1 %21, label %30, label %22

22:                                               ; preds = %14
  %23 = load i64, ptr addrspace(5) %17, align 8, !tbaa !11
  br label %24

24:                                               ; preds = %22, %24
  %25 = phi i64 [ %20, %22 ], [ %28, %24 ]
  %26 = sdiv i64 %25, %4
  %27 = getelementptr inbounds float, ptr %6, i64 %26
  store float 1.000000e+00, ptr %27, align 4, !tbaa !20
  %28 = add nsw i64 %23, %25
  %29 = icmp ugt i64 %28, %3
  br i1 %29, label %30, label %24

30:                                               ; preds = %24, %14
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %19) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %8) #2
  br label %31

31:                                               ; preds = %30, %7
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.smin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708584, !"_Z4stepPfxx", i32 7, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a5004698__Z4stepPfxx_l7_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"long long", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"int", !13, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"any p2 pointer", !19, i64 0}
!19 = !{!"any pointer", !13, i64 0}
!20 = !{!21, !21, i64 0}
!21 = !{!"float", !13, i64 0}
