; Generated by gen.sh from Inputs/reject_unsigned_divisor.cpp -- do not edit.
;
; RUN: env GICC_MODE=write-summary %opt -load-pass-plugin=%gicc_passes_so \
; RUN:   -passes=gicc-write-summary -disable-output %s 2>&1 | %FileCheck %s
;
; // An unsigned divisor of 2^31 or more must not be read as negative.
; void step(float* a, int n, unsigned m) {
;     #pragma omp target teams distribute parallel for is_device_ptr(a)
;     for (int i = 0; i < n; ++i)
;         a[i % m] = 1.0f;
; }
;
; // CHECK: [gicc-write] kernel {{.*}}
; // CHECK-NEXT: when ((trunc i64 %1 to i32) > 0)
; // CHECK-NEXT: store to ptr not analysable: store address: collapse radix (zext i32 (trunc i64 %6 to i32) to i64) cannot be proven positive (a division the source wrote?)

source_filename = "Inputs/reject_unsigned_divisor.cpp"
target datalayout = "e-p6:32:32-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr constant i32 0
@0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @0 }, align 8
@__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_kernel_environment = weak_odr protected constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0 }, ptr @1, ptr @__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_dynamic_environment }
@2 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @0 }, align 8
@3 = private unnamed_addr constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @0 }, align 8

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected ptx_kernel void @__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3(ptr noalias noundef %0, i64 noundef %1, ptr noundef %2, i64 noundef %3) local_unnamed_addr #0 {
  %5 = alloca i32, align 4
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  %9 = alloca [5 x ptr], align 8
  %10 = tail call i32 @__kmpc_target_init(ptr nonnull @__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_kernel_environment, ptr %0) #2
  %11 = icmp eq i32 %10, -1
  br i1 %11, label %13, label %12

12:                                               ; preds = %4, %56
  ret void

13:                                               ; preds = %4
  %14 = tail call i32 @__kmpc_global_thread_num(ptr nonnull @1) #2
  %15 = and i64 %1, 4294967295
  %16 = and i64 %3, 4294967295
  call void @llvm.lifetime.start.p0(i64 40, ptr nonnull %9)
  %17 = trunc i64 %1 to i32
  %18 = add nsw i32 %17, -1
  %19 = icmp sgt i32 %17, 0
  br i1 %19, label %20, label %56

20:                                               ; preds = %13
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %5) #6, !noalias !8
  %21 = addrspacecast ptr %5 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %21, align 4, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %6) #6, !noalias !8
  %22 = addrspacecast ptr %6 to ptr addrspace(5)
  store i32 %18, ptr addrspace(5) %22, align 4, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %7) #6, !noalias !8
  %23 = addrspacecast ptr %7 to ptr addrspace(5)
  store i32 1, ptr addrspace(5) %23, align 4, !tbaa !11, !noalias !8
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #6, !noalias !8
  %24 = addrspacecast ptr %8 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %24, align 4, !tbaa !11, !noalias !8
  call void @__kmpc_distribute_static_init_4(ptr nonnull @2, i32 %14, i32 91, ptr nonnull %8, ptr nonnull %5, ptr nonnull %6, ptr nonnull %7, i32 1, i32 128) #2, !noalias !8
  %25 = load i32, ptr addrspace(5) %22, align 4, !tbaa !11, !noalias !8
  %26 = call i32 @llvm.smin.i32(i32 %25, i32 %18)
  store i32 %26, ptr addrspace(5) %22, align 4, !tbaa !11, !noalias !8
  %27 = load i32, ptr addrspace(5) %21, align 4, !tbaa !11, !noalias !8
  %28 = icmp slt i32 %27, %17
  br i1 %28, label %29, label %55

29:                                               ; preds = %20
  %30 = addrspacecast ptr %9 to ptr addrspace(5)
  %31 = getelementptr inbounds nuw i8, ptr %9, i64 8
  %32 = addrspacecast ptr %31 to ptr addrspace(5)
  %33 = getelementptr inbounds nuw i8, ptr %9, i64 16
  %34 = inttoptr i64 %15 to ptr
  %35 = addrspacecast ptr %33 to ptr addrspace(5)
  %36 = getelementptr inbounds nuw i8, ptr %9, i64 24
  %37 = addrspacecast ptr %36 to ptr addrspace(5)
  %38 = getelementptr inbounds nuw i8, ptr %9, i64 32
  %39 = inttoptr i64 %16 to ptr
  %40 = addrspacecast ptr %38 to ptr addrspace(5)
  br label %41

41:                                               ; preds = %29, %41
  %42 = phi i32 [ %26, %29 ], [ %53, %41 ]
  %43 = phi i32 [ %27, %29 ], [ %50, %41 ]
  %44 = zext i32 %43 to i64
  %45 = zext i32 %42 to i64
  %46 = inttoptr i64 %44 to ptr
  store ptr %46, ptr addrspace(5) %30, align 8, !tbaa !15, !noalias !8
  %47 = inttoptr i64 %45 to ptr
  store ptr %47, ptr addrspace(5) %32, align 8, !tbaa !15, !noalias !8
  store ptr %34, ptr addrspace(5) %35, align 8, !tbaa !15, !noalias !8
  store ptr %2, ptr addrspace(5) %37, align 8, !tbaa !15, !noalias !8
  store ptr %39, ptr addrspace(5) %40, align 8, !tbaa !15, !noalias !8
  call void @__kmpc_parallel_51(ptr nonnull @1, i32 %14, i32 1, i32 -1, i32 -1, ptr nonnull @__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_omp_outlined_omp_outlined, ptr null, ptr nonnull %9, i64 5) #2, !noalias !8
  %48 = load i32, ptr addrspace(5) %23, align 4, !tbaa !11, !noalias !8
  %49 = load i32, ptr addrspace(5) %21, align 4, !tbaa !11, !noalias !8
  %50 = add nsw i32 %49, %48
  store i32 %50, ptr addrspace(5) %21, align 4, !tbaa !11, !noalias !8
  %51 = load i32, ptr addrspace(5) %22, align 4, !tbaa !11, !noalias !8
  %52 = add nsw i32 %51, %48
  %53 = call i32 @llvm.smin.i32(i32 %52, i32 %18)
  store i32 %53, ptr addrspace(5) %22, align 4, !tbaa !11, !noalias !8
  %54 = icmp slt i32 %50, %17
  br i1 %54, label %41, label %55

55:                                               ; preds = %41, %20
  call void @__kmpc_distribute_static_fini(ptr nonnull @2, i32 %14) #2, !noalias !8
  br label %56

56:                                               ; preds = %13, %55
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %7) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %6) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %5) #2, !noalias !8
  call void @llvm.lifetime.end.p0(i64 40, ptr nonnull %9)
  call void @__kmpc_target_deinit() #2
  br label %12
}

declare i32 @__kmpc_target_init(ptr, ptr) local_unnamed_addr

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_omp_outlined_omp_outlined(ptr noalias noundef readonly nocapture %0, ptr noalias readnone nocapture %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef writeonly nocapture %5, i64 noundef %6) #3 {
  %8 = alloca i32, align 4
  %9 = alloca i32, align 4
  %10 = alloca i32, align 4
  %11 = alloca i32, align 4
  %12 = trunc i64 %4 to i32
  %13 = trunc i64 %6 to i32
  %14 = icmp sgt i32 %12, 0
  br i1 %14, label %15, label %37

15:                                               ; preds = %7
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %8) #2
  %16 = addrspacecast ptr %8 to ptr addrspace(5)
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %9) #2
  %17 = addrspacecast ptr %9 to ptr addrspace(5)
  %18 = trunc i64 %2 to i32
  %19 = trunc i64 %3 to i32
  store i32 %18, ptr addrspace(5) %16, align 4, !tbaa !11
  store i32 %19, ptr addrspace(5) %17, align 4, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %10) #2
  %20 = addrspacecast ptr %10 to ptr addrspace(5)
  store i32 1, ptr addrspace(5) %20, align 4, !tbaa !11
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %11) #2
  %21 = addrspacecast ptr %11 to ptr addrspace(5)
  store i32 0, ptr addrspace(5) %21, align 4, !tbaa !11
  %22 = load i32, ptr %0, align 4, !tbaa !11
  call void @__kmpc_for_static_init_4(ptr nonnull @3, i32 %22, i32 33, ptr nonnull %11, ptr nonnull %8, ptr nonnull %9, ptr nonnull %10, i32 1, i32 1) #2
  %23 = load i32, ptr addrspace(5) %16, align 4, !tbaa !11
  %24 = sext i32 %23 to i64
  %25 = icmp ult i64 %3, %24
  br i1 %25, label %36, label %26

26:                                               ; preds = %15
  %27 = load i32, ptr addrspace(5) %20, align 4, !tbaa !11
  br label %28

28:                                               ; preds = %26, %28
  %29 = phi i32 [ %23, %26 ], [ %33, %28 ]
  %30 = urem i32 %29, %13
  %31 = zext i32 %30 to i64
  %32 = getelementptr inbounds nuw float, ptr %5, i64 %31
  store float 1.000000e+00, ptr %32, align 4, !tbaa !18
  %33 = add nsw i32 %27, %29
  %34 = sext i32 %33 to i64
  %35 = icmp ult i64 %3, %34
  br i1 %35, label %36, label %28

36:                                               ; preds = %28, %15
  call void @__kmpc_for_static_fini(ptr nonnull @3, i32 %22) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %11) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %10) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %9) #2
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %8) #2
  br label %37

37:                                               ; preds = %36, %7
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_4(ptr, i32, i32, ptr, ptr, ptr, ptr, i32, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_for_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #5

attributes #0 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "nvvm.maxntid"="128" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_90" "target-features"="+ptx87,+sm_90" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}
!llvm.ident = !{!7}

!0 = !{i32 0, i32 1808112826, i32 -1526708582, !"_Z4stepPfij", i32 3, i32 0, i32 0}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{!"clang version 21.1.8"}
!8 = !{!9}
!9 = distinct !{!9, !10, !"__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_omp_outlined: argument 0"}
!10 = distinct !{!10, !"__omp_offloading_6bc59cba_a500469a__Z4stepPfij_l3_omp_outlined"}
!11 = !{!12, !12, i64 0}
!12 = !{!"int", !13, i64 0}
!13 = !{!"omnipotent char", !14, i64 0}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, !16, i64 0}
!16 = !{!"any p2 pointer", !17, i64 0}
!17 = !{!"any pointer", !13, i64 0}
!18 = !{!19, !19, i64 0}
!19 = !{!"float", !13, i64 0}
