#!/bin/bash
# gicc-stub-sidecar.sh — ensure a sidecar source file exists.
#
# Usage: gicc-stub-sidecar.sh <sidecar_src> <main_src>
#
# The plugin produces <sidecar_src> as a side effect of the main TU
# compile. CMake has no way to model that side effect, so the build
# graph would deadlock without a rule to "produce" <sidecar_src>.
#
# This wrapper provides such a rule. It writes a no-op placeholder ONLY
# if <sidecar_src> doesn't already exist. When the plugin overwrites it
# during the next main-TU compile, that newer content is what the
# subsequent sidecar-object recompile picks up.
set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "usage: $0 <sidecar_src> <main_src>" >&2
    exit 2
fi

src="$1"
main="$2"

if [[ -f "$src" ]]; then
    # Already present (real one from a previous plugin run, or the
    # placeholder we wrote earlier). Touch so make sees this rule did
    # something this build (otherwise it may keep re-running it).
    touch "$src"
    exit 0
fi

mkdir -p "$(dirname "$src")"
cat > "$src" <<EOF
// Placeholder generated by gicc-stub-sidecar.sh for $main.
// The plugin will overwrite this once the main TU has been compiled
// at least once. Re-run \`make\` to pick up the real trace functions.
EOF
