# Makefile.nvshmem - Build NVSHMEM benchmarks
#
# Usage:
#   module purge
#   module load genesis common proxy slurm gcc/11.4.1 cuda/12.4.131
#   module use /shared/data1/Projects/CSE_HPC/apps/modules/aarch64/maple
#   module load openmpi-gcc/5.0.5/cuda.12.4 nvhpc/24.5.cuda_12.4
#   make -f Makefile.nvshmem

# NVHPC paths
NVHPC_ROOT ?= /hrtc/apps/devtools/nvidia-hpcsdk/aarch64/24.5-cuda12.4.131/Linux_aarch64/24.5
NVSHMEM_HOME ?= $(NVHPC_ROOT)/comm_libs/nvshmem
CUDA_HOME ?= /hrtc/apps/cuda/12.4.131/aarch64/rocky9

# Use system MPI (openmpi-gcc)
MPI_HOME ?= /hrtc/apps/mpi/openmpi/aarch64/rocky9/5.0.5/gcc/11.4.1/cuda.12.4

# Compilers
NVCC = $(NVHPC_ROOT)/compilers/bin/nvcc
MPICXX = $(MPI_HOME)/bin/mpic++

# Flags
NVCC_GENCODE = -gencode=arch=compute_90,code=sm_90
NVCCFLAGS = -dc -ccbin g++ -std=c++17 $(NVCC_GENCODE) -O3
INCLUDES = -I$(NVSHMEM_HOME)/include -I$(CUDA_HOME)/include -I$(MPI_HOME)/include
LIBDIRS = -L$(NVSHMEM_HOME)/lib -L$(CUDA_HOME)/lib64 -L$(MPI_HOME)/lib
LDFLAGS = $(LIBDIRS) -lnvshmem_host -lnvshmem_device -lcudart -lcuda

# Targets
TARGETS = nvshmem_pingpong_bench nvshmem_simple_bench

all: $(TARGETS)

nvshmem_pingpong_bench: nvshmem_pingpong_bench.cu
	$(NVCC) $(NVCCFLAGS) $(INCLUDES) $< -c -o $@.o
	$(NVCC) $(NVCC_GENCODE) -dlink $@.o -o $@.dlink.o $(LIBDIRS) -lnvshmem_device
	$(MPICXX) $@.o $@.dlink.o -o $@ $(LDFLAGS)
	rm -f $@.o $@.dlink.o

nvshmem_simple_bench: nvshmem_simple_bench.cu
	$(NVCC) $(NVCCFLAGS) $(INCLUDES) $< -c -o $@.o
	$(NVCC) $(NVCC_GENCODE) -dlink $@.o -o $@.dlink.o $(LIBDIRS) -lnvshmem_device
	$(MPICXX) $@.o $@.dlink.o -o $@ $(LDFLAGS)
	rm -f $@.o $@.dlink.o

clean:
	rm -f $(TARGETS) *.o

.PHONY: all clean
